package com.ecej.mapper;

import com.ecej.po.ICHCustomerInfo;
import com.ecej.po.ICHCustomerInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ICHCustomerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichcustomerinfo
     *
     * @mbg.generated
     */
    long countByExample(ICHCustomerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichcustomerinfo
     *
     * @mbg.generated
     */
    int deleteByExample(ICHCustomerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichcustomerinfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichcustomerinfo
     *
     * @mbg.generated
     */
    int insert(ICHCustomerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichcustomerinfo
     *
     * @mbg.generated
     */
    int insertSelective(ICHCustomerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichcustomerinfo
     *
     * @mbg.generated
     */
    List<ICHCustomerInfo> selectByExample(ICHCustomerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichcustomerinfo
     *
     * @mbg.generated
     */
    ICHCustomerInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichcustomerinfo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ICHCustomerInfo record, @Param("example") ICHCustomerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichcustomerinfo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ICHCustomerInfo record, @Param("example") ICHCustomerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichcustomerinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ICHCustomerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichcustomerinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ICHCustomerInfo record);
}