package com.ecej.mapper;

import com.ecej.po.ICHGasEqui;
import com.ecej.po.ICHGasEquiExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ICHGasEquiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichgasequi
     *
     * @mbg.generated
     */
    long countByExample(ICHGasEquiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichgasequi
     *
     * @mbg.generated
     */
    int deleteByExample(ICHGasEquiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichgasequi
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichgasequi
     *
     * @mbg.generated
     */
    int insert(ICHGasEqui record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichgasequi
     *
     * @mbg.generated
     */
    int insertSelective(ICHGasEqui record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichgasequi
     *
     * @mbg.generated
     */
    List<ICHGasEqui> selectByExample(ICHGasEquiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichgasequi
     *
     * @mbg.generated
     */
    ICHGasEqui selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichgasequi
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ICHGasEqui record, @Param("example") ICHGasEquiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichgasequi
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ICHGasEqui record, @Param("example") ICHGasEquiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichgasequi
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ICHGasEqui record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichgasequi
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ICHGasEqui record);

    void deleteDistinctData();
}