package com.ecej.mapper;

import com.ecej.po.ICHReadingPlan;
import com.ecej.po.ICHReadingPlanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ICHReadingPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichreadingplan
     *
     * @mbg.generated
     */
    long countByExample(ICHReadingPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichreadingplan
     *
     * @mbg.generated
     */
    int deleteByExample(ICHReadingPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichreadingplan
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichreadingplan
     *
     * @mbg.generated
     */
    int insert(ICHReadingPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichreadingplan
     *
     * @mbg.generated
     */
    int insertSelective(ICHReadingPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichreadingplan
     *
     * @mbg.generated
     */
    List<ICHReadingPlan> selectByExample(ICHReadingPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichreadingplan
     *
     * @mbg.generated
     */
    ICHReadingPlan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichreadingplan
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ICHReadingPlan record, @Param("example") ICHReadingPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichreadingplan
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ICHReadingPlan record, @Param("example") ICHReadingPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichreadingplan
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ICHReadingPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichreadingplan
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ICHReadingPlan record);
}