package com.ecej.po;

import java.io.Serializable;

/**
 * Created by wyx on 2017-10-09.
 * 
 * @author wyx
 * @title ichcustomerinfo
 * @date 2017-10-09
 */
public class ICHCustomerInfo implements Serializable {
    /**
     * 
     * id 
     * id
     */
    private Integer id;

    /**
     * 
     * anlage 
     * anlage
     */
    private String anlage;

    /**
     * 
     * bauform 
     * bauform
     */
    private String bauform;

    /**
     * 
     * bauklas 
     * bauklas
     */
    private String bauklas;

    /**
     * 
     * branche 
     * branche
     */
    private String branche;

    /**
     * 
     * consnumber1 
     * consnumber1
     */
    private String consnumber1;

    /**
     * 
     * consnumber2 
     * consnumber2
     */
    private String consnumber2;

    /**
     * 
     * consnumber3 
     * consnumber3
     */
    private String consnumber3;

    /**
     * 
     * devloc 
     * devloc
     */
    private String devloc;

    /**
     * 
     * nameOrg1 
     * name_org1
     */
    private String nameOrg1;

    /**
     * 
     * opeBp 
     * ope_bp
     */
    private String opeBp;

    /**
     * 
     * partner 
     * partner
     */
    private String partner;

    /**
     * 
     * planId 
     * plan_id
     */
    private Integer planId;

    /**
     * 
     * r3Usrer1 
     * r3_usrer1
     */
    private String r3Usrer1;

    /**
     * 
     * r3Usrer2 
     * r3_usrer2
     */
    private String r3Usrer2;

    /**
     * 
     * r3Usrer3 
     * r3_usrer3
     */
    private String r3Usrer3;

    /**
     * 
     * r3Usrer4 
     * r3_usrer4
     */
    private String r3Usrer4;

    /**
     * 
     * r3Usrer5 
     * r3_usrer5
     */
    private String r3Usrer5;

    /**
     * 
     * roomnumber 
     * roomnumber
     */
    private String roomnumber;

    /**
     * 
     * serge 
     * serge
     */
    private String serge;

    /**
     * 
     * strSuppl1 
     * str_suppl1
     */
    private String strSuppl1;

    /**
     * 
     * strSuppl2 
     * str_suppl2
     */
    private String strSuppl2;

    /**
     * 
     * strSuppl3 
     * str_suppl3
     */
    private String strSuppl3;

    /**
     * 
     * street 
     * street
     */
    private String street;

    /**
     * 
     * tariftyp 
     * tariftyp
     */
    private String tariftyp;

    /**
     * 
     * telNumber1 
     * tel_number1
     */
    private String telNumber1;

    /**
     * 
     * telNumber2 
     * tel_number2
     */
    private String telNumber2;

    /**
     * 
     * telNumber3 
     * tel_number3
     */
    private String telNumber3;

    /**
     * 
     * telNumber4 
     * tel_number4
     */
    private String telNumber4;

    /**
     * 
     * telNumber5 
     * tel_number5
     */
    private String telNumber5;

    /**
     * 
     * uploadFlag 
     * upload_flag
     */
    private String uploadFlag;

    /**
     * 
     * vertrag 
     * vertrag
     */
    private String vertrag;

    /**
     * 
     * vstelle 
     * vstelle
     */
    private String vstelle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ichcustomerinfo
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichcustomerinfo.id
     *
     * @return the value of ichcustomerinfo.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichcustomerinfo.id
     *
     * @param id the value for ichcustomerinfo.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichcustomerinfo.anlage
     *
     * @return the value of ichcustomerinfo.anlage
     *
     * @mbg.generated
     */
    public String getAnlage() {
        return anlage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichcustomerinfo.anlage
     *
     * @param anlage the value for ichcustomerinfo.anlage
     *
     * @mbg.generated
     */
    public void setAnlage(String anlage) {
        this.anlage = anlage == null ? null : anlage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichcustomerinfo.bauform
     *
     * @return the value of ichcustomerinfo.bauform
     *
     * @mbg.generated
     */
    public String getBauform() {
        return bauform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichcustomerinfo.bauform
     *
     * @param bauform the value for ichcustomerinfo.bauform
     *
     * @mbg.generated
     */
    public void setBauform(String bauform) {
        this.bauform = bauform == null ? null : bauform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichcustomerinfo.bauklas
     *
     * @return the value of ichcustomerinfo.bauklas
     *
     * @mbg.generated
     */
    public String getBauklas() {
        return bauklas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichcustomerinfo.bauklas
     *
     * @param bauklas the value for ichcustomerinfo.bauklas
     *
     * @mbg.generated
     */
    public void setBauklas(String bauklas) {
        this.bauklas = bauklas == null ? null : bauklas.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichcustomerinfo.branche
     *
     * @return the value of ichcustomerinfo.branche
     *
     * @mbg.generated
     */
    public String getBranche() {
        return branche;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichcustomerinfo.branche
     *
     * @param branche the value for ichcustomerinfo.branche
     *
     * @mbg.generated
     */
    public void setBranche(String branche) {
        this.branche = branche == null ? null : branche.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichcustomerinfo.consnumber1
     *
     * @return the value of ichcustomerinfo.consnumber1
     *
     * @mbg.generated
     */
    public String getConsnumber1() {
        return consnumber1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichcustomerinfo.consnumber1
     *
     * @param consnumber1 the value for ichcustomerinfo.consnumber1
     *
     * @mbg.generated
     */
    public void setConsnumber1(String consnumber1) {
        this.consnumber1 = consnumber1 == null ? null : consnumber1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichcustomerinfo.consnumber2
     *
     * @return the value of ichcustomerinfo.consnumber2
     *
     * @mbg.generated
     */
    public String getConsnumber2() {
        return consnumber2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichcustomerinfo.consnumber2
     *
     * @param consnumber2 the value for ichcustomerinfo.consnumber2
     *
     * @mbg.generated
     */
    public void setConsnumber2(String consnumber2) {
        this.consnumber2 = consnumber2 == null ? null : consnumber2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichcustomerinfo.consnumber3
     *
     * @return the value of ichcustomerinfo.consnumber3
     *
     * @mbg.generated
     */
    public String getConsnumber3() {
        return consnumber3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichcustomerinfo.consnumber3
     *
     * @param consnumber3 the value for ichcustomerinfo.consnumber3
     *
     * @mbg.generated
     */
    public void setConsnumber3(String consnumber3) {
        this.consnumber3 = consnumber3 == null ? null : consnumber3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichcustomerinfo.devloc
     *
     * @return the value of ichcustomerinfo.devloc
     *
     * @mbg.generated
     */
    public String getDevloc() {
        return devloc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichcustomerinfo.devloc
     *
     * @param devloc the value for ichcustomerinfo.devloc
     *
     * @mbg.generated
     */
    public void setDevloc(String devloc) {
        this.devloc = devloc == null ? null : devloc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichcustomerinfo.name_org1
     *
     * @return the value of ichcustomerinfo.name_org1
     *
     * @mbg.generated
     */
    public String getNameOrg1() {
        return nameOrg1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichcustomerinfo.name_org1
     *
     * @param nameOrg1 the value for ichcustomerinfo.name_org1
     *
     * @mbg.generated
     */
    public void setNameOrg1(String nameOrg1) {
        this.nameOrg1 = nameOrg1 == null ? null : nameOrg1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichcustomerinfo.ope_bp
     *
     * @return the value of ichcustomerinfo.ope_bp
     *
     * @mbg.generated
     */
    public String getOpeBp() {
        return opeBp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichcustomerinfo.ope_bp
     *
     * @param opeBp the value for ichcustomerinfo.ope_bp
     *
     * @mbg.generated
     */
    public void setOpeBp(String opeBp) {
        this.opeBp = opeBp == null ? null : opeBp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichcustomerinfo.partner
     *
     * @return the value of ichcustomerinfo.partner
     *
     * @mbg.generated
     */
    public String getPartner() {
        return partner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichcustomerinfo.partner
     *
     * @param partner the value for ichcustomerinfo.partner
     *
     * @mbg.generated
     */
    public void setPartner(String partner) {
        this.partner = partner == null ? null : partner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichcustomerinfo.plan_id
     *
     * @return the value of ichcustomerinfo.plan_id
     *
     * @mbg.generated
     */
    public Integer getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichcustomerinfo.plan_id
     *
     * @param planId the value for ichcustomerinfo.plan_id
     *
     * @mbg.generated
     */
    public void setPlanId(Integer planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichcustomerinfo.r3_usrer1
     *
     * @return the value of ichcustomerinfo.r3_usrer1
     *
     * @mbg.generated
     */
    public String getR3Usrer1() {
        return r3Usrer1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichcustomerinfo.r3_usrer1
     *
     * @param r3Usrer1 the value for ichcustomerinfo.r3_usrer1
     *
     * @mbg.generated
     */
    public void setR3Usrer1(String r3Usrer1) {
        this.r3Usrer1 = r3Usrer1 == null ? null : r3Usrer1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichcustomerinfo.r3_usrer2
     *
     * @return the value of ichcustomerinfo.r3_usrer2
     *
     * @mbg.generated
     */
    public String getR3Usrer2() {
        return r3Usrer2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichcustomerinfo.r3_usrer2
     *
     * @param r3Usrer2 the value for ichcustomerinfo.r3_usrer2
     *
     * @mbg.generated
     */
    public void setR3Usrer2(String r3Usrer2) {
        this.r3Usrer2 = r3Usrer2 == null ? null : r3Usrer2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichcustomerinfo.r3_usrer3
     *
     * @return the value of ichcustomerinfo.r3_usrer3
     *
     * @mbg.generated
     */
    public String getR3Usrer3() {
        return r3Usrer3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichcustomerinfo.r3_usrer3
     *
     * @param r3Usrer3 the value for ichcustomerinfo.r3_usrer3
     *
     * @mbg.generated
     */
    public void setR3Usrer3(String r3Usrer3) {
        this.r3Usrer3 = r3Usrer3 == null ? null : r3Usrer3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichcustomerinfo.r3_usrer4
     *
     * @return the value of ichcustomerinfo.r3_usrer4
     *
     * @mbg.generated
     */
    public String getR3Usrer4() {
        return r3Usrer4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichcustomerinfo.r3_usrer4
     *
     * @param r3Usrer4 the value for ichcustomerinfo.r3_usrer4
     *
     * @mbg.generated
     */
    public void setR3Usrer4(String r3Usrer4) {
        this.r3Usrer4 = r3Usrer4 == null ? null : r3Usrer4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichcustomerinfo.r3_usrer5
     *
     * @return the value of ichcustomerinfo.r3_usrer5
     *
     * @mbg.generated
     */
    public String getR3Usrer5() {
        return r3Usrer5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichcustomerinfo.r3_usrer5
     *
     * @param r3Usrer5 the value for ichcustomerinfo.r3_usrer5
     *
     * @mbg.generated
     */
    public void setR3Usrer5(String r3Usrer5) {
        this.r3Usrer5 = r3Usrer5 == null ? null : r3Usrer5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichcustomerinfo.roomnumber
     *
     * @return the value of ichcustomerinfo.roomnumber
     *
     * @mbg.generated
     */
    public String getRoomnumber() {
        return roomnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichcustomerinfo.roomnumber
     *
     * @param roomnumber the value for ichcustomerinfo.roomnumber
     *
     * @mbg.generated
     */
    public void setRoomnumber(String roomnumber) {
        this.roomnumber = roomnumber == null ? null : roomnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichcustomerinfo.serge
     *
     * @return the value of ichcustomerinfo.serge
     *
     * @mbg.generated
     */
    public String getSerge() {
        return serge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichcustomerinfo.serge
     *
     * @param serge the value for ichcustomerinfo.serge
     *
     * @mbg.generated
     */
    public void setSerge(String serge) {
        this.serge = serge == null ? null : serge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichcustomerinfo.str_suppl1
     *
     * @return the value of ichcustomerinfo.str_suppl1
     *
     * @mbg.generated
     */
    public String getStrSuppl1() {
        return strSuppl1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichcustomerinfo.str_suppl1
     *
     * @param strSuppl1 the value for ichcustomerinfo.str_suppl1
     *
     * @mbg.generated
     */
    public void setStrSuppl1(String strSuppl1) {
        this.strSuppl1 = strSuppl1 == null ? null : strSuppl1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichcustomerinfo.str_suppl2
     *
     * @return the value of ichcustomerinfo.str_suppl2
     *
     * @mbg.generated
     */
    public String getStrSuppl2() {
        return strSuppl2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichcustomerinfo.str_suppl2
     *
     * @param strSuppl2 the value for ichcustomerinfo.str_suppl2
     *
     * @mbg.generated
     */
    public void setStrSuppl2(String strSuppl2) {
        this.strSuppl2 = strSuppl2 == null ? null : strSuppl2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichcustomerinfo.str_suppl3
     *
     * @return the value of ichcustomerinfo.str_suppl3
     *
     * @mbg.generated
     */
    public String getStrSuppl3() {
        return strSuppl3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichcustomerinfo.str_suppl3
     *
     * @param strSuppl3 the value for ichcustomerinfo.str_suppl3
     *
     * @mbg.generated
     */
    public void setStrSuppl3(String strSuppl3) {
        this.strSuppl3 = strSuppl3 == null ? null : strSuppl3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichcustomerinfo.street
     *
     * @return the value of ichcustomerinfo.street
     *
     * @mbg.generated
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichcustomerinfo.street
     *
     * @param street the value for ichcustomerinfo.street
     *
     * @mbg.generated
     */
    public void setStreet(String street) {
        this.street = street == null ? null : street.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichcustomerinfo.tariftyp
     *
     * @return the value of ichcustomerinfo.tariftyp
     *
     * @mbg.generated
     */
    public String getTariftyp() {
        return tariftyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichcustomerinfo.tariftyp
     *
     * @param tariftyp the value for ichcustomerinfo.tariftyp
     *
     * @mbg.generated
     */
    public void setTariftyp(String tariftyp) {
        this.tariftyp = tariftyp == null ? null : tariftyp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichcustomerinfo.tel_number1
     *
     * @return the value of ichcustomerinfo.tel_number1
     *
     * @mbg.generated
     */
    public String getTelNumber1() {
        return telNumber1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichcustomerinfo.tel_number1
     *
     * @param telNumber1 the value for ichcustomerinfo.tel_number1
     *
     * @mbg.generated
     */
    public void setTelNumber1(String telNumber1) {
        this.telNumber1 = telNumber1 == null ? null : telNumber1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichcustomerinfo.tel_number2
     *
     * @return the value of ichcustomerinfo.tel_number2
     *
     * @mbg.generated
     */
    public String getTelNumber2() {
        return telNumber2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichcustomerinfo.tel_number2
     *
     * @param telNumber2 the value for ichcustomerinfo.tel_number2
     *
     * @mbg.generated
     */
    public void setTelNumber2(String telNumber2) {
        this.telNumber2 = telNumber2 == null ? null : telNumber2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichcustomerinfo.tel_number3
     *
     * @return the value of ichcustomerinfo.tel_number3
     *
     * @mbg.generated
     */
    public String getTelNumber3() {
        return telNumber3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichcustomerinfo.tel_number3
     *
     * @param telNumber3 the value for ichcustomerinfo.tel_number3
     *
     * @mbg.generated
     */
    public void setTelNumber3(String telNumber3) {
        this.telNumber3 = telNumber3 == null ? null : telNumber3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichcustomerinfo.tel_number4
     *
     * @return the value of ichcustomerinfo.tel_number4
     *
     * @mbg.generated
     */
    public String getTelNumber4() {
        return telNumber4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichcustomerinfo.tel_number4
     *
     * @param telNumber4 the value for ichcustomerinfo.tel_number4
     *
     * @mbg.generated
     */
    public void setTelNumber4(String telNumber4) {
        this.telNumber4 = telNumber4 == null ? null : telNumber4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichcustomerinfo.tel_number5
     *
     * @return the value of ichcustomerinfo.tel_number5
     *
     * @mbg.generated
     */
    public String getTelNumber5() {
        return telNumber5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichcustomerinfo.tel_number5
     *
     * @param telNumber5 the value for ichcustomerinfo.tel_number5
     *
     * @mbg.generated
     */
    public void setTelNumber5(String telNumber5) {
        this.telNumber5 = telNumber5 == null ? null : telNumber5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichcustomerinfo.upload_flag
     *
     * @return the value of ichcustomerinfo.upload_flag
     *
     * @mbg.generated
     */
    public String getUploadFlag() {
        return uploadFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichcustomerinfo.upload_flag
     *
     * @param uploadFlag the value for ichcustomerinfo.upload_flag
     *
     * @mbg.generated
     */
    public void setUploadFlag(String uploadFlag) {
        this.uploadFlag = uploadFlag == null ? null : uploadFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichcustomerinfo.vertrag
     *
     * @return the value of ichcustomerinfo.vertrag
     *
     * @mbg.generated
     */
    public String getVertrag() {
        return vertrag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichcustomerinfo.vertrag
     *
     * @param vertrag the value for ichcustomerinfo.vertrag
     *
     * @mbg.generated
     */
    public void setVertrag(String vertrag) {
        this.vertrag = vertrag == null ? null : vertrag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichcustomerinfo.vstelle
     *
     * @return the value of ichcustomerinfo.vstelle
     *
     * @mbg.generated
     */
    public String getVstelle() {
        return vstelle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichcustomerinfo.vstelle
     *
     * @param vstelle the value for ichcustomerinfo.vstelle
     *
     * @mbg.generated
     */
    public void setVstelle(String vstelle) {
        this.vstelle = vstelle == null ? null : vstelle.trim();
    }
}