package com.ecej.po;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class ICHCustomerInfoExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ichcustomerinfo
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ichcustomerinfo
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ichcustomerinfo
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ichcustomerinfo
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichcustomerinfo
     *
     * @mbg.generated
     */
    public ICHCustomerInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichcustomerinfo
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichcustomerinfo
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichcustomerinfo
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichcustomerinfo
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichcustomerinfo
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichcustomerinfo
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichcustomerinfo
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichcustomerinfo
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichcustomerinfo
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichcustomerinfo
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ichcustomerinfo
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria implements Serializable {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAnlageIsNull() {
            addCriterion("anlage is null");
            return (Criteria) this;
        }

        public Criteria andAnlageIsNotNull() {
            addCriterion("anlage is not null");
            return (Criteria) this;
        }

        public Criteria andAnlageEqualTo(String value) {
            addCriterion("anlage =", value, "anlage");
            return (Criteria) this;
        }

        public Criteria andAnlageNotEqualTo(String value) {
            addCriterion("anlage <>", value, "anlage");
            return (Criteria) this;
        }

        public Criteria andAnlageGreaterThan(String value) {
            addCriterion("anlage >", value, "anlage");
            return (Criteria) this;
        }

        public Criteria andAnlageGreaterThanOrEqualTo(String value) {
            addCriterion("anlage >=", value, "anlage");
            return (Criteria) this;
        }

        public Criteria andAnlageLessThan(String value) {
            addCriterion("anlage <", value, "anlage");
            return (Criteria) this;
        }

        public Criteria andAnlageLessThanOrEqualTo(String value) {
            addCriterion("anlage <=", value, "anlage");
            return (Criteria) this;
        }

        public Criteria andAnlageLike(String value) {
            addCriterion("anlage like", value, "anlage");
            return (Criteria) this;
        }

        public Criteria andAnlageNotLike(String value) {
            addCriterion("anlage not like", value, "anlage");
            return (Criteria) this;
        }

        public Criteria andAnlageIn(List<String> values) {
            addCriterion("anlage in", values, "anlage");
            return (Criteria) this;
        }

        public Criteria andAnlageNotIn(List<String> values) {
            addCriterion("anlage not in", values, "anlage");
            return (Criteria) this;
        }

        public Criteria andAnlageBetween(String value1, String value2) {
            addCriterion("anlage between", value1, value2, "anlage");
            return (Criteria) this;
        }

        public Criteria andAnlageNotBetween(String value1, String value2) {
            addCriterion("anlage not between", value1, value2, "anlage");
            return (Criteria) this;
        }

        public Criteria andBauformIsNull() {
            addCriterion("bauform is null");
            return (Criteria) this;
        }

        public Criteria andBauformIsNotNull() {
            addCriterion("bauform is not null");
            return (Criteria) this;
        }

        public Criteria andBauformEqualTo(String value) {
            addCriterion("bauform =", value, "bauform");
            return (Criteria) this;
        }

        public Criteria andBauformNotEqualTo(String value) {
            addCriterion("bauform <>", value, "bauform");
            return (Criteria) this;
        }

        public Criteria andBauformGreaterThan(String value) {
            addCriterion("bauform >", value, "bauform");
            return (Criteria) this;
        }

        public Criteria andBauformGreaterThanOrEqualTo(String value) {
            addCriterion("bauform >=", value, "bauform");
            return (Criteria) this;
        }

        public Criteria andBauformLessThan(String value) {
            addCriterion("bauform <", value, "bauform");
            return (Criteria) this;
        }

        public Criteria andBauformLessThanOrEqualTo(String value) {
            addCriterion("bauform <=", value, "bauform");
            return (Criteria) this;
        }

        public Criteria andBauformLike(String value) {
            addCriterion("bauform like", value, "bauform");
            return (Criteria) this;
        }

        public Criteria andBauformNotLike(String value) {
            addCriterion("bauform not like", value, "bauform");
            return (Criteria) this;
        }

        public Criteria andBauformIn(List<String> values) {
            addCriterion("bauform in", values, "bauform");
            return (Criteria) this;
        }

        public Criteria andBauformNotIn(List<String> values) {
            addCriterion("bauform not in", values, "bauform");
            return (Criteria) this;
        }

        public Criteria andBauformBetween(String value1, String value2) {
            addCriterion("bauform between", value1, value2, "bauform");
            return (Criteria) this;
        }

        public Criteria andBauformNotBetween(String value1, String value2) {
            addCriterion("bauform not between", value1, value2, "bauform");
            return (Criteria) this;
        }

        public Criteria andBauklasIsNull() {
            addCriterion("bauklas is null");
            return (Criteria) this;
        }

        public Criteria andBauklasIsNotNull() {
            addCriterion("bauklas is not null");
            return (Criteria) this;
        }

        public Criteria andBauklasEqualTo(String value) {
            addCriterion("bauklas =", value, "bauklas");
            return (Criteria) this;
        }

        public Criteria andBauklasNotEqualTo(String value) {
            addCriterion("bauklas <>", value, "bauklas");
            return (Criteria) this;
        }

        public Criteria andBauklasGreaterThan(String value) {
            addCriterion("bauklas >", value, "bauklas");
            return (Criteria) this;
        }

        public Criteria andBauklasGreaterThanOrEqualTo(String value) {
            addCriterion("bauklas >=", value, "bauklas");
            return (Criteria) this;
        }

        public Criteria andBauklasLessThan(String value) {
            addCriterion("bauklas <", value, "bauklas");
            return (Criteria) this;
        }

        public Criteria andBauklasLessThanOrEqualTo(String value) {
            addCriterion("bauklas <=", value, "bauklas");
            return (Criteria) this;
        }

        public Criteria andBauklasLike(String value) {
            addCriterion("bauklas like", value, "bauklas");
            return (Criteria) this;
        }

        public Criteria andBauklasNotLike(String value) {
            addCriterion("bauklas not like", value, "bauklas");
            return (Criteria) this;
        }

        public Criteria andBauklasIn(List<String> values) {
            addCriterion("bauklas in", values, "bauklas");
            return (Criteria) this;
        }

        public Criteria andBauklasNotIn(List<String> values) {
            addCriterion("bauklas not in", values, "bauklas");
            return (Criteria) this;
        }

        public Criteria andBauklasBetween(String value1, String value2) {
            addCriterion("bauklas between", value1, value2, "bauklas");
            return (Criteria) this;
        }

        public Criteria andBauklasNotBetween(String value1, String value2) {
            addCriterion("bauklas not between", value1, value2, "bauklas");
            return (Criteria) this;
        }

        public Criteria andBrancheIsNull() {
            addCriterion("branche is null");
            return (Criteria) this;
        }

        public Criteria andBrancheIsNotNull() {
            addCriterion("branche is not null");
            return (Criteria) this;
        }

        public Criteria andBrancheEqualTo(String value) {
            addCriterion("branche =", value, "branche");
            return (Criteria) this;
        }

        public Criteria andBrancheNotEqualTo(String value) {
            addCriterion("branche <>", value, "branche");
            return (Criteria) this;
        }

        public Criteria andBrancheGreaterThan(String value) {
            addCriterion("branche >", value, "branche");
            return (Criteria) this;
        }

        public Criteria andBrancheGreaterThanOrEqualTo(String value) {
            addCriterion("branche >=", value, "branche");
            return (Criteria) this;
        }

        public Criteria andBrancheLessThan(String value) {
            addCriterion("branche <", value, "branche");
            return (Criteria) this;
        }

        public Criteria andBrancheLessThanOrEqualTo(String value) {
            addCriterion("branche <=", value, "branche");
            return (Criteria) this;
        }

        public Criteria andBrancheLike(String value) {
            addCriterion("branche like", value, "branche");
            return (Criteria) this;
        }

        public Criteria andBrancheNotLike(String value) {
            addCriterion("branche not like", value, "branche");
            return (Criteria) this;
        }

        public Criteria andBrancheIn(List<String> values) {
            addCriterion("branche in", values, "branche");
            return (Criteria) this;
        }

        public Criteria andBrancheNotIn(List<String> values) {
            addCriterion("branche not in", values, "branche");
            return (Criteria) this;
        }

        public Criteria andBrancheBetween(String value1, String value2) {
            addCriterion("branche between", value1, value2, "branche");
            return (Criteria) this;
        }

        public Criteria andBrancheNotBetween(String value1, String value2) {
            addCriterion("branche not between", value1, value2, "branche");
            return (Criteria) this;
        }

        public Criteria andConsnumber1IsNull() {
            addCriterion("consnumber1 is null");
            return (Criteria) this;
        }

        public Criteria andConsnumber1IsNotNull() {
            addCriterion("consnumber1 is not null");
            return (Criteria) this;
        }

        public Criteria andConsnumber1EqualTo(String value) {
            addCriterion("consnumber1 =", value, "consnumber1");
            return (Criteria) this;
        }

        public Criteria andConsnumber1NotEqualTo(String value) {
            addCriterion("consnumber1 <>", value, "consnumber1");
            return (Criteria) this;
        }

        public Criteria andConsnumber1GreaterThan(String value) {
            addCriterion("consnumber1 >", value, "consnumber1");
            return (Criteria) this;
        }

        public Criteria andConsnumber1GreaterThanOrEqualTo(String value) {
            addCriterion("consnumber1 >=", value, "consnumber1");
            return (Criteria) this;
        }

        public Criteria andConsnumber1LessThan(String value) {
            addCriterion("consnumber1 <", value, "consnumber1");
            return (Criteria) this;
        }

        public Criteria andConsnumber1LessThanOrEqualTo(String value) {
            addCriterion("consnumber1 <=", value, "consnumber1");
            return (Criteria) this;
        }

        public Criteria andConsnumber1Like(String value) {
            addCriterion("consnumber1 like", value, "consnumber1");
            return (Criteria) this;
        }

        public Criteria andConsnumber1NotLike(String value) {
            addCriterion("consnumber1 not like", value, "consnumber1");
            return (Criteria) this;
        }

        public Criteria andConsnumber1In(List<String> values) {
            addCriterion("consnumber1 in", values, "consnumber1");
            return (Criteria) this;
        }

        public Criteria andConsnumber1NotIn(List<String> values) {
            addCriterion("consnumber1 not in", values, "consnumber1");
            return (Criteria) this;
        }

        public Criteria andConsnumber1Between(String value1, String value2) {
            addCriterion("consnumber1 between", value1, value2, "consnumber1");
            return (Criteria) this;
        }

        public Criteria andConsnumber1NotBetween(String value1, String value2) {
            addCriterion("consnumber1 not between", value1, value2, "consnumber1");
            return (Criteria) this;
        }

        public Criteria andConsnumber2IsNull() {
            addCriterion("consnumber2 is null");
            return (Criteria) this;
        }

        public Criteria andConsnumber2IsNotNull() {
            addCriterion("consnumber2 is not null");
            return (Criteria) this;
        }

        public Criteria andConsnumber2EqualTo(String value) {
            addCriterion("consnumber2 =", value, "consnumber2");
            return (Criteria) this;
        }

        public Criteria andConsnumber2NotEqualTo(String value) {
            addCriterion("consnumber2 <>", value, "consnumber2");
            return (Criteria) this;
        }

        public Criteria andConsnumber2GreaterThan(String value) {
            addCriterion("consnumber2 >", value, "consnumber2");
            return (Criteria) this;
        }

        public Criteria andConsnumber2GreaterThanOrEqualTo(String value) {
            addCriterion("consnumber2 >=", value, "consnumber2");
            return (Criteria) this;
        }

        public Criteria andConsnumber2LessThan(String value) {
            addCriterion("consnumber2 <", value, "consnumber2");
            return (Criteria) this;
        }

        public Criteria andConsnumber2LessThanOrEqualTo(String value) {
            addCriterion("consnumber2 <=", value, "consnumber2");
            return (Criteria) this;
        }

        public Criteria andConsnumber2Like(String value) {
            addCriterion("consnumber2 like", value, "consnumber2");
            return (Criteria) this;
        }

        public Criteria andConsnumber2NotLike(String value) {
            addCriterion("consnumber2 not like", value, "consnumber2");
            return (Criteria) this;
        }

        public Criteria andConsnumber2In(List<String> values) {
            addCriterion("consnumber2 in", values, "consnumber2");
            return (Criteria) this;
        }

        public Criteria andConsnumber2NotIn(List<String> values) {
            addCriterion("consnumber2 not in", values, "consnumber2");
            return (Criteria) this;
        }

        public Criteria andConsnumber2Between(String value1, String value2) {
            addCriterion("consnumber2 between", value1, value2, "consnumber2");
            return (Criteria) this;
        }

        public Criteria andConsnumber2NotBetween(String value1, String value2) {
            addCriterion("consnumber2 not between", value1, value2, "consnumber2");
            return (Criteria) this;
        }

        public Criteria andConsnumber3IsNull() {
            addCriterion("consnumber3 is null");
            return (Criteria) this;
        }

        public Criteria andConsnumber3IsNotNull() {
            addCriterion("consnumber3 is not null");
            return (Criteria) this;
        }

        public Criteria andConsnumber3EqualTo(String value) {
            addCriterion("consnumber3 =", value, "consnumber3");
            return (Criteria) this;
        }

        public Criteria andConsnumber3NotEqualTo(String value) {
            addCriterion("consnumber3 <>", value, "consnumber3");
            return (Criteria) this;
        }

        public Criteria andConsnumber3GreaterThan(String value) {
            addCriterion("consnumber3 >", value, "consnumber3");
            return (Criteria) this;
        }

        public Criteria andConsnumber3GreaterThanOrEqualTo(String value) {
            addCriterion("consnumber3 >=", value, "consnumber3");
            return (Criteria) this;
        }

        public Criteria andConsnumber3LessThan(String value) {
            addCriterion("consnumber3 <", value, "consnumber3");
            return (Criteria) this;
        }

        public Criteria andConsnumber3LessThanOrEqualTo(String value) {
            addCriterion("consnumber3 <=", value, "consnumber3");
            return (Criteria) this;
        }

        public Criteria andConsnumber3Like(String value) {
            addCriterion("consnumber3 like", value, "consnumber3");
            return (Criteria) this;
        }

        public Criteria andConsnumber3NotLike(String value) {
            addCriterion("consnumber3 not like", value, "consnumber3");
            return (Criteria) this;
        }

        public Criteria andConsnumber3In(List<String> values) {
            addCriterion("consnumber3 in", values, "consnumber3");
            return (Criteria) this;
        }

        public Criteria andConsnumber3NotIn(List<String> values) {
            addCriterion("consnumber3 not in", values, "consnumber3");
            return (Criteria) this;
        }

        public Criteria andConsnumber3Between(String value1, String value2) {
            addCriterion("consnumber3 between", value1, value2, "consnumber3");
            return (Criteria) this;
        }

        public Criteria andConsnumber3NotBetween(String value1, String value2) {
            addCriterion("consnumber3 not between", value1, value2, "consnumber3");
            return (Criteria) this;
        }

        public Criteria andDevlocIsNull() {
            addCriterion("devloc is null");
            return (Criteria) this;
        }

        public Criteria andDevlocIsNotNull() {
            addCriterion("devloc is not null");
            return (Criteria) this;
        }

        public Criteria andDevlocEqualTo(String value) {
            addCriterion("devloc =", value, "devloc");
            return (Criteria) this;
        }

        public Criteria andDevlocNotEqualTo(String value) {
            addCriterion("devloc <>", value, "devloc");
            return (Criteria) this;
        }

        public Criteria andDevlocGreaterThan(String value) {
            addCriterion("devloc >", value, "devloc");
            return (Criteria) this;
        }

        public Criteria andDevlocGreaterThanOrEqualTo(String value) {
            addCriterion("devloc >=", value, "devloc");
            return (Criteria) this;
        }

        public Criteria andDevlocLessThan(String value) {
            addCriterion("devloc <", value, "devloc");
            return (Criteria) this;
        }

        public Criteria andDevlocLessThanOrEqualTo(String value) {
            addCriterion("devloc <=", value, "devloc");
            return (Criteria) this;
        }

        public Criteria andDevlocLike(String value) {
            addCriterion("devloc like", value, "devloc");
            return (Criteria) this;
        }

        public Criteria andDevlocNotLike(String value) {
            addCriterion("devloc not like", value, "devloc");
            return (Criteria) this;
        }

        public Criteria andDevlocIn(List<String> values) {
            addCriterion("devloc in", values, "devloc");
            return (Criteria) this;
        }

        public Criteria andDevlocNotIn(List<String> values) {
            addCriterion("devloc not in", values, "devloc");
            return (Criteria) this;
        }

        public Criteria andDevlocBetween(String value1, String value2) {
            addCriterion("devloc between", value1, value2, "devloc");
            return (Criteria) this;
        }

        public Criteria andDevlocNotBetween(String value1, String value2) {
            addCriterion("devloc not between", value1, value2, "devloc");
            return (Criteria) this;
        }

        public Criteria andNameOrg1IsNull() {
            addCriterion("name_org1 is null");
            return (Criteria) this;
        }

        public Criteria andNameOrg1IsNotNull() {
            addCriterion("name_org1 is not null");
            return (Criteria) this;
        }

        public Criteria andNameOrg1EqualTo(String value) {
            addCriterion("name_org1 =", value, "nameOrg1");
            return (Criteria) this;
        }

        public Criteria andNameOrg1NotEqualTo(String value) {
            addCriterion("name_org1 <>", value, "nameOrg1");
            return (Criteria) this;
        }

        public Criteria andNameOrg1GreaterThan(String value) {
            addCriterion("name_org1 >", value, "nameOrg1");
            return (Criteria) this;
        }

        public Criteria andNameOrg1GreaterThanOrEqualTo(String value) {
            addCriterion("name_org1 >=", value, "nameOrg1");
            return (Criteria) this;
        }

        public Criteria andNameOrg1LessThan(String value) {
            addCriterion("name_org1 <", value, "nameOrg1");
            return (Criteria) this;
        }

        public Criteria andNameOrg1LessThanOrEqualTo(String value) {
            addCriterion("name_org1 <=", value, "nameOrg1");
            return (Criteria) this;
        }

        public Criteria andNameOrg1Like(String value) {
            addCriterion("name_org1 like", value, "nameOrg1");
            return (Criteria) this;
        }

        public Criteria andNameOrg1NotLike(String value) {
            addCriterion("name_org1 not like", value, "nameOrg1");
            return (Criteria) this;
        }

        public Criteria andNameOrg1In(List<String> values) {
            addCriterion("name_org1 in", values, "nameOrg1");
            return (Criteria) this;
        }

        public Criteria andNameOrg1NotIn(List<String> values) {
            addCriterion("name_org1 not in", values, "nameOrg1");
            return (Criteria) this;
        }

        public Criteria andNameOrg1Between(String value1, String value2) {
            addCriterion("name_org1 between", value1, value2, "nameOrg1");
            return (Criteria) this;
        }

        public Criteria andNameOrg1NotBetween(String value1, String value2) {
            addCriterion("name_org1 not between", value1, value2, "nameOrg1");
            return (Criteria) this;
        }

        public Criteria andOpeBpIsNull() {
            addCriterion("ope_bp is null");
            return (Criteria) this;
        }

        public Criteria andOpeBpIsNotNull() {
            addCriterion("ope_bp is not null");
            return (Criteria) this;
        }

        public Criteria andOpeBpEqualTo(String value) {
            addCriterion("ope_bp =", value, "opeBp");
            return (Criteria) this;
        }

        public Criteria andOpeBpNotEqualTo(String value) {
            addCriterion("ope_bp <>", value, "opeBp");
            return (Criteria) this;
        }

        public Criteria andOpeBpGreaterThan(String value) {
            addCriterion("ope_bp >", value, "opeBp");
            return (Criteria) this;
        }

        public Criteria andOpeBpGreaterThanOrEqualTo(String value) {
            addCriterion("ope_bp >=", value, "opeBp");
            return (Criteria) this;
        }

        public Criteria andOpeBpLessThan(String value) {
            addCriterion("ope_bp <", value, "opeBp");
            return (Criteria) this;
        }

        public Criteria andOpeBpLessThanOrEqualTo(String value) {
            addCriterion("ope_bp <=", value, "opeBp");
            return (Criteria) this;
        }

        public Criteria andOpeBpLike(String value) {
            addCriterion("ope_bp like", value, "opeBp");
            return (Criteria) this;
        }

        public Criteria andOpeBpNotLike(String value) {
            addCriterion("ope_bp not like", value, "opeBp");
            return (Criteria) this;
        }

        public Criteria andOpeBpIn(List<String> values) {
            addCriterion("ope_bp in", values, "opeBp");
            return (Criteria) this;
        }

        public Criteria andOpeBpNotIn(List<String> values) {
            addCriterion("ope_bp not in", values, "opeBp");
            return (Criteria) this;
        }

        public Criteria andOpeBpBetween(String value1, String value2) {
            addCriterion("ope_bp between", value1, value2, "opeBp");
            return (Criteria) this;
        }

        public Criteria andOpeBpNotBetween(String value1, String value2) {
            addCriterion("ope_bp not between", value1, value2, "opeBp");
            return (Criteria) this;
        }

        public Criteria andPartnerIsNull() {
            addCriterion("partner is null");
            return (Criteria) this;
        }

        public Criteria andPartnerIsNotNull() {
            addCriterion("partner is not null");
            return (Criteria) this;
        }

        public Criteria andPartnerEqualTo(String value) {
            addCriterion("partner =", value, "partner");
            return (Criteria) this;
        }

        public Criteria andPartnerNotEqualTo(String value) {
            addCriterion("partner <>", value, "partner");
            return (Criteria) this;
        }

        public Criteria andPartnerGreaterThan(String value) {
            addCriterion("partner >", value, "partner");
            return (Criteria) this;
        }

        public Criteria andPartnerGreaterThanOrEqualTo(String value) {
            addCriterion("partner >=", value, "partner");
            return (Criteria) this;
        }

        public Criteria andPartnerLessThan(String value) {
            addCriterion("partner <", value, "partner");
            return (Criteria) this;
        }

        public Criteria andPartnerLessThanOrEqualTo(String value) {
            addCriterion("partner <=", value, "partner");
            return (Criteria) this;
        }

        public Criteria andPartnerLike(String value) {
            addCriterion("partner like", value, "partner");
            return (Criteria) this;
        }

        public Criteria andPartnerNotLike(String value) {
            addCriterion("partner not like", value, "partner");
            return (Criteria) this;
        }

        public Criteria andPartnerIn(List<String> values) {
            addCriterion("partner in", values, "partner");
            return (Criteria) this;
        }

        public Criteria andPartnerNotIn(List<String> values) {
            addCriterion("partner not in", values, "partner");
            return (Criteria) this;
        }

        public Criteria andPartnerBetween(String value1, String value2) {
            addCriterion("partner between", value1, value2, "partner");
            return (Criteria) this;
        }

        public Criteria andPartnerNotBetween(String value1, String value2) {
            addCriterion("partner not between", value1, value2, "partner");
            return (Criteria) this;
        }

        public Criteria andPlanIdIsNull() {
            addCriterion("plan_id is null");
            return (Criteria) this;
        }

        public Criteria andPlanIdIsNotNull() {
            addCriterion("plan_id is not null");
            return (Criteria) this;
        }

        public Criteria andPlanIdEqualTo(Integer value) {
            addCriterion("plan_id =", value, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdNotEqualTo(Integer value) {
            addCriterion("plan_id <>", value, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdGreaterThan(Integer value) {
            addCriterion("plan_id >", value, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("plan_id >=", value, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdLessThan(Integer value) {
            addCriterion("plan_id <", value, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdLessThanOrEqualTo(Integer value) {
            addCriterion("plan_id <=", value, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdIn(List<Integer> values) {
            addCriterion("plan_id in", values, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdNotIn(List<Integer> values) {
            addCriterion("plan_id not in", values, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdBetween(Integer value1, Integer value2) {
            addCriterion("plan_id between", value1, value2, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdNotBetween(Integer value1, Integer value2) {
            addCriterion("plan_id not between", value1, value2, "planId");
            return (Criteria) this;
        }

        public Criteria andR3Usrer1IsNull() {
            addCriterion("r3_usrer1 is null");
            return (Criteria) this;
        }

        public Criteria andR3Usrer1IsNotNull() {
            addCriterion("r3_usrer1 is not null");
            return (Criteria) this;
        }

        public Criteria andR3Usrer1EqualTo(String value) {
            addCriterion("r3_usrer1 =", value, "r3Usrer1");
            return (Criteria) this;
        }

        public Criteria andR3Usrer1NotEqualTo(String value) {
            addCriterion("r3_usrer1 <>", value, "r3Usrer1");
            return (Criteria) this;
        }

        public Criteria andR3Usrer1GreaterThan(String value) {
            addCriterion("r3_usrer1 >", value, "r3Usrer1");
            return (Criteria) this;
        }

        public Criteria andR3Usrer1GreaterThanOrEqualTo(String value) {
            addCriterion("r3_usrer1 >=", value, "r3Usrer1");
            return (Criteria) this;
        }

        public Criteria andR3Usrer1LessThan(String value) {
            addCriterion("r3_usrer1 <", value, "r3Usrer1");
            return (Criteria) this;
        }

        public Criteria andR3Usrer1LessThanOrEqualTo(String value) {
            addCriterion("r3_usrer1 <=", value, "r3Usrer1");
            return (Criteria) this;
        }

        public Criteria andR3Usrer1Like(String value) {
            addCriterion("r3_usrer1 like", value, "r3Usrer1");
            return (Criteria) this;
        }

        public Criteria andR3Usrer1NotLike(String value) {
            addCriterion("r3_usrer1 not like", value, "r3Usrer1");
            return (Criteria) this;
        }

        public Criteria andR3Usrer1In(List<String> values) {
            addCriterion("r3_usrer1 in", values, "r3Usrer1");
            return (Criteria) this;
        }

        public Criteria andR3Usrer1NotIn(List<String> values) {
            addCriterion("r3_usrer1 not in", values, "r3Usrer1");
            return (Criteria) this;
        }

        public Criteria andR3Usrer1Between(String value1, String value2) {
            addCriterion("r3_usrer1 between", value1, value2, "r3Usrer1");
            return (Criteria) this;
        }

        public Criteria andR3Usrer1NotBetween(String value1, String value2) {
            addCriterion("r3_usrer1 not between", value1, value2, "r3Usrer1");
            return (Criteria) this;
        }

        public Criteria andR3Usrer2IsNull() {
            addCriterion("r3_usrer2 is null");
            return (Criteria) this;
        }

        public Criteria andR3Usrer2IsNotNull() {
            addCriterion("r3_usrer2 is not null");
            return (Criteria) this;
        }

        public Criteria andR3Usrer2EqualTo(String value) {
            addCriterion("r3_usrer2 =", value, "r3Usrer2");
            return (Criteria) this;
        }

        public Criteria andR3Usrer2NotEqualTo(String value) {
            addCriterion("r3_usrer2 <>", value, "r3Usrer2");
            return (Criteria) this;
        }

        public Criteria andR3Usrer2GreaterThan(String value) {
            addCriterion("r3_usrer2 >", value, "r3Usrer2");
            return (Criteria) this;
        }

        public Criteria andR3Usrer2GreaterThanOrEqualTo(String value) {
            addCriterion("r3_usrer2 >=", value, "r3Usrer2");
            return (Criteria) this;
        }

        public Criteria andR3Usrer2LessThan(String value) {
            addCriterion("r3_usrer2 <", value, "r3Usrer2");
            return (Criteria) this;
        }

        public Criteria andR3Usrer2LessThanOrEqualTo(String value) {
            addCriterion("r3_usrer2 <=", value, "r3Usrer2");
            return (Criteria) this;
        }

        public Criteria andR3Usrer2Like(String value) {
            addCriterion("r3_usrer2 like", value, "r3Usrer2");
            return (Criteria) this;
        }

        public Criteria andR3Usrer2NotLike(String value) {
            addCriterion("r3_usrer2 not like", value, "r3Usrer2");
            return (Criteria) this;
        }

        public Criteria andR3Usrer2In(List<String> values) {
            addCriterion("r3_usrer2 in", values, "r3Usrer2");
            return (Criteria) this;
        }

        public Criteria andR3Usrer2NotIn(List<String> values) {
            addCriterion("r3_usrer2 not in", values, "r3Usrer2");
            return (Criteria) this;
        }

        public Criteria andR3Usrer2Between(String value1, String value2) {
            addCriterion("r3_usrer2 between", value1, value2, "r3Usrer2");
            return (Criteria) this;
        }

        public Criteria andR3Usrer2NotBetween(String value1, String value2) {
            addCriterion("r3_usrer2 not between", value1, value2, "r3Usrer2");
            return (Criteria) this;
        }

        public Criteria andR3Usrer3IsNull() {
            addCriterion("r3_usrer3 is null");
            return (Criteria) this;
        }

        public Criteria andR3Usrer3IsNotNull() {
            addCriterion("r3_usrer3 is not null");
            return (Criteria) this;
        }

        public Criteria andR3Usrer3EqualTo(String value) {
            addCriterion("r3_usrer3 =", value, "r3Usrer3");
            return (Criteria) this;
        }

        public Criteria andR3Usrer3NotEqualTo(String value) {
            addCriterion("r3_usrer3 <>", value, "r3Usrer3");
            return (Criteria) this;
        }

        public Criteria andR3Usrer3GreaterThan(String value) {
            addCriterion("r3_usrer3 >", value, "r3Usrer3");
            return (Criteria) this;
        }

        public Criteria andR3Usrer3GreaterThanOrEqualTo(String value) {
            addCriterion("r3_usrer3 >=", value, "r3Usrer3");
            return (Criteria) this;
        }

        public Criteria andR3Usrer3LessThan(String value) {
            addCriterion("r3_usrer3 <", value, "r3Usrer3");
            return (Criteria) this;
        }

        public Criteria andR3Usrer3LessThanOrEqualTo(String value) {
            addCriterion("r3_usrer3 <=", value, "r3Usrer3");
            return (Criteria) this;
        }

        public Criteria andR3Usrer3Like(String value) {
            addCriterion("r3_usrer3 like", value, "r3Usrer3");
            return (Criteria) this;
        }

        public Criteria andR3Usrer3NotLike(String value) {
            addCriterion("r3_usrer3 not like", value, "r3Usrer3");
            return (Criteria) this;
        }

        public Criteria andR3Usrer3In(List<String> values) {
            addCriterion("r3_usrer3 in", values, "r3Usrer3");
            return (Criteria) this;
        }

        public Criteria andR3Usrer3NotIn(List<String> values) {
            addCriterion("r3_usrer3 not in", values, "r3Usrer3");
            return (Criteria) this;
        }

        public Criteria andR3Usrer3Between(String value1, String value2) {
            addCriterion("r3_usrer3 between", value1, value2, "r3Usrer3");
            return (Criteria) this;
        }

        public Criteria andR3Usrer3NotBetween(String value1, String value2) {
            addCriterion("r3_usrer3 not between", value1, value2, "r3Usrer3");
            return (Criteria) this;
        }

        public Criteria andR3Usrer4IsNull() {
            addCriterion("r3_usrer4 is null");
            return (Criteria) this;
        }

        public Criteria andR3Usrer4IsNotNull() {
            addCriterion("r3_usrer4 is not null");
            return (Criteria) this;
        }

        public Criteria andR3Usrer4EqualTo(String value) {
            addCriterion("r3_usrer4 =", value, "r3Usrer4");
            return (Criteria) this;
        }

        public Criteria andR3Usrer4NotEqualTo(String value) {
            addCriterion("r3_usrer4 <>", value, "r3Usrer4");
            return (Criteria) this;
        }

        public Criteria andR3Usrer4GreaterThan(String value) {
            addCriterion("r3_usrer4 >", value, "r3Usrer4");
            return (Criteria) this;
        }

        public Criteria andR3Usrer4GreaterThanOrEqualTo(String value) {
            addCriterion("r3_usrer4 >=", value, "r3Usrer4");
            return (Criteria) this;
        }

        public Criteria andR3Usrer4LessThan(String value) {
            addCriterion("r3_usrer4 <", value, "r3Usrer4");
            return (Criteria) this;
        }

        public Criteria andR3Usrer4LessThanOrEqualTo(String value) {
            addCriterion("r3_usrer4 <=", value, "r3Usrer4");
            return (Criteria) this;
        }

        public Criteria andR3Usrer4Like(String value) {
            addCriterion("r3_usrer4 like", value, "r3Usrer4");
            return (Criteria) this;
        }

        public Criteria andR3Usrer4NotLike(String value) {
            addCriterion("r3_usrer4 not like", value, "r3Usrer4");
            return (Criteria) this;
        }

        public Criteria andR3Usrer4In(List<String> values) {
            addCriterion("r3_usrer4 in", values, "r3Usrer4");
            return (Criteria) this;
        }

        public Criteria andR3Usrer4NotIn(List<String> values) {
            addCriterion("r3_usrer4 not in", values, "r3Usrer4");
            return (Criteria) this;
        }

        public Criteria andR3Usrer4Between(String value1, String value2) {
            addCriterion("r3_usrer4 between", value1, value2, "r3Usrer4");
            return (Criteria) this;
        }

        public Criteria andR3Usrer4NotBetween(String value1, String value2) {
            addCriterion("r3_usrer4 not between", value1, value2, "r3Usrer4");
            return (Criteria) this;
        }

        public Criteria andR3Usrer5IsNull() {
            addCriterion("r3_usrer5 is null");
            return (Criteria) this;
        }

        public Criteria andR3Usrer5IsNotNull() {
            addCriterion("r3_usrer5 is not null");
            return (Criteria) this;
        }

        public Criteria andR3Usrer5EqualTo(String value) {
            addCriterion("r3_usrer5 =", value, "r3Usrer5");
            return (Criteria) this;
        }

        public Criteria andR3Usrer5NotEqualTo(String value) {
            addCriterion("r3_usrer5 <>", value, "r3Usrer5");
            return (Criteria) this;
        }

        public Criteria andR3Usrer5GreaterThan(String value) {
            addCriterion("r3_usrer5 >", value, "r3Usrer5");
            return (Criteria) this;
        }

        public Criteria andR3Usrer5GreaterThanOrEqualTo(String value) {
            addCriterion("r3_usrer5 >=", value, "r3Usrer5");
            return (Criteria) this;
        }

        public Criteria andR3Usrer5LessThan(String value) {
            addCriterion("r3_usrer5 <", value, "r3Usrer5");
            return (Criteria) this;
        }

        public Criteria andR3Usrer5LessThanOrEqualTo(String value) {
            addCriterion("r3_usrer5 <=", value, "r3Usrer5");
            return (Criteria) this;
        }

        public Criteria andR3Usrer5Like(String value) {
            addCriterion("r3_usrer5 like", value, "r3Usrer5");
            return (Criteria) this;
        }

        public Criteria andR3Usrer5NotLike(String value) {
            addCriterion("r3_usrer5 not like", value, "r3Usrer5");
            return (Criteria) this;
        }

        public Criteria andR3Usrer5In(List<String> values) {
            addCriterion("r3_usrer5 in", values, "r3Usrer5");
            return (Criteria) this;
        }

        public Criteria andR3Usrer5NotIn(List<String> values) {
            addCriterion("r3_usrer5 not in", values, "r3Usrer5");
            return (Criteria) this;
        }

        public Criteria andR3Usrer5Between(String value1, String value2) {
            addCriterion("r3_usrer5 between", value1, value2, "r3Usrer5");
            return (Criteria) this;
        }

        public Criteria andR3Usrer5NotBetween(String value1, String value2) {
            addCriterion("r3_usrer5 not between", value1, value2, "r3Usrer5");
            return (Criteria) this;
        }

        public Criteria andRoomnumberIsNull() {
            addCriterion("roomnumber is null");
            return (Criteria) this;
        }

        public Criteria andRoomnumberIsNotNull() {
            addCriterion("roomnumber is not null");
            return (Criteria) this;
        }

        public Criteria andRoomnumberEqualTo(String value) {
            addCriterion("roomnumber =", value, "roomnumber");
            return (Criteria) this;
        }

        public Criteria andRoomnumberNotEqualTo(String value) {
            addCriterion("roomnumber <>", value, "roomnumber");
            return (Criteria) this;
        }

        public Criteria andRoomnumberGreaterThan(String value) {
            addCriterion("roomnumber >", value, "roomnumber");
            return (Criteria) this;
        }

        public Criteria andRoomnumberGreaterThanOrEqualTo(String value) {
            addCriterion("roomnumber >=", value, "roomnumber");
            return (Criteria) this;
        }

        public Criteria andRoomnumberLessThan(String value) {
            addCriterion("roomnumber <", value, "roomnumber");
            return (Criteria) this;
        }

        public Criteria andRoomnumberLessThanOrEqualTo(String value) {
            addCriterion("roomnumber <=", value, "roomnumber");
            return (Criteria) this;
        }

        public Criteria andRoomnumberLike(String value) {
            addCriterion("roomnumber like", value, "roomnumber");
            return (Criteria) this;
        }

        public Criteria andRoomnumberNotLike(String value) {
            addCriterion("roomnumber not like", value, "roomnumber");
            return (Criteria) this;
        }

        public Criteria andRoomnumberIn(List<String> values) {
            addCriterion("roomnumber in", values, "roomnumber");
            return (Criteria) this;
        }

        public Criteria andRoomnumberNotIn(List<String> values) {
            addCriterion("roomnumber not in", values, "roomnumber");
            return (Criteria) this;
        }

        public Criteria andRoomnumberBetween(String value1, String value2) {
            addCriterion("roomnumber between", value1, value2, "roomnumber");
            return (Criteria) this;
        }

        public Criteria andRoomnumberNotBetween(String value1, String value2) {
            addCriterion("roomnumber not between", value1, value2, "roomnumber");
            return (Criteria) this;
        }

        public Criteria andSergeIsNull() {
            addCriterion("serge is null");
            return (Criteria) this;
        }

        public Criteria andSergeIsNotNull() {
            addCriterion("serge is not null");
            return (Criteria) this;
        }

        public Criteria andSergeEqualTo(String value) {
            addCriterion("serge =", value, "serge");
            return (Criteria) this;
        }

        public Criteria andSergeNotEqualTo(String value) {
            addCriterion("serge <>", value, "serge");
            return (Criteria) this;
        }

        public Criteria andSergeGreaterThan(String value) {
            addCriterion("serge >", value, "serge");
            return (Criteria) this;
        }

        public Criteria andSergeGreaterThanOrEqualTo(String value) {
            addCriterion("serge >=", value, "serge");
            return (Criteria) this;
        }

        public Criteria andSergeLessThan(String value) {
            addCriterion("serge <", value, "serge");
            return (Criteria) this;
        }

        public Criteria andSergeLessThanOrEqualTo(String value) {
            addCriterion("serge <=", value, "serge");
            return (Criteria) this;
        }

        public Criteria andSergeLike(String value) {
            addCriterion("serge like", value, "serge");
            return (Criteria) this;
        }

        public Criteria andSergeNotLike(String value) {
            addCriterion("serge not like", value, "serge");
            return (Criteria) this;
        }

        public Criteria andSergeIn(List<String> values) {
            addCriterion("serge in", values, "serge");
            return (Criteria) this;
        }

        public Criteria andSergeNotIn(List<String> values) {
            addCriterion("serge not in", values, "serge");
            return (Criteria) this;
        }

        public Criteria andSergeBetween(String value1, String value2) {
            addCriterion("serge between", value1, value2, "serge");
            return (Criteria) this;
        }

        public Criteria andSergeNotBetween(String value1, String value2) {
            addCriterion("serge not between", value1, value2, "serge");
            return (Criteria) this;
        }

        public Criteria andStrSuppl1IsNull() {
            addCriterion("str_suppl1 is null");
            return (Criteria) this;
        }

        public Criteria andStrSuppl1IsNotNull() {
            addCriterion("str_suppl1 is not null");
            return (Criteria) this;
        }

        public Criteria andStrSuppl1EqualTo(String value) {
            addCriterion("str_suppl1 =", value, "strSuppl1");
            return (Criteria) this;
        }

        public Criteria andStrSuppl1NotEqualTo(String value) {
            addCriterion("str_suppl1 <>", value, "strSuppl1");
            return (Criteria) this;
        }

        public Criteria andStrSuppl1GreaterThan(String value) {
            addCriterion("str_suppl1 >", value, "strSuppl1");
            return (Criteria) this;
        }

        public Criteria andStrSuppl1GreaterThanOrEqualTo(String value) {
            addCriterion("str_suppl1 >=", value, "strSuppl1");
            return (Criteria) this;
        }

        public Criteria andStrSuppl1LessThan(String value) {
            addCriterion("str_suppl1 <", value, "strSuppl1");
            return (Criteria) this;
        }

        public Criteria andStrSuppl1LessThanOrEqualTo(String value) {
            addCriterion("str_suppl1 <=", value, "strSuppl1");
            return (Criteria) this;
        }

        public Criteria andStrSuppl1Like(String value) {
            addCriterion("str_suppl1 like", value, "strSuppl1");
            return (Criteria) this;
        }

        public Criteria andStrSuppl1NotLike(String value) {
            addCriterion("str_suppl1 not like", value, "strSuppl1");
            return (Criteria) this;
        }

        public Criteria andStrSuppl1In(List<String> values) {
            addCriterion("str_suppl1 in", values, "strSuppl1");
            return (Criteria) this;
        }

        public Criteria andStrSuppl1NotIn(List<String> values) {
            addCriterion("str_suppl1 not in", values, "strSuppl1");
            return (Criteria) this;
        }

        public Criteria andStrSuppl1Between(String value1, String value2) {
            addCriterion("str_suppl1 between", value1, value2, "strSuppl1");
            return (Criteria) this;
        }

        public Criteria andStrSuppl1NotBetween(String value1, String value2) {
            addCriterion("str_suppl1 not between", value1, value2, "strSuppl1");
            return (Criteria) this;
        }

        public Criteria andStrSuppl2IsNull() {
            addCriterion("str_suppl2 is null");
            return (Criteria) this;
        }

        public Criteria andStrSuppl2IsNotNull() {
            addCriterion("str_suppl2 is not null");
            return (Criteria) this;
        }

        public Criteria andStrSuppl2EqualTo(String value) {
            addCriterion("str_suppl2 =", value, "strSuppl2");
            return (Criteria) this;
        }

        public Criteria andStrSuppl2NotEqualTo(String value) {
            addCriterion("str_suppl2 <>", value, "strSuppl2");
            return (Criteria) this;
        }

        public Criteria andStrSuppl2GreaterThan(String value) {
            addCriterion("str_suppl2 >", value, "strSuppl2");
            return (Criteria) this;
        }

        public Criteria andStrSuppl2GreaterThanOrEqualTo(String value) {
            addCriterion("str_suppl2 >=", value, "strSuppl2");
            return (Criteria) this;
        }

        public Criteria andStrSuppl2LessThan(String value) {
            addCriterion("str_suppl2 <", value, "strSuppl2");
            return (Criteria) this;
        }

        public Criteria andStrSuppl2LessThanOrEqualTo(String value) {
            addCriterion("str_suppl2 <=", value, "strSuppl2");
            return (Criteria) this;
        }

        public Criteria andStrSuppl2Like(String value) {
            addCriterion("str_suppl2 like", value, "strSuppl2");
            return (Criteria) this;
        }

        public Criteria andStrSuppl2NotLike(String value) {
            addCriterion("str_suppl2 not like", value, "strSuppl2");
            return (Criteria) this;
        }

        public Criteria andStrSuppl2In(List<String> values) {
            addCriterion("str_suppl2 in", values, "strSuppl2");
            return (Criteria) this;
        }

        public Criteria andStrSuppl2NotIn(List<String> values) {
            addCriterion("str_suppl2 not in", values, "strSuppl2");
            return (Criteria) this;
        }

        public Criteria andStrSuppl2Between(String value1, String value2) {
            addCriterion("str_suppl2 between", value1, value2, "strSuppl2");
            return (Criteria) this;
        }

        public Criteria andStrSuppl2NotBetween(String value1, String value2) {
            addCriterion("str_suppl2 not between", value1, value2, "strSuppl2");
            return (Criteria) this;
        }

        public Criteria andStrSuppl3IsNull() {
            addCriterion("str_suppl3 is null");
            return (Criteria) this;
        }

        public Criteria andStrSuppl3IsNotNull() {
            addCriterion("str_suppl3 is not null");
            return (Criteria) this;
        }

        public Criteria andStrSuppl3EqualTo(String value) {
            addCriterion("str_suppl3 =", value, "strSuppl3");
            return (Criteria) this;
        }

        public Criteria andStrSuppl3NotEqualTo(String value) {
            addCriterion("str_suppl3 <>", value, "strSuppl3");
            return (Criteria) this;
        }

        public Criteria andStrSuppl3GreaterThan(String value) {
            addCriterion("str_suppl3 >", value, "strSuppl3");
            return (Criteria) this;
        }

        public Criteria andStrSuppl3GreaterThanOrEqualTo(String value) {
            addCriterion("str_suppl3 >=", value, "strSuppl3");
            return (Criteria) this;
        }

        public Criteria andStrSuppl3LessThan(String value) {
            addCriterion("str_suppl3 <", value, "strSuppl3");
            return (Criteria) this;
        }

        public Criteria andStrSuppl3LessThanOrEqualTo(String value) {
            addCriterion("str_suppl3 <=", value, "strSuppl3");
            return (Criteria) this;
        }

        public Criteria andStrSuppl3Like(String value) {
            addCriterion("str_suppl3 like", value, "strSuppl3");
            return (Criteria) this;
        }

        public Criteria andStrSuppl3NotLike(String value) {
            addCriterion("str_suppl3 not like", value, "strSuppl3");
            return (Criteria) this;
        }

        public Criteria andStrSuppl3In(List<String> values) {
            addCriterion("str_suppl3 in", values, "strSuppl3");
            return (Criteria) this;
        }

        public Criteria andStrSuppl3NotIn(List<String> values) {
            addCriterion("str_suppl3 not in", values, "strSuppl3");
            return (Criteria) this;
        }

        public Criteria andStrSuppl3Between(String value1, String value2) {
            addCriterion("str_suppl3 between", value1, value2, "strSuppl3");
            return (Criteria) this;
        }

        public Criteria andStrSuppl3NotBetween(String value1, String value2) {
            addCriterion("str_suppl3 not between", value1, value2, "strSuppl3");
            return (Criteria) this;
        }

        public Criteria andStreetIsNull() {
            addCriterion("street is null");
            return (Criteria) this;
        }

        public Criteria andStreetIsNotNull() {
            addCriterion("street is not null");
            return (Criteria) this;
        }

        public Criteria andStreetEqualTo(String value) {
            addCriterion("street =", value, "street");
            return (Criteria) this;
        }

        public Criteria andStreetNotEqualTo(String value) {
            addCriterion("street <>", value, "street");
            return (Criteria) this;
        }

        public Criteria andStreetGreaterThan(String value) {
            addCriterion("street >", value, "street");
            return (Criteria) this;
        }

        public Criteria andStreetGreaterThanOrEqualTo(String value) {
            addCriterion("street >=", value, "street");
            return (Criteria) this;
        }

        public Criteria andStreetLessThan(String value) {
            addCriterion("street <", value, "street");
            return (Criteria) this;
        }

        public Criteria andStreetLessThanOrEqualTo(String value) {
            addCriterion("street <=", value, "street");
            return (Criteria) this;
        }

        public Criteria andStreetLike(String value) {
            addCriterion("street like", value, "street");
            return (Criteria) this;
        }

        public Criteria andStreetNotLike(String value) {
            addCriterion("street not like", value, "street");
            return (Criteria) this;
        }

        public Criteria andStreetIn(List<String> values) {
            addCriterion("street in", values, "street");
            return (Criteria) this;
        }

        public Criteria andStreetNotIn(List<String> values) {
            addCriterion("street not in", values, "street");
            return (Criteria) this;
        }

        public Criteria andStreetBetween(String value1, String value2) {
            addCriterion("street between", value1, value2, "street");
            return (Criteria) this;
        }

        public Criteria andStreetNotBetween(String value1, String value2) {
            addCriterion("street not between", value1, value2, "street");
            return (Criteria) this;
        }

        public Criteria andTariftypIsNull() {
            addCriterion("tariftyp is null");
            return (Criteria) this;
        }

        public Criteria andTariftypIsNotNull() {
            addCriterion("tariftyp is not null");
            return (Criteria) this;
        }

        public Criteria andTariftypEqualTo(String value) {
            addCriterion("tariftyp =", value, "tariftyp");
            return (Criteria) this;
        }

        public Criteria andTariftypNotEqualTo(String value) {
            addCriterion("tariftyp <>", value, "tariftyp");
            return (Criteria) this;
        }

        public Criteria andTariftypGreaterThan(String value) {
            addCriterion("tariftyp >", value, "tariftyp");
            return (Criteria) this;
        }

        public Criteria andTariftypGreaterThanOrEqualTo(String value) {
            addCriterion("tariftyp >=", value, "tariftyp");
            return (Criteria) this;
        }

        public Criteria andTariftypLessThan(String value) {
            addCriterion("tariftyp <", value, "tariftyp");
            return (Criteria) this;
        }

        public Criteria andTariftypLessThanOrEqualTo(String value) {
            addCriterion("tariftyp <=", value, "tariftyp");
            return (Criteria) this;
        }

        public Criteria andTariftypLike(String value) {
            addCriterion("tariftyp like", value, "tariftyp");
            return (Criteria) this;
        }

        public Criteria andTariftypNotLike(String value) {
            addCriterion("tariftyp not like", value, "tariftyp");
            return (Criteria) this;
        }

        public Criteria andTariftypIn(List<String> values) {
            addCriterion("tariftyp in", values, "tariftyp");
            return (Criteria) this;
        }

        public Criteria andTariftypNotIn(List<String> values) {
            addCriterion("tariftyp not in", values, "tariftyp");
            return (Criteria) this;
        }

        public Criteria andTariftypBetween(String value1, String value2) {
            addCriterion("tariftyp between", value1, value2, "tariftyp");
            return (Criteria) this;
        }

        public Criteria andTariftypNotBetween(String value1, String value2) {
            addCriterion("tariftyp not between", value1, value2, "tariftyp");
            return (Criteria) this;
        }

        public Criteria andTelNumber1IsNull() {
            addCriterion("tel_number1 is null");
            return (Criteria) this;
        }

        public Criteria andTelNumber1IsNotNull() {
            addCriterion("tel_number1 is not null");
            return (Criteria) this;
        }

        public Criteria andTelNumber1EqualTo(String value) {
            addCriterion("tel_number1 =", value, "telNumber1");
            return (Criteria) this;
        }

        public Criteria andTelNumber1NotEqualTo(String value) {
            addCriterion("tel_number1 <>", value, "telNumber1");
            return (Criteria) this;
        }

        public Criteria andTelNumber1GreaterThan(String value) {
            addCriterion("tel_number1 >", value, "telNumber1");
            return (Criteria) this;
        }

        public Criteria andTelNumber1GreaterThanOrEqualTo(String value) {
            addCriterion("tel_number1 >=", value, "telNumber1");
            return (Criteria) this;
        }

        public Criteria andTelNumber1LessThan(String value) {
            addCriterion("tel_number1 <", value, "telNumber1");
            return (Criteria) this;
        }

        public Criteria andTelNumber1LessThanOrEqualTo(String value) {
            addCriterion("tel_number1 <=", value, "telNumber1");
            return (Criteria) this;
        }

        public Criteria andTelNumber1Like(String value) {
            addCriterion("tel_number1 like", value, "telNumber1");
            return (Criteria) this;
        }

        public Criteria andTelNumber1NotLike(String value) {
            addCriterion("tel_number1 not like", value, "telNumber1");
            return (Criteria) this;
        }

        public Criteria andTelNumber1In(List<String> values) {
            addCriterion("tel_number1 in", values, "telNumber1");
            return (Criteria) this;
        }

        public Criteria andTelNumber1NotIn(List<String> values) {
            addCriterion("tel_number1 not in", values, "telNumber1");
            return (Criteria) this;
        }

        public Criteria andTelNumber1Between(String value1, String value2) {
            addCriterion("tel_number1 between", value1, value2, "telNumber1");
            return (Criteria) this;
        }

        public Criteria andTelNumber1NotBetween(String value1, String value2) {
            addCriterion("tel_number1 not between", value1, value2, "telNumber1");
            return (Criteria) this;
        }

        public Criteria andTelNumber2IsNull() {
            addCriterion("tel_number2 is null");
            return (Criteria) this;
        }

        public Criteria andTelNumber2IsNotNull() {
            addCriterion("tel_number2 is not null");
            return (Criteria) this;
        }

        public Criteria andTelNumber2EqualTo(String value) {
            addCriterion("tel_number2 =", value, "telNumber2");
            return (Criteria) this;
        }

        public Criteria andTelNumber2NotEqualTo(String value) {
            addCriterion("tel_number2 <>", value, "telNumber2");
            return (Criteria) this;
        }

        public Criteria andTelNumber2GreaterThan(String value) {
            addCriterion("tel_number2 >", value, "telNumber2");
            return (Criteria) this;
        }

        public Criteria andTelNumber2GreaterThanOrEqualTo(String value) {
            addCriterion("tel_number2 >=", value, "telNumber2");
            return (Criteria) this;
        }

        public Criteria andTelNumber2LessThan(String value) {
            addCriterion("tel_number2 <", value, "telNumber2");
            return (Criteria) this;
        }

        public Criteria andTelNumber2LessThanOrEqualTo(String value) {
            addCriterion("tel_number2 <=", value, "telNumber2");
            return (Criteria) this;
        }

        public Criteria andTelNumber2Like(String value) {
            addCriterion("tel_number2 like", value, "telNumber2");
            return (Criteria) this;
        }

        public Criteria andTelNumber2NotLike(String value) {
            addCriterion("tel_number2 not like", value, "telNumber2");
            return (Criteria) this;
        }

        public Criteria andTelNumber2In(List<String> values) {
            addCriterion("tel_number2 in", values, "telNumber2");
            return (Criteria) this;
        }

        public Criteria andTelNumber2NotIn(List<String> values) {
            addCriterion("tel_number2 not in", values, "telNumber2");
            return (Criteria) this;
        }

        public Criteria andTelNumber2Between(String value1, String value2) {
            addCriterion("tel_number2 between", value1, value2, "telNumber2");
            return (Criteria) this;
        }

        public Criteria andTelNumber2NotBetween(String value1, String value2) {
            addCriterion("tel_number2 not between", value1, value2, "telNumber2");
            return (Criteria) this;
        }

        public Criteria andTelNumber3IsNull() {
            addCriterion("tel_number3 is null");
            return (Criteria) this;
        }

        public Criteria andTelNumber3IsNotNull() {
            addCriterion("tel_number3 is not null");
            return (Criteria) this;
        }

        public Criteria andTelNumber3EqualTo(String value) {
            addCriterion("tel_number3 =", value, "telNumber3");
            return (Criteria) this;
        }

        public Criteria andTelNumber3NotEqualTo(String value) {
            addCriterion("tel_number3 <>", value, "telNumber3");
            return (Criteria) this;
        }

        public Criteria andTelNumber3GreaterThan(String value) {
            addCriterion("tel_number3 >", value, "telNumber3");
            return (Criteria) this;
        }

        public Criteria andTelNumber3GreaterThanOrEqualTo(String value) {
            addCriterion("tel_number3 >=", value, "telNumber3");
            return (Criteria) this;
        }

        public Criteria andTelNumber3LessThan(String value) {
            addCriterion("tel_number3 <", value, "telNumber3");
            return (Criteria) this;
        }

        public Criteria andTelNumber3LessThanOrEqualTo(String value) {
            addCriterion("tel_number3 <=", value, "telNumber3");
            return (Criteria) this;
        }

        public Criteria andTelNumber3Like(String value) {
            addCriterion("tel_number3 like", value, "telNumber3");
            return (Criteria) this;
        }

        public Criteria andTelNumber3NotLike(String value) {
            addCriterion("tel_number3 not like", value, "telNumber3");
            return (Criteria) this;
        }

        public Criteria andTelNumber3In(List<String> values) {
            addCriterion("tel_number3 in", values, "telNumber3");
            return (Criteria) this;
        }

        public Criteria andTelNumber3NotIn(List<String> values) {
            addCriterion("tel_number3 not in", values, "telNumber3");
            return (Criteria) this;
        }

        public Criteria andTelNumber3Between(String value1, String value2) {
            addCriterion("tel_number3 between", value1, value2, "telNumber3");
            return (Criteria) this;
        }

        public Criteria andTelNumber3NotBetween(String value1, String value2) {
            addCriterion("tel_number3 not between", value1, value2, "telNumber3");
            return (Criteria) this;
        }

        public Criteria andTelNumber4IsNull() {
            addCriterion("tel_number4 is null");
            return (Criteria) this;
        }

        public Criteria andTelNumber4IsNotNull() {
            addCriterion("tel_number4 is not null");
            return (Criteria) this;
        }

        public Criteria andTelNumber4EqualTo(String value) {
            addCriterion("tel_number4 =", value, "telNumber4");
            return (Criteria) this;
        }

        public Criteria andTelNumber4NotEqualTo(String value) {
            addCriterion("tel_number4 <>", value, "telNumber4");
            return (Criteria) this;
        }

        public Criteria andTelNumber4GreaterThan(String value) {
            addCriterion("tel_number4 >", value, "telNumber4");
            return (Criteria) this;
        }

        public Criteria andTelNumber4GreaterThanOrEqualTo(String value) {
            addCriterion("tel_number4 >=", value, "telNumber4");
            return (Criteria) this;
        }

        public Criteria andTelNumber4LessThan(String value) {
            addCriterion("tel_number4 <", value, "telNumber4");
            return (Criteria) this;
        }

        public Criteria andTelNumber4LessThanOrEqualTo(String value) {
            addCriterion("tel_number4 <=", value, "telNumber4");
            return (Criteria) this;
        }

        public Criteria andTelNumber4Like(String value) {
            addCriterion("tel_number4 like", value, "telNumber4");
            return (Criteria) this;
        }

        public Criteria andTelNumber4NotLike(String value) {
            addCriterion("tel_number4 not like", value, "telNumber4");
            return (Criteria) this;
        }

        public Criteria andTelNumber4In(List<String> values) {
            addCriterion("tel_number4 in", values, "telNumber4");
            return (Criteria) this;
        }

        public Criteria andTelNumber4NotIn(List<String> values) {
            addCriterion("tel_number4 not in", values, "telNumber4");
            return (Criteria) this;
        }

        public Criteria andTelNumber4Between(String value1, String value2) {
            addCriterion("tel_number4 between", value1, value2, "telNumber4");
            return (Criteria) this;
        }

        public Criteria andTelNumber4NotBetween(String value1, String value2) {
            addCriterion("tel_number4 not between", value1, value2, "telNumber4");
            return (Criteria) this;
        }

        public Criteria andTelNumber5IsNull() {
            addCriterion("tel_number5 is null");
            return (Criteria) this;
        }

        public Criteria andTelNumber5IsNotNull() {
            addCriterion("tel_number5 is not null");
            return (Criteria) this;
        }

        public Criteria andTelNumber5EqualTo(String value) {
            addCriterion("tel_number5 =", value, "telNumber5");
            return (Criteria) this;
        }

        public Criteria andTelNumber5NotEqualTo(String value) {
            addCriterion("tel_number5 <>", value, "telNumber5");
            return (Criteria) this;
        }

        public Criteria andTelNumber5GreaterThan(String value) {
            addCriterion("tel_number5 >", value, "telNumber5");
            return (Criteria) this;
        }

        public Criteria andTelNumber5GreaterThanOrEqualTo(String value) {
            addCriterion("tel_number5 >=", value, "telNumber5");
            return (Criteria) this;
        }

        public Criteria andTelNumber5LessThan(String value) {
            addCriterion("tel_number5 <", value, "telNumber5");
            return (Criteria) this;
        }

        public Criteria andTelNumber5LessThanOrEqualTo(String value) {
            addCriterion("tel_number5 <=", value, "telNumber5");
            return (Criteria) this;
        }

        public Criteria andTelNumber5Like(String value) {
            addCriterion("tel_number5 like", value, "telNumber5");
            return (Criteria) this;
        }

        public Criteria andTelNumber5NotLike(String value) {
            addCriterion("tel_number5 not like", value, "telNumber5");
            return (Criteria) this;
        }

        public Criteria andTelNumber5In(List<String> values) {
            addCriterion("tel_number5 in", values, "telNumber5");
            return (Criteria) this;
        }

        public Criteria andTelNumber5NotIn(List<String> values) {
            addCriterion("tel_number5 not in", values, "telNumber5");
            return (Criteria) this;
        }

        public Criteria andTelNumber5Between(String value1, String value2) {
            addCriterion("tel_number5 between", value1, value2, "telNumber5");
            return (Criteria) this;
        }

        public Criteria andTelNumber5NotBetween(String value1, String value2) {
            addCriterion("tel_number5 not between", value1, value2, "telNumber5");
            return (Criteria) this;
        }

        public Criteria andUploadFlagIsNull() {
            addCriterion("upload_flag is null");
            return (Criteria) this;
        }

        public Criteria andUploadFlagIsNotNull() {
            addCriterion("upload_flag is not null");
            return (Criteria) this;
        }

        public Criteria andUploadFlagEqualTo(String value) {
            addCriterion("upload_flag =", value, "uploadFlag");
            return (Criteria) this;
        }

        public Criteria andUploadFlagNotEqualTo(String value) {
            addCriterion("upload_flag <>", value, "uploadFlag");
            return (Criteria) this;
        }

        public Criteria andUploadFlagGreaterThan(String value) {
            addCriterion("upload_flag >", value, "uploadFlag");
            return (Criteria) this;
        }

        public Criteria andUploadFlagGreaterThanOrEqualTo(String value) {
            addCriterion("upload_flag >=", value, "uploadFlag");
            return (Criteria) this;
        }

        public Criteria andUploadFlagLessThan(String value) {
            addCriterion("upload_flag <", value, "uploadFlag");
            return (Criteria) this;
        }

        public Criteria andUploadFlagLessThanOrEqualTo(String value) {
            addCriterion("upload_flag <=", value, "uploadFlag");
            return (Criteria) this;
        }

        public Criteria andUploadFlagLike(String value) {
            addCriterion("upload_flag like", value, "uploadFlag");
            return (Criteria) this;
        }

        public Criteria andUploadFlagNotLike(String value) {
            addCriterion("upload_flag not like", value, "uploadFlag");
            return (Criteria) this;
        }

        public Criteria andUploadFlagIn(List<String> values) {
            addCriterion("upload_flag in", values, "uploadFlag");
            return (Criteria) this;
        }

        public Criteria andUploadFlagNotIn(List<String> values) {
            addCriterion("upload_flag not in", values, "uploadFlag");
            return (Criteria) this;
        }

        public Criteria andUploadFlagBetween(String value1, String value2) {
            addCriterion("upload_flag between", value1, value2, "uploadFlag");
            return (Criteria) this;
        }

        public Criteria andUploadFlagNotBetween(String value1, String value2) {
            addCriterion("upload_flag not between", value1, value2, "uploadFlag");
            return (Criteria) this;
        }

        public Criteria andVertragIsNull() {
            addCriterion("vertrag is null");
            return (Criteria) this;
        }

        public Criteria andVertragIsNotNull() {
            addCriterion("vertrag is not null");
            return (Criteria) this;
        }

        public Criteria andVertragEqualTo(String value) {
            addCriterion("vertrag =", value, "vertrag");
            return (Criteria) this;
        }

        public Criteria andVertragNotEqualTo(String value) {
            addCriterion("vertrag <>", value, "vertrag");
            return (Criteria) this;
        }

        public Criteria andVertragGreaterThan(String value) {
            addCriterion("vertrag >", value, "vertrag");
            return (Criteria) this;
        }

        public Criteria andVertragGreaterThanOrEqualTo(String value) {
            addCriterion("vertrag >=", value, "vertrag");
            return (Criteria) this;
        }

        public Criteria andVertragLessThan(String value) {
            addCriterion("vertrag <", value, "vertrag");
            return (Criteria) this;
        }

        public Criteria andVertragLessThanOrEqualTo(String value) {
            addCriterion("vertrag <=", value, "vertrag");
            return (Criteria) this;
        }

        public Criteria andVertragLike(String value) {
            addCriterion("vertrag like", value, "vertrag");
            return (Criteria) this;
        }

        public Criteria andVertragNotLike(String value) {
            addCriterion("vertrag not like", value, "vertrag");
            return (Criteria) this;
        }

        public Criteria andVertragIn(List<String> values) {
            addCriterion("vertrag in", values, "vertrag");
            return (Criteria) this;
        }

        public Criteria andVertragNotIn(List<String> values) {
            addCriterion("vertrag not in", values, "vertrag");
            return (Criteria) this;
        }

        public Criteria andVertragBetween(String value1, String value2) {
            addCriterion("vertrag between", value1, value2, "vertrag");
            return (Criteria) this;
        }

        public Criteria andVertragNotBetween(String value1, String value2) {
            addCriterion("vertrag not between", value1, value2, "vertrag");
            return (Criteria) this;
        }

        public Criteria andVstelleIsNull() {
            addCriterion("vstelle is null");
            return (Criteria) this;
        }

        public Criteria andVstelleIsNotNull() {
            addCriterion("vstelle is not null");
            return (Criteria) this;
        }

        public Criteria andVstelleEqualTo(String value) {
            addCriterion("vstelle =", value, "vstelle");
            return (Criteria) this;
        }

        public Criteria andVstelleNotEqualTo(String value) {
            addCriterion("vstelle <>", value, "vstelle");
            return (Criteria) this;
        }

        public Criteria andVstelleGreaterThan(String value) {
            addCriterion("vstelle >", value, "vstelle");
            return (Criteria) this;
        }

        public Criteria andVstelleGreaterThanOrEqualTo(String value) {
            addCriterion("vstelle >=", value, "vstelle");
            return (Criteria) this;
        }

        public Criteria andVstelleLessThan(String value) {
            addCriterion("vstelle <", value, "vstelle");
            return (Criteria) this;
        }

        public Criteria andVstelleLessThanOrEqualTo(String value) {
            addCriterion("vstelle <=", value, "vstelle");
            return (Criteria) this;
        }

        public Criteria andVstelleLike(String value) {
            addCriterion("vstelle like", value, "vstelle");
            return (Criteria) this;
        }

        public Criteria andVstelleNotLike(String value) {
            addCriterion("vstelle not like", value, "vstelle");
            return (Criteria) this;
        }

        public Criteria andVstelleIn(List<String> values) {
            addCriterion("vstelle in", values, "vstelle");
            return (Criteria) this;
        }

        public Criteria andVstelleNotIn(List<String> values) {
            addCriterion("vstelle not in", values, "vstelle");
            return (Criteria) this;
        }

        public Criteria andVstelleBetween(String value1, String value2) {
            addCriterion("vstelle between", value1, value2, "vstelle");
            return (Criteria) this;
        }

        public Criteria andVstelleNotBetween(String value1, String value2) {
            addCriterion("vstelle not between", value1, value2, "vstelle");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ichcustomerinfo
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ichcustomerinfo
     *
     * @mbg.generated
     */
    public static class Criterion implements Serializable {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}