package com.ecej.po;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class ICHGasEquiExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ichgasequi
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ichgasequi
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ichgasequi
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ichgasequi
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichgasequi
     *
     * @mbg.generated
     */
    public ICHGasEquiExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichgasequi
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichgasequi
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichgasequi
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichgasequi
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichgasequi
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichgasequi
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichgasequi
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichgasequi
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichgasequi
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichgasequi
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ichgasequi
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria implements Serializable {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBauformIsNull() {
            addCriterion("bauform is null");
            return (Criteria) this;
        }

        public Criteria andBauformIsNotNull() {
            addCriterion("bauform is not null");
            return (Criteria) this;
        }

        public Criteria andBauformEqualTo(String value) {
            addCriterion("bauform =", value, "bauform");
            return (Criteria) this;
        }

        public Criteria andBauformNotEqualTo(String value) {
            addCriterion("bauform <>", value, "bauform");
            return (Criteria) this;
        }

        public Criteria andBauformGreaterThan(String value) {
            addCriterion("bauform >", value, "bauform");
            return (Criteria) this;
        }

        public Criteria andBauformGreaterThanOrEqualTo(String value) {
            addCriterion("bauform >=", value, "bauform");
            return (Criteria) this;
        }

        public Criteria andBauformLessThan(String value) {
            addCriterion("bauform <", value, "bauform");
            return (Criteria) this;
        }

        public Criteria andBauformLessThanOrEqualTo(String value) {
            addCriterion("bauform <=", value, "bauform");
            return (Criteria) this;
        }

        public Criteria andBauformLike(String value) {
            addCriterion("bauform like", value, "bauform");
            return (Criteria) this;
        }

        public Criteria andBauformNotLike(String value) {
            addCriterion("bauform not like", value, "bauform");
            return (Criteria) this;
        }

        public Criteria andBauformIn(List<String> values) {
            addCriterion("bauform in", values, "bauform");
            return (Criteria) this;
        }

        public Criteria andBauformNotIn(List<String> values) {
            addCriterion("bauform not in", values, "bauform");
            return (Criteria) this;
        }

        public Criteria andBauformBetween(String value1, String value2) {
            addCriterion("bauform between", value1, value2, "bauform");
            return (Criteria) this;
        }

        public Criteria andBauformNotBetween(String value1, String value2) {
            addCriterion("bauform not between", value1, value2, "bauform");
            return (Criteria) this;
        }

        public Criteria andBauklasIsNull() {
            addCriterion("bauklas is null");
            return (Criteria) this;
        }

        public Criteria andBauklasIsNotNull() {
            addCriterion("bauklas is not null");
            return (Criteria) this;
        }

        public Criteria andBauklasEqualTo(String value) {
            addCriterion("bauklas =", value, "bauklas");
            return (Criteria) this;
        }

        public Criteria andBauklasNotEqualTo(String value) {
            addCriterion("bauklas <>", value, "bauklas");
            return (Criteria) this;
        }

        public Criteria andBauklasGreaterThan(String value) {
            addCriterion("bauklas >", value, "bauklas");
            return (Criteria) this;
        }

        public Criteria andBauklasGreaterThanOrEqualTo(String value) {
            addCriterion("bauklas >=", value, "bauklas");
            return (Criteria) this;
        }

        public Criteria andBauklasLessThan(String value) {
            addCriterion("bauklas <", value, "bauklas");
            return (Criteria) this;
        }

        public Criteria andBauklasLessThanOrEqualTo(String value) {
            addCriterion("bauklas <=", value, "bauklas");
            return (Criteria) this;
        }

        public Criteria andBauklasLike(String value) {
            addCriterion("bauklas like", value, "bauklas");
            return (Criteria) this;
        }

        public Criteria andBauklasNotLike(String value) {
            addCriterion("bauklas not like", value, "bauklas");
            return (Criteria) this;
        }

        public Criteria andBauklasIn(List<String> values) {
            addCriterion("bauklas in", values, "bauklas");
            return (Criteria) this;
        }

        public Criteria andBauklasNotIn(List<String> values) {
            addCriterion("bauklas not in", values, "bauklas");
            return (Criteria) this;
        }

        public Criteria andBauklasBetween(String value1, String value2) {
            addCriterion("bauklas between", value1, value2, "bauklas");
            return (Criteria) this;
        }

        public Criteria andBauklasNotBetween(String value1, String value2) {
            addCriterion("bauklas not between", value1, value2, "bauklas");
            return (Criteria) this;
        }

        public Criteria andEartxIsNull() {
            addCriterion("eartx is null");
            return (Criteria) this;
        }

        public Criteria andEartxIsNotNull() {
            addCriterion("eartx is not null");
            return (Criteria) this;
        }

        public Criteria andEartxEqualTo(String value) {
            addCriterion("eartx =", value, "eartx");
            return (Criteria) this;
        }

        public Criteria andEartxNotEqualTo(String value) {
            addCriterion("eartx <>", value, "eartx");
            return (Criteria) this;
        }

        public Criteria andEartxGreaterThan(String value) {
            addCriterion("eartx >", value, "eartx");
            return (Criteria) this;
        }

        public Criteria andEartxGreaterThanOrEqualTo(String value) {
            addCriterion("eartx >=", value, "eartx");
            return (Criteria) this;
        }

        public Criteria andEartxLessThan(String value) {
            addCriterion("eartx <", value, "eartx");
            return (Criteria) this;
        }

        public Criteria andEartxLessThanOrEqualTo(String value) {
            addCriterion("eartx <=", value, "eartx");
            return (Criteria) this;
        }

        public Criteria andEartxLike(String value) {
            addCriterion("eartx like", value, "eartx");
            return (Criteria) this;
        }

        public Criteria andEartxNotLike(String value) {
            addCriterion("eartx not like", value, "eartx");
            return (Criteria) this;
        }

        public Criteria andEartxIn(List<String> values) {
            addCriterion("eartx in", values, "eartx");
            return (Criteria) this;
        }

        public Criteria andEartxNotIn(List<String> values) {
            addCriterion("eartx not in", values, "eartx");
            return (Criteria) this;
        }

        public Criteria andEartxBetween(String value1, String value2) {
            addCriterion("eartx between", value1, value2, "eartx");
            return (Criteria) this;
        }

        public Criteria andEartxNotBetween(String value1, String value2) {
            addCriterion("eartx not between", value1, value2, "eartx");
            return (Criteria) this;
        }

        public Criteria andEqartIsNull() {
            addCriterion("eqart is null");
            return (Criteria) this;
        }

        public Criteria andEqartIsNotNull() {
            addCriterion("eqart is not null");
            return (Criteria) this;
        }

        public Criteria andEqartEqualTo(String value) {
            addCriterion("eqart =", value, "eqart");
            return (Criteria) this;
        }

        public Criteria andEqartNotEqualTo(String value) {
            addCriterion("eqart <>", value, "eqart");
            return (Criteria) this;
        }

        public Criteria andEqartGreaterThan(String value) {
            addCriterion("eqart >", value, "eqart");
            return (Criteria) this;
        }

        public Criteria andEqartGreaterThanOrEqualTo(String value) {
            addCriterion("eqart >=", value, "eqart");
            return (Criteria) this;
        }

        public Criteria andEqartLessThan(String value) {
            addCriterion("eqart <", value, "eqart");
            return (Criteria) this;
        }

        public Criteria andEqartLessThanOrEqualTo(String value) {
            addCriterion("eqart <=", value, "eqart");
            return (Criteria) this;
        }

        public Criteria andEqartLike(String value) {
            addCriterion("eqart like", value, "eqart");
            return (Criteria) this;
        }

        public Criteria andEqartNotLike(String value) {
            addCriterion("eqart not like", value, "eqart");
            return (Criteria) this;
        }

        public Criteria andEqartIn(List<String> values) {
            addCriterion("eqart in", values, "eqart");
            return (Criteria) this;
        }

        public Criteria andEqartNotIn(List<String> values) {
            addCriterion("eqart not in", values, "eqart");
            return (Criteria) this;
        }

        public Criteria andEqartBetween(String value1, String value2) {
            addCriterion("eqart between", value1, value2, "eqart");
            return (Criteria) this;
        }

        public Criteria andEqartNotBetween(String value1, String value2) {
            addCriterion("eqart not between", value1, value2, "eqart");
            return (Criteria) this;
        }

        public Criteria andEqunrIsNull() {
            addCriterion("equnr is null");
            return (Criteria) this;
        }

        public Criteria andEqunrIsNotNull() {
            addCriterion("equnr is not null");
            return (Criteria) this;
        }

        public Criteria andEqunrEqualTo(String value) {
            addCriterion("equnr =", value, "equnr");
            return (Criteria) this;
        }

        public Criteria andEqunrNotEqualTo(String value) {
            addCriterion("equnr <>", value, "equnr");
            return (Criteria) this;
        }

        public Criteria andEqunrGreaterThan(String value) {
            addCriterion("equnr >", value, "equnr");
            return (Criteria) this;
        }

        public Criteria andEqunrGreaterThanOrEqualTo(String value) {
            addCriterion("equnr >=", value, "equnr");
            return (Criteria) this;
        }

        public Criteria andEqunrLessThan(String value) {
            addCriterion("equnr <", value, "equnr");
            return (Criteria) this;
        }

        public Criteria andEqunrLessThanOrEqualTo(String value) {
            addCriterion("equnr <=", value, "equnr");
            return (Criteria) this;
        }

        public Criteria andEqunrLike(String value) {
            addCriterion("equnr like", value, "equnr");
            return (Criteria) this;
        }

        public Criteria andEqunrNotLike(String value) {
            addCriterion("equnr not like", value, "equnr");
            return (Criteria) this;
        }

        public Criteria andEqunrIn(List<String> values) {
            addCriterion("equnr in", values, "equnr");
            return (Criteria) this;
        }

        public Criteria andEqunrNotIn(List<String> values) {
            addCriterion("equnr not in", values, "equnr");
            return (Criteria) this;
        }

        public Criteria andEqunrBetween(String value1, String value2) {
            addCriterion("equnr between", value1, value2, "equnr");
            return (Criteria) this;
        }

        public Criteria andEqunrNotBetween(String value1, String value2) {
            addCriterion("equnr not between", value1, value2, "equnr");
            return (Criteria) this;
        }

        public Criteria andEstatIsNull() {
            addCriterion("estat is null");
            return (Criteria) this;
        }

        public Criteria andEstatIsNotNull() {
            addCriterion("estat is not null");
            return (Criteria) this;
        }

        public Criteria andEstatEqualTo(String value) {
            addCriterion("estat =", value, "estat");
            return (Criteria) this;
        }

        public Criteria andEstatNotEqualTo(String value) {
            addCriterion("estat <>", value, "estat");
            return (Criteria) this;
        }

        public Criteria andEstatGreaterThan(String value) {
            addCriterion("estat >", value, "estat");
            return (Criteria) this;
        }

        public Criteria andEstatGreaterThanOrEqualTo(String value) {
            addCriterion("estat >=", value, "estat");
            return (Criteria) this;
        }

        public Criteria andEstatLessThan(String value) {
            addCriterion("estat <", value, "estat");
            return (Criteria) this;
        }

        public Criteria andEstatLessThanOrEqualTo(String value) {
            addCriterion("estat <=", value, "estat");
            return (Criteria) this;
        }

        public Criteria andEstatLike(String value) {
            addCriterion("estat like", value, "estat");
            return (Criteria) this;
        }

        public Criteria andEstatNotLike(String value) {
            addCriterion("estat not like", value, "estat");
            return (Criteria) this;
        }

        public Criteria andEstatIn(List<String> values) {
            addCriterion("estat in", values, "estat");
            return (Criteria) this;
        }

        public Criteria andEstatNotIn(List<String> values) {
            addCriterion("estat not in", values, "estat");
            return (Criteria) this;
        }

        public Criteria andEstatBetween(String value1, String value2) {
            addCriterion("estat between", value1, value2, "estat");
            return (Criteria) this;
        }

        public Criteria andEstatNotBetween(String value1, String value2) {
            addCriterion("estat not between", value1, value2, "estat");
            return (Criteria) this;
        }

        public Criteria andEstxtIsNull() {
            addCriterion("estxt is null");
            return (Criteria) this;
        }

        public Criteria andEstxtIsNotNull() {
            addCriterion("estxt is not null");
            return (Criteria) this;
        }

        public Criteria andEstxtEqualTo(String value) {
            addCriterion("estxt =", value, "estxt");
            return (Criteria) this;
        }

        public Criteria andEstxtNotEqualTo(String value) {
            addCriterion("estxt <>", value, "estxt");
            return (Criteria) this;
        }

        public Criteria andEstxtGreaterThan(String value) {
            addCriterion("estxt >", value, "estxt");
            return (Criteria) this;
        }

        public Criteria andEstxtGreaterThanOrEqualTo(String value) {
            addCriterion("estxt >=", value, "estxt");
            return (Criteria) this;
        }

        public Criteria andEstxtLessThan(String value) {
            addCriterion("estxt <", value, "estxt");
            return (Criteria) this;
        }

        public Criteria andEstxtLessThanOrEqualTo(String value) {
            addCriterion("estxt <=", value, "estxt");
            return (Criteria) this;
        }

        public Criteria andEstxtLike(String value) {
            addCriterion("estxt like", value, "estxt");
            return (Criteria) this;
        }

        public Criteria andEstxtNotLike(String value) {
            addCriterion("estxt not like", value, "estxt");
            return (Criteria) this;
        }

        public Criteria andEstxtIn(List<String> values) {
            addCriterion("estxt in", values, "estxt");
            return (Criteria) this;
        }

        public Criteria andEstxtNotIn(List<String> values) {
            addCriterion("estxt not in", values, "estxt");
            return (Criteria) this;
        }

        public Criteria andEstxtBetween(String value1, String value2) {
            addCriterion("estxt between", value1, value2, "estxt");
            return (Criteria) this;
        }

        public Criteria andEstxtNotBetween(String value1, String value2) {
            addCriterion("estxt not between", value1, value2, "estxt");
            return (Criteria) this;
        }

        public Criteria andGwldtIsNull() {
            addCriterion("gwldt is null");
            return (Criteria) this;
        }

        public Criteria andGwldtIsNotNull() {
            addCriterion("gwldt is not null");
            return (Criteria) this;
        }

        public Criteria andGwldtEqualTo(String value) {
            addCriterion("gwldt =", value, "gwldt");
            return (Criteria) this;
        }

        public Criteria andGwldtNotEqualTo(String value) {
            addCriterion("gwldt <>", value, "gwldt");
            return (Criteria) this;
        }

        public Criteria andGwldtGreaterThan(String value) {
            addCriterion("gwldt >", value, "gwldt");
            return (Criteria) this;
        }

        public Criteria andGwldtGreaterThanOrEqualTo(String value) {
            addCriterion("gwldt >=", value, "gwldt");
            return (Criteria) this;
        }

        public Criteria andGwldtLessThan(String value) {
            addCriterion("gwldt <", value, "gwldt");
            return (Criteria) this;
        }

        public Criteria andGwldtLessThanOrEqualTo(String value) {
            addCriterion("gwldt <=", value, "gwldt");
            return (Criteria) this;
        }

        public Criteria andGwldtLike(String value) {
            addCriterion("gwldt like", value, "gwldt");
            return (Criteria) this;
        }

        public Criteria andGwldtNotLike(String value) {
            addCriterion("gwldt not like", value, "gwldt");
            return (Criteria) this;
        }

        public Criteria andGwldtIn(List<String> values) {
            addCriterion("gwldt in", values, "gwldt");
            return (Criteria) this;
        }

        public Criteria andGwldtNotIn(List<String> values) {
            addCriterion("gwldt not in", values, "gwldt");
            return (Criteria) this;
        }

        public Criteria andGwldtBetween(String value1, String value2) {
            addCriterion("gwldt between", value1, value2, "gwldt");
            return (Criteria) this;
        }

        public Criteria andGwldtNotBetween(String value1, String value2) {
            addCriterion("gwldt not between", value1, value2, "gwldt");
            return (Criteria) this;
        }

        public Criteria andGwlenIsNull() {
            addCriterion("gwlen is null");
            return (Criteria) this;
        }

        public Criteria andGwlenIsNotNull() {
            addCriterion("gwlen is not null");
            return (Criteria) this;
        }

        public Criteria andGwlenEqualTo(String value) {
            addCriterion("gwlen =", value, "gwlen");
            return (Criteria) this;
        }

        public Criteria andGwlenNotEqualTo(String value) {
            addCriterion("gwlen <>", value, "gwlen");
            return (Criteria) this;
        }

        public Criteria andGwlenGreaterThan(String value) {
            addCriterion("gwlen >", value, "gwlen");
            return (Criteria) this;
        }

        public Criteria andGwlenGreaterThanOrEqualTo(String value) {
            addCriterion("gwlen >=", value, "gwlen");
            return (Criteria) this;
        }

        public Criteria andGwlenLessThan(String value) {
            addCriterion("gwlen <", value, "gwlen");
            return (Criteria) this;
        }

        public Criteria andGwlenLessThanOrEqualTo(String value) {
            addCriterion("gwlen <=", value, "gwlen");
            return (Criteria) this;
        }

        public Criteria andGwlenLike(String value) {
            addCriterion("gwlen like", value, "gwlen");
            return (Criteria) this;
        }

        public Criteria andGwlenNotLike(String value) {
            addCriterion("gwlen not like", value, "gwlen");
            return (Criteria) this;
        }

        public Criteria andGwlenIn(List<String> values) {
            addCriterion("gwlen in", values, "gwlen");
            return (Criteria) this;
        }

        public Criteria andGwlenNotIn(List<String> values) {
            addCriterion("gwlen not in", values, "gwlen");
            return (Criteria) this;
        }

        public Criteria andGwlenBetween(String value1, String value2) {
            addCriterion("gwlen between", value1, value2, "gwlen");
            return (Criteria) this;
        }

        public Criteria andGwlenNotBetween(String value1, String value2) {
            addCriterion("gwlen not between", value1, value2, "gwlen");
            return (Criteria) this;
        }

        public Criteria andHerstIsNull() {
            addCriterion("herst is null");
            return (Criteria) this;
        }

        public Criteria andHerstIsNotNull() {
            addCriterion("herst is not null");
            return (Criteria) this;
        }

        public Criteria andHerstEqualTo(String value) {
            addCriterion("herst =", value, "herst");
            return (Criteria) this;
        }

        public Criteria andHerstNotEqualTo(String value) {
            addCriterion("herst <>", value, "herst");
            return (Criteria) this;
        }

        public Criteria andHerstGreaterThan(String value) {
            addCriterion("herst >", value, "herst");
            return (Criteria) this;
        }

        public Criteria andHerstGreaterThanOrEqualTo(String value) {
            addCriterion("herst >=", value, "herst");
            return (Criteria) this;
        }

        public Criteria andHerstLessThan(String value) {
            addCriterion("herst <", value, "herst");
            return (Criteria) this;
        }

        public Criteria andHerstLessThanOrEqualTo(String value) {
            addCriterion("herst <=", value, "herst");
            return (Criteria) this;
        }

        public Criteria andHerstLike(String value) {
            addCriterion("herst like", value, "herst");
            return (Criteria) this;
        }

        public Criteria andHerstNotLike(String value) {
            addCriterion("herst not like", value, "herst");
            return (Criteria) this;
        }

        public Criteria andHerstIn(List<String> values) {
            addCriterion("herst in", values, "herst");
            return (Criteria) this;
        }

        public Criteria andHerstNotIn(List<String> values) {
            addCriterion("herst not in", values, "herst");
            return (Criteria) this;
        }

        public Criteria andHerstBetween(String value1, String value2) {
            addCriterion("herst between", value1, value2, "herst");
            return (Criteria) this;
        }

        public Criteria andHerstNotBetween(String value1, String value2) {
            addCriterion("herst not between", value1, value2, "herst");
            return (Criteria) this;
        }

        public Criteria andOpeEqIsNull() {
            addCriterion("ope_eq is null");
            return (Criteria) this;
        }

        public Criteria andOpeEqIsNotNull() {
            addCriterion("ope_eq is not null");
            return (Criteria) this;
        }

        public Criteria andOpeEqEqualTo(String value) {
            addCriterion("ope_eq =", value, "opeEq");
            return (Criteria) this;
        }

        public Criteria andOpeEqNotEqualTo(String value) {
            addCriterion("ope_eq <>", value, "opeEq");
            return (Criteria) this;
        }

        public Criteria andOpeEqGreaterThan(String value) {
            addCriterion("ope_eq >", value, "opeEq");
            return (Criteria) this;
        }

        public Criteria andOpeEqGreaterThanOrEqualTo(String value) {
            addCriterion("ope_eq >=", value, "opeEq");
            return (Criteria) this;
        }

        public Criteria andOpeEqLessThan(String value) {
            addCriterion("ope_eq <", value, "opeEq");
            return (Criteria) this;
        }

        public Criteria andOpeEqLessThanOrEqualTo(String value) {
            addCriterion("ope_eq <=", value, "opeEq");
            return (Criteria) this;
        }

        public Criteria andOpeEqLike(String value) {
            addCriterion("ope_eq like", value, "opeEq");
            return (Criteria) this;
        }

        public Criteria andOpeEqNotLike(String value) {
            addCriterion("ope_eq not like", value, "opeEq");
            return (Criteria) this;
        }

        public Criteria andOpeEqIn(List<String> values) {
            addCriterion("ope_eq in", values, "opeEq");
            return (Criteria) this;
        }

        public Criteria andOpeEqNotIn(List<String> values) {
            addCriterion("ope_eq not in", values, "opeEq");
            return (Criteria) this;
        }

        public Criteria andOpeEqBetween(String value1, String value2) {
            addCriterion("ope_eq between", value1, value2, "opeEq");
            return (Criteria) this;
        }

        public Criteria andOpeEqNotBetween(String value1, String value2) {
            addCriterion("ope_eq not between", value1, value2, "opeEq");
            return (Criteria) this;
        }

        public Criteria andPlanIdIsNull() {
            addCriterion("plan_id is null");
            return (Criteria) this;
        }

        public Criteria andPlanIdIsNotNull() {
            addCriterion("plan_id is not null");
            return (Criteria) this;
        }

        public Criteria andPlanIdEqualTo(Integer value) {
            addCriterion("plan_id =", value, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdNotEqualTo(Integer value) {
            addCriterion("plan_id <>", value, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdGreaterThan(Integer value) {
            addCriterion("plan_id >", value, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("plan_id >=", value, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdLessThan(Integer value) {
            addCriterion("plan_id <", value, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdLessThanOrEqualTo(Integer value) {
            addCriterion("plan_id <=", value, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdIn(List<Integer> values) {
            addCriterion("plan_id in", values, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdNotIn(List<Integer> values) {
            addCriterion("plan_id not in", values, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdBetween(Integer value1, Integer value2) {
            addCriterion("plan_id between", value1, value2, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdNotBetween(Integer value1, Integer value2) {
            addCriterion("plan_id not between", value1, value2, "planId");
            return (Criteria) this;
        }

        public Criteria andSergeIsNull() {
            addCriterion("serge is null");
            return (Criteria) this;
        }

        public Criteria andSergeIsNotNull() {
            addCriterion("serge is not null");
            return (Criteria) this;
        }

        public Criteria andSergeEqualTo(String value) {
            addCriterion("serge =", value, "serge");
            return (Criteria) this;
        }

        public Criteria andSergeNotEqualTo(String value) {
            addCriterion("serge <>", value, "serge");
            return (Criteria) this;
        }

        public Criteria andSergeGreaterThan(String value) {
            addCriterion("serge >", value, "serge");
            return (Criteria) this;
        }

        public Criteria andSergeGreaterThanOrEqualTo(String value) {
            addCriterion("serge >=", value, "serge");
            return (Criteria) this;
        }

        public Criteria andSergeLessThan(String value) {
            addCriterion("serge <", value, "serge");
            return (Criteria) this;
        }

        public Criteria andSergeLessThanOrEqualTo(String value) {
            addCriterion("serge <=", value, "serge");
            return (Criteria) this;
        }

        public Criteria andSergeLike(String value) {
            addCriterion("serge like", value, "serge");
            return (Criteria) this;
        }

        public Criteria andSergeNotLike(String value) {
            addCriterion("serge not like", value, "serge");
            return (Criteria) this;
        }

        public Criteria andSergeIn(List<String> values) {
            addCriterion("serge in", values, "serge");
            return (Criteria) this;
        }

        public Criteria andSergeNotIn(List<String> values) {
            addCriterion("serge not in", values, "serge");
            return (Criteria) this;
        }

        public Criteria andSergeBetween(String value1, String value2) {
            addCriterion("serge between", value1, value2, "serge");
            return (Criteria) this;
        }

        public Criteria andSergeNotBetween(String value1, String value2) {
            addCriterion("serge not between", value1, value2, "serge");
            return (Criteria) this;
        }

        public Criteria andTypbzIsNull() {
            addCriterion("typbz is null");
            return (Criteria) this;
        }

        public Criteria andTypbzIsNotNull() {
            addCriterion("typbz is not null");
            return (Criteria) this;
        }

        public Criteria andTypbzEqualTo(String value) {
            addCriterion("typbz =", value, "typbz");
            return (Criteria) this;
        }

        public Criteria andTypbzNotEqualTo(String value) {
            addCriterion("typbz <>", value, "typbz");
            return (Criteria) this;
        }

        public Criteria andTypbzGreaterThan(String value) {
            addCriterion("typbz >", value, "typbz");
            return (Criteria) this;
        }

        public Criteria andTypbzGreaterThanOrEqualTo(String value) {
            addCriterion("typbz >=", value, "typbz");
            return (Criteria) this;
        }

        public Criteria andTypbzLessThan(String value) {
            addCriterion("typbz <", value, "typbz");
            return (Criteria) this;
        }

        public Criteria andTypbzLessThanOrEqualTo(String value) {
            addCriterion("typbz <=", value, "typbz");
            return (Criteria) this;
        }

        public Criteria andTypbzLike(String value) {
            addCriterion("typbz like", value, "typbz");
            return (Criteria) this;
        }

        public Criteria andTypbzNotLike(String value) {
            addCriterion("typbz not like", value, "typbz");
            return (Criteria) this;
        }

        public Criteria andTypbzIn(List<String> values) {
            addCriterion("typbz in", values, "typbz");
            return (Criteria) this;
        }

        public Criteria andTypbzNotIn(List<String> values) {
            addCriterion("typbz not in", values, "typbz");
            return (Criteria) this;
        }

        public Criteria andTypbzBetween(String value1, String value2) {
            addCriterion("typbz between", value1, value2, "typbz");
            return (Criteria) this;
        }

        public Criteria andTypbzNotBetween(String value1, String value2) {
            addCriterion("typbz not between", value1, value2, "typbz");
            return (Criteria) this;
        }

        public Criteria andUploadFlagIsNull() {
            addCriterion("upload_flag is null");
            return (Criteria) this;
        }

        public Criteria andUploadFlagIsNotNull() {
            addCriterion("upload_flag is not null");
            return (Criteria) this;
        }

        public Criteria andUploadFlagEqualTo(String value) {
            addCriterion("upload_flag =", value, "uploadFlag");
            return (Criteria) this;
        }

        public Criteria andUploadFlagNotEqualTo(String value) {
            addCriterion("upload_flag <>", value, "uploadFlag");
            return (Criteria) this;
        }

        public Criteria andUploadFlagGreaterThan(String value) {
            addCriterion("upload_flag >", value, "uploadFlag");
            return (Criteria) this;
        }

        public Criteria andUploadFlagGreaterThanOrEqualTo(String value) {
            addCriterion("upload_flag >=", value, "uploadFlag");
            return (Criteria) this;
        }

        public Criteria andUploadFlagLessThan(String value) {
            addCriterion("upload_flag <", value, "uploadFlag");
            return (Criteria) this;
        }

        public Criteria andUploadFlagLessThanOrEqualTo(String value) {
            addCriterion("upload_flag <=", value, "uploadFlag");
            return (Criteria) this;
        }

        public Criteria andUploadFlagLike(String value) {
            addCriterion("upload_flag like", value, "uploadFlag");
            return (Criteria) this;
        }

        public Criteria andUploadFlagNotLike(String value) {
            addCriterion("upload_flag not like", value, "uploadFlag");
            return (Criteria) this;
        }

        public Criteria andUploadFlagIn(List<String> values) {
            addCriterion("upload_flag in", values, "uploadFlag");
            return (Criteria) this;
        }

        public Criteria andUploadFlagNotIn(List<String> values) {
            addCriterion("upload_flag not in", values, "uploadFlag");
            return (Criteria) this;
        }

        public Criteria andUploadFlagBetween(String value1, String value2) {
            addCriterion("upload_flag between", value1, value2, "uploadFlag");
            return (Criteria) this;
        }

        public Criteria andUploadFlagNotBetween(String value1, String value2) {
            addCriterion("upload_flag not between", value1, value2, "uploadFlag");
            return (Criteria) this;
        }

        public Criteria andVstelleIsNull() {
            addCriterion("vstelle is null");
            return (Criteria) this;
        }

        public Criteria andVstelleIsNotNull() {
            addCriterion("vstelle is not null");
            return (Criteria) this;
        }

        public Criteria andVstelleEqualTo(String value) {
            addCriterion("vstelle =", value, "vstelle");
            return (Criteria) this;
        }

        public Criteria andVstelleNotEqualTo(String value) {
            addCriterion("vstelle <>", value, "vstelle");
            return (Criteria) this;
        }

        public Criteria andVstelleGreaterThan(String value) {
            addCriterion("vstelle >", value, "vstelle");
            return (Criteria) this;
        }

        public Criteria andVstelleGreaterThanOrEqualTo(String value) {
            addCriterion("vstelle >=", value, "vstelle");
            return (Criteria) this;
        }

        public Criteria andVstelleLessThan(String value) {
            addCriterion("vstelle <", value, "vstelle");
            return (Criteria) this;
        }

        public Criteria andVstelleLessThanOrEqualTo(String value) {
            addCriterion("vstelle <=", value, "vstelle");
            return (Criteria) this;
        }

        public Criteria andVstelleLike(String value) {
            addCriterion("vstelle like", value, "vstelle");
            return (Criteria) this;
        }

        public Criteria andVstelleNotLike(String value) {
            addCriterion("vstelle not like", value, "vstelle");
            return (Criteria) this;
        }

        public Criteria andVstelleIn(List<String> values) {
            addCriterion("vstelle in", values, "vstelle");
            return (Criteria) this;
        }

        public Criteria andVstelleNotIn(List<String> values) {
            addCriterion("vstelle not in", values, "vstelle");
            return (Criteria) this;
        }

        public Criteria andVstelleBetween(String value1, String value2) {
            addCriterion("vstelle between", value1, value2, "vstelle");
            return (Criteria) this;
        }

        public Criteria andVstelleNotBetween(String value1, String value2) {
            addCriterion("vstelle not between", value1, value2, "vstelle");
            return (Criteria) this;
        }

        public Criteria andYxatgIsNull() {
            addCriterion("yxatg is null");
            return (Criteria) this;
        }

        public Criteria andYxatgIsNotNull() {
            addCriterion("yxatg is not null");
            return (Criteria) this;
        }

        public Criteria andYxatgEqualTo(String value) {
            addCriterion("yxatg =", value, "yxatg");
            return (Criteria) this;
        }

        public Criteria andYxatgNotEqualTo(String value) {
            addCriterion("yxatg <>", value, "yxatg");
            return (Criteria) this;
        }

        public Criteria andYxatgGreaterThan(String value) {
            addCriterion("yxatg >", value, "yxatg");
            return (Criteria) this;
        }

        public Criteria andYxatgGreaterThanOrEqualTo(String value) {
            addCriterion("yxatg >=", value, "yxatg");
            return (Criteria) this;
        }

        public Criteria andYxatgLessThan(String value) {
            addCriterion("yxatg <", value, "yxatg");
            return (Criteria) this;
        }

        public Criteria andYxatgLessThanOrEqualTo(String value) {
            addCriterion("yxatg <=", value, "yxatg");
            return (Criteria) this;
        }

        public Criteria andYxatgLike(String value) {
            addCriterion("yxatg like", value, "yxatg");
            return (Criteria) this;
        }

        public Criteria andYxatgNotLike(String value) {
            addCriterion("yxatg not like", value, "yxatg");
            return (Criteria) this;
        }

        public Criteria andYxatgIn(List<String> values) {
            addCriterion("yxatg in", values, "yxatg");
            return (Criteria) this;
        }

        public Criteria andYxatgNotIn(List<String> values) {
            addCriterion("yxatg not in", values, "yxatg");
            return (Criteria) this;
        }

        public Criteria andYxatgBetween(String value1, String value2) {
            addCriterion("yxatg between", value1, value2, "yxatg");
            return (Criteria) this;
        }

        public Criteria andYxatgNotBetween(String value1, String value2) {
            addCriterion("yxatg not between", value1, value2, "yxatg");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ichgasequi
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ichgasequi
     *
     * @mbg.generated
     */
    public static class Criterion implements Serializable {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}