package com.ecej.po;

import java.io.Serializable;

/**
 * Created by wyx on 2017-10-09.
 * 
 * @author wyx
 * @title ichgasequi
 * @date 2017-10-09
 */
public class ICHGasEqui implements Serializable {
    /**
     * 
     * id 
     * id
     */
    private Integer id;

    /**
     * 
     * bauform 
     * bauform
     */
    private String bauform;

    /**
     * 
     * bauklas 
     * bauklas
     */
    private String bauklas;

    /**
     * 
     * eartx 
     * eartx
     */
    private String eartx;

    /**
     * 
     * eqart 
     * eqart
     */
    private String eqart;

    /**
     * 
     * equnr 
     * equnr
     */
    private String equnr;

    /**
     * 
     * estat 
     * estat
     */
    private String estat;

    /**
     * 
     * estxt 
     * estxt
     */
    private String estxt;

    /**
     * 
     * gwldt 
     * gwldt
     */
    private String gwldt;

    /**
     * 
     * gwlen 
     * gwlen
     */
    private String gwlen;

    /**
     * 
     * herst 
     * herst
     */
    private String herst;

    /**
     * 
     * opeEq 
     * ope_eq
     */
    private String opeEq;

    /**
     * 
     * planId 
     * plan_id
     */
    private Integer planId;

    /**
     * 
     * serge 
     * serge
     */
    private String serge;

    /**
     * 
     * typbz 
     * typbz
     */
    private String typbz;

    /**
     * 
     * uploadFlag 
     * upload_flag
     */
    private String uploadFlag;

    /**
     * 
     * vstelle 
     * vstelle
     */
    private String vstelle;

    /**
     * 
     * yxatg 
     * yxatg
     */
    private String yxatg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ichgasequi
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichgasequi.id
     *
     * @return the value of ichgasequi.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichgasequi.id
     *
     * @param id the value for ichgasequi.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichgasequi.bauform
     *
     * @return the value of ichgasequi.bauform
     *
     * @mbg.generated
     */
    public String getBauform() {
        return bauform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichgasequi.bauform
     *
     * @param bauform the value for ichgasequi.bauform
     *
     * @mbg.generated
     */
    public void setBauform(String bauform) {
        this.bauform = bauform == null ? null : bauform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichgasequi.bauklas
     *
     * @return the value of ichgasequi.bauklas
     *
     * @mbg.generated
     */
    public String getBauklas() {
        return bauklas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichgasequi.bauklas
     *
     * @param bauklas the value for ichgasequi.bauklas
     *
     * @mbg.generated
     */
    public void setBauklas(String bauklas) {
        this.bauklas = bauklas == null ? null : bauklas.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichgasequi.eartx
     *
     * @return the value of ichgasequi.eartx
     *
     * @mbg.generated
     */
    public String getEartx() {
        return eartx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichgasequi.eartx
     *
     * @param eartx the value for ichgasequi.eartx
     *
     * @mbg.generated
     */
    public void setEartx(String eartx) {
        this.eartx = eartx == null ? null : eartx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichgasequi.eqart
     *
     * @return the value of ichgasequi.eqart
     *
     * @mbg.generated
     */
    public String getEqart() {
        return eqart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichgasequi.eqart
     *
     * @param eqart the value for ichgasequi.eqart
     *
     * @mbg.generated
     */
    public void setEqart(String eqart) {
        this.eqart = eqart == null ? null : eqart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichgasequi.equnr
     *
     * @return the value of ichgasequi.equnr
     *
     * @mbg.generated
     */
    public String getEqunr() {
        return equnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichgasequi.equnr
     *
     * @param equnr the value for ichgasequi.equnr
     *
     * @mbg.generated
     */
    public void setEqunr(String equnr) {
        this.equnr = equnr == null ? null : equnr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichgasequi.estat
     *
     * @return the value of ichgasequi.estat
     *
     * @mbg.generated
     */
    public String getEstat() {
        return estat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichgasequi.estat
     *
     * @param estat the value for ichgasequi.estat
     *
     * @mbg.generated
     */
    public void setEstat(String estat) {
        this.estat = estat == null ? null : estat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichgasequi.estxt
     *
     * @return the value of ichgasequi.estxt
     *
     * @mbg.generated
     */
    public String getEstxt() {
        return estxt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichgasequi.estxt
     *
     * @param estxt the value for ichgasequi.estxt
     *
     * @mbg.generated
     */
    public void setEstxt(String estxt) {
        this.estxt = estxt == null ? null : estxt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichgasequi.gwldt
     *
     * @return the value of ichgasequi.gwldt
     *
     * @mbg.generated
     */
    public String getGwldt() {
        return gwldt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichgasequi.gwldt
     *
     * @param gwldt the value for ichgasequi.gwldt
     *
     * @mbg.generated
     */
    public void setGwldt(String gwldt) {
        this.gwldt = gwldt == null ? null : gwldt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichgasequi.gwlen
     *
     * @return the value of ichgasequi.gwlen
     *
     * @mbg.generated
     */
    public String getGwlen() {
        return gwlen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichgasequi.gwlen
     *
     * @param gwlen the value for ichgasequi.gwlen
     *
     * @mbg.generated
     */
    public void setGwlen(String gwlen) {
        this.gwlen = gwlen == null ? null : gwlen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichgasequi.herst
     *
     * @return the value of ichgasequi.herst
     *
     * @mbg.generated
     */
    public String getHerst() {
        return herst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichgasequi.herst
     *
     * @param herst the value for ichgasequi.herst
     *
     * @mbg.generated
     */
    public void setHerst(String herst) {
        this.herst = herst == null ? null : herst.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichgasequi.ope_eq
     *
     * @return the value of ichgasequi.ope_eq
     *
     * @mbg.generated
     */
    public String getOpeEq() {
        return opeEq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichgasequi.ope_eq
     *
     * @param opeEq the value for ichgasequi.ope_eq
     *
     * @mbg.generated
     */
    public void setOpeEq(String opeEq) {
        this.opeEq = opeEq == null ? null : opeEq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichgasequi.plan_id
     *
     * @return the value of ichgasequi.plan_id
     *
     * @mbg.generated
     */
    public Integer getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichgasequi.plan_id
     *
     * @param planId the value for ichgasequi.plan_id
     *
     * @mbg.generated
     */
    public void setPlanId(Integer planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichgasequi.serge
     *
     * @return the value of ichgasequi.serge
     *
     * @mbg.generated
     */
    public String getSerge() {
        return serge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichgasequi.serge
     *
     * @param serge the value for ichgasequi.serge
     *
     * @mbg.generated
     */
    public void setSerge(String serge) {
        this.serge = serge == null ? null : serge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichgasequi.typbz
     *
     * @return the value of ichgasequi.typbz
     *
     * @mbg.generated
     */
    public String getTypbz() {
        return typbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichgasequi.typbz
     *
     * @param typbz the value for ichgasequi.typbz
     *
     * @mbg.generated
     */
    public void setTypbz(String typbz) {
        this.typbz = typbz == null ? null : typbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichgasequi.upload_flag
     *
     * @return the value of ichgasequi.upload_flag
     *
     * @mbg.generated
     */
    public String getUploadFlag() {
        return uploadFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichgasequi.upload_flag
     *
     * @param uploadFlag the value for ichgasequi.upload_flag
     *
     * @mbg.generated
     */
    public void setUploadFlag(String uploadFlag) {
        this.uploadFlag = uploadFlag == null ? null : uploadFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichgasequi.vstelle
     *
     * @return the value of ichgasequi.vstelle
     *
     * @mbg.generated
     */
    public String getVstelle() {
        return vstelle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichgasequi.vstelle
     *
     * @param vstelle the value for ichgasequi.vstelle
     *
     * @mbg.generated
     */
    public void setVstelle(String vstelle) {
        this.vstelle = vstelle == null ? null : vstelle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichgasequi.yxatg
     *
     * @return the value of ichgasequi.yxatg
     *
     * @mbg.generated
     */
    public String getYxatg() {
        return yxatg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichgasequi.yxatg
     *
     * @param yxatg the value for ichgasequi.yxatg
     *
     * @mbg.generated
     */
    public void setYxatg(String yxatg) {
        this.yxatg = yxatg == null ? null : yxatg.trim();
    }
}