package com.ecej.po;

import java.io.Serializable;

/**
 * Created by wyx on 2017-10-09.
 * 
 * @author wyx
 * @title ichinstallinfo
 * @date 2017-10-09
 */
public class ICHInstallInfo implements Serializable {
    /**
     * 
     * id 
     * id
     */
    private Integer id;

    /**
     * 
     * ab 
     * ab
     */
    private String ab;

    /**
     * 
     * anlage 
     * anlage
     */
    private String anlage;

    /**
     * 
     * bauform 
     * bauform
     */
    private String bauform;

    /**
     * 
     * bauklas 
     * bauklas
     */
    private String bauklas;

    /**
     * 
     * branche 
     * branche
     */
    private String branche;

    /**
     * 
     * devloc 
     * devloc
     */
    private String devloc;

    /**
     * 
     * gwldt 
     * gwldt
     */
    private String gwldt;

    /**
     * 
     * gwlen 
     * gwlen
     */
    private String gwlen;

    /**
     * 
     * istype 
     * istype
     */
    private String istype;

    /**
     * 
     * loctxt 
     * loctxt
     */
    private String loctxt;

    /**
     * 
     * maktx 
     * maktx
     */
    private String maktx;

    /**
     * 
     * matnr 
     * matnr
     */
    private String matnr;

    /**
     * 
     * metyp 
     * metyp
     */
    private String metyp;

    /**
     * 
     * opeIns 
     * ope_ins
     */
    private String opeIns;

    /**
     * 
     * planId 
     * plan_id
     */
    private Integer planId;

    /**
     * 
     * platxt 
     * platxt
     */
    private String platxt;

    /**
     * 
     * serge 
     * serge
     */
    private String serge;

    /**
     * 
     * sernr 
     * sernr
     */
    private String sernr;

    /**
     * 
     * srqunr 
     * srqunr
     */
    private String srqunr;

    /**
     * 
     * text 
     * text
     */
    private String text;

    /**
     * 
     * uploadFlag 
     * upload_flag
     */
    private String uploadFlag;

    /**
     * 
     * vertrag 
     * vertrag
     */
    private String vertrag;

    /**
     * 
     * vrefer 
     * vrefer
     */
    private String vrefer;

    /**
     * 
     * vstelle 
     * vstelle
     */
    private String vstelle;

    /**
     * 
     * ycdir 
     * ycdir
     */
    private String ycdir;

    /**
     * 
     * yfhka 
     * yfhka
     */
    private String yfhka;

    /**
     * 
     * yliuf1 
     * yliuf1
     */
    private String yliuf1;

    /**
     * 
     * yplace 
     * yplace
     */
    private String yplace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ichinstallinfo
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichinstallinfo.id
     *
     * @return the value of ichinstallinfo.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichinstallinfo.id
     *
     * @param id the value for ichinstallinfo.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichinstallinfo.ab
     *
     * @return the value of ichinstallinfo.ab
     *
     * @mbg.generated
     */
    public String getAb() {
        return ab;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichinstallinfo.ab
     *
     * @param ab the value for ichinstallinfo.ab
     *
     * @mbg.generated
     */
    public void setAb(String ab) {
        this.ab = ab == null ? null : ab.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichinstallinfo.anlage
     *
     * @return the value of ichinstallinfo.anlage
     *
     * @mbg.generated
     */
    public String getAnlage() {
        return anlage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichinstallinfo.anlage
     *
     * @param anlage the value for ichinstallinfo.anlage
     *
     * @mbg.generated
     */
    public void setAnlage(String anlage) {
        this.anlage = anlage == null ? null : anlage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichinstallinfo.bauform
     *
     * @return the value of ichinstallinfo.bauform
     *
     * @mbg.generated
     */
    public String getBauform() {
        return bauform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichinstallinfo.bauform
     *
     * @param bauform the value for ichinstallinfo.bauform
     *
     * @mbg.generated
     */
    public void setBauform(String bauform) {
        this.bauform = bauform == null ? null : bauform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichinstallinfo.bauklas
     *
     * @return the value of ichinstallinfo.bauklas
     *
     * @mbg.generated
     */
    public String getBauklas() {
        return bauklas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichinstallinfo.bauklas
     *
     * @param bauklas the value for ichinstallinfo.bauklas
     *
     * @mbg.generated
     */
    public void setBauklas(String bauklas) {
        this.bauklas = bauklas == null ? null : bauklas.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichinstallinfo.branche
     *
     * @return the value of ichinstallinfo.branche
     *
     * @mbg.generated
     */
    public String getBranche() {
        return branche;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichinstallinfo.branche
     *
     * @param branche the value for ichinstallinfo.branche
     *
     * @mbg.generated
     */
    public void setBranche(String branche) {
        this.branche = branche == null ? null : branche.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichinstallinfo.devloc
     *
     * @return the value of ichinstallinfo.devloc
     *
     * @mbg.generated
     */
    public String getDevloc() {
        return devloc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichinstallinfo.devloc
     *
     * @param devloc the value for ichinstallinfo.devloc
     *
     * @mbg.generated
     */
    public void setDevloc(String devloc) {
        this.devloc = devloc == null ? null : devloc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichinstallinfo.gwldt
     *
     * @return the value of ichinstallinfo.gwldt
     *
     * @mbg.generated
     */
    public String getGwldt() {
        return gwldt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichinstallinfo.gwldt
     *
     * @param gwldt the value for ichinstallinfo.gwldt
     *
     * @mbg.generated
     */
    public void setGwldt(String gwldt) {
        this.gwldt = gwldt == null ? null : gwldt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichinstallinfo.gwlen
     *
     * @return the value of ichinstallinfo.gwlen
     *
     * @mbg.generated
     */
    public String getGwlen() {
        return gwlen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichinstallinfo.gwlen
     *
     * @param gwlen the value for ichinstallinfo.gwlen
     *
     * @mbg.generated
     */
    public void setGwlen(String gwlen) {
        this.gwlen = gwlen == null ? null : gwlen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichinstallinfo.istype
     *
     * @return the value of ichinstallinfo.istype
     *
     * @mbg.generated
     */
    public String getIstype() {
        return istype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichinstallinfo.istype
     *
     * @param istype the value for ichinstallinfo.istype
     *
     * @mbg.generated
     */
    public void setIstype(String istype) {
        this.istype = istype == null ? null : istype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichinstallinfo.loctxt
     *
     * @return the value of ichinstallinfo.loctxt
     *
     * @mbg.generated
     */
    public String getLoctxt() {
        return loctxt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichinstallinfo.loctxt
     *
     * @param loctxt the value for ichinstallinfo.loctxt
     *
     * @mbg.generated
     */
    public void setLoctxt(String loctxt) {
        this.loctxt = loctxt == null ? null : loctxt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichinstallinfo.maktx
     *
     * @return the value of ichinstallinfo.maktx
     *
     * @mbg.generated
     */
    public String getMaktx() {
        return maktx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichinstallinfo.maktx
     *
     * @param maktx the value for ichinstallinfo.maktx
     *
     * @mbg.generated
     */
    public void setMaktx(String maktx) {
        this.maktx = maktx == null ? null : maktx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichinstallinfo.matnr
     *
     * @return the value of ichinstallinfo.matnr
     *
     * @mbg.generated
     */
    public String getMatnr() {
        return matnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichinstallinfo.matnr
     *
     * @param matnr the value for ichinstallinfo.matnr
     *
     * @mbg.generated
     */
    public void setMatnr(String matnr) {
        this.matnr = matnr == null ? null : matnr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichinstallinfo.metyp
     *
     * @return the value of ichinstallinfo.metyp
     *
     * @mbg.generated
     */
    public String getMetyp() {
        return metyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichinstallinfo.metyp
     *
     * @param metyp the value for ichinstallinfo.metyp
     *
     * @mbg.generated
     */
    public void setMetyp(String metyp) {
        this.metyp = metyp == null ? null : metyp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichinstallinfo.ope_ins
     *
     * @return the value of ichinstallinfo.ope_ins
     *
     * @mbg.generated
     */
    public String getOpeIns() {
        return opeIns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichinstallinfo.ope_ins
     *
     * @param opeIns the value for ichinstallinfo.ope_ins
     *
     * @mbg.generated
     */
    public void setOpeIns(String opeIns) {
        this.opeIns = opeIns == null ? null : opeIns.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichinstallinfo.plan_id
     *
     * @return the value of ichinstallinfo.plan_id
     *
     * @mbg.generated
     */
    public Integer getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichinstallinfo.plan_id
     *
     * @param planId the value for ichinstallinfo.plan_id
     *
     * @mbg.generated
     */
    public void setPlanId(Integer planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichinstallinfo.platxt
     *
     * @return the value of ichinstallinfo.platxt
     *
     * @mbg.generated
     */
    public String getPlatxt() {
        return platxt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichinstallinfo.platxt
     *
     * @param platxt the value for ichinstallinfo.platxt
     *
     * @mbg.generated
     */
    public void setPlatxt(String platxt) {
        this.platxt = platxt == null ? null : platxt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichinstallinfo.serge
     *
     * @return the value of ichinstallinfo.serge
     *
     * @mbg.generated
     */
    public String getSerge() {
        return serge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichinstallinfo.serge
     *
     * @param serge the value for ichinstallinfo.serge
     *
     * @mbg.generated
     */
    public void setSerge(String serge) {
        this.serge = serge == null ? null : serge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichinstallinfo.sernr
     *
     * @return the value of ichinstallinfo.sernr
     *
     * @mbg.generated
     */
    public String getSernr() {
        return sernr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichinstallinfo.sernr
     *
     * @param sernr the value for ichinstallinfo.sernr
     *
     * @mbg.generated
     */
    public void setSernr(String sernr) {
        this.sernr = sernr == null ? null : sernr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichinstallinfo.srqunr
     *
     * @return the value of ichinstallinfo.srqunr
     *
     * @mbg.generated
     */
    public String getSrqunr() {
        return srqunr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichinstallinfo.srqunr
     *
     * @param srqunr the value for ichinstallinfo.srqunr
     *
     * @mbg.generated
     */
    public void setSrqunr(String srqunr) {
        this.srqunr = srqunr == null ? null : srqunr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichinstallinfo.text
     *
     * @return the value of ichinstallinfo.text
     *
     * @mbg.generated
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichinstallinfo.text
     *
     * @param text the value for ichinstallinfo.text
     *
     * @mbg.generated
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichinstallinfo.upload_flag
     *
     * @return the value of ichinstallinfo.upload_flag
     *
     * @mbg.generated
     */
    public String getUploadFlag() {
        return uploadFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichinstallinfo.upload_flag
     *
     * @param uploadFlag the value for ichinstallinfo.upload_flag
     *
     * @mbg.generated
     */
    public void setUploadFlag(String uploadFlag) {
        this.uploadFlag = uploadFlag == null ? null : uploadFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichinstallinfo.vertrag
     *
     * @return the value of ichinstallinfo.vertrag
     *
     * @mbg.generated
     */
    public String getVertrag() {
        return vertrag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichinstallinfo.vertrag
     *
     * @param vertrag the value for ichinstallinfo.vertrag
     *
     * @mbg.generated
     */
    public void setVertrag(String vertrag) {
        this.vertrag = vertrag == null ? null : vertrag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichinstallinfo.vrefer
     *
     * @return the value of ichinstallinfo.vrefer
     *
     * @mbg.generated
     */
    public String getVrefer() {
        return vrefer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichinstallinfo.vrefer
     *
     * @param vrefer the value for ichinstallinfo.vrefer
     *
     * @mbg.generated
     */
    public void setVrefer(String vrefer) {
        this.vrefer = vrefer == null ? null : vrefer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichinstallinfo.vstelle
     *
     * @return the value of ichinstallinfo.vstelle
     *
     * @mbg.generated
     */
    public String getVstelle() {
        return vstelle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichinstallinfo.vstelle
     *
     * @param vstelle the value for ichinstallinfo.vstelle
     *
     * @mbg.generated
     */
    public void setVstelle(String vstelle) {
        this.vstelle = vstelle == null ? null : vstelle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichinstallinfo.ycdir
     *
     * @return the value of ichinstallinfo.ycdir
     *
     * @mbg.generated
     */
    public String getYcdir() {
        return ycdir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichinstallinfo.ycdir
     *
     * @param ycdir the value for ichinstallinfo.ycdir
     *
     * @mbg.generated
     */
    public void setYcdir(String ycdir) {
        this.ycdir = ycdir == null ? null : ycdir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichinstallinfo.yfhka
     *
     * @return the value of ichinstallinfo.yfhka
     *
     * @mbg.generated
     */
    public String getYfhka() {
        return yfhka;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichinstallinfo.yfhka
     *
     * @param yfhka the value for ichinstallinfo.yfhka
     *
     * @mbg.generated
     */
    public void setYfhka(String yfhka) {
        this.yfhka = yfhka == null ? null : yfhka.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichinstallinfo.yliuf1
     *
     * @return the value of ichinstallinfo.yliuf1
     *
     * @mbg.generated
     */
    public String getYliuf1() {
        return yliuf1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichinstallinfo.yliuf1
     *
     * @param yliuf1 the value for ichinstallinfo.yliuf1
     *
     * @mbg.generated
     */
    public void setYliuf1(String yliuf1) {
        this.yliuf1 = yliuf1 == null ? null : yliuf1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichinstallinfo.yplace
     *
     * @return the value of ichinstallinfo.yplace
     *
     * @mbg.generated
     */
    public String getYplace() {
        return yplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichinstallinfo.yplace
     *
     * @param yplace the value for ichinstallinfo.yplace
     *
     * @mbg.generated
     */
    public void setYplace(String yplace) {
        this.yplace = yplace == null ? null : yplace.trim();
    }
}