package com.ecej.po;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class ICHInstallInfoExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ichinstallinfo
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ichinstallinfo
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ichinstallinfo
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ichinstallinfo
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichinstallinfo
     *
     * @mbg.generated
     */
    public ICHInstallInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichinstallinfo
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichinstallinfo
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichinstallinfo
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichinstallinfo
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichinstallinfo
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichinstallinfo
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichinstallinfo
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichinstallinfo
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichinstallinfo
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichinstallinfo
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ichinstallinfo
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria implements Serializable {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAbIsNull() {
            addCriterion("ab is null");
            return (Criteria) this;
        }

        public Criteria andAbIsNotNull() {
            addCriterion("ab is not null");
            return (Criteria) this;
        }

        public Criteria andAbEqualTo(String value) {
            addCriterion("ab =", value, "ab");
            return (Criteria) this;
        }

        public Criteria andAbNotEqualTo(String value) {
            addCriterion("ab <>", value, "ab");
            return (Criteria) this;
        }

        public Criteria andAbGreaterThan(String value) {
            addCriterion("ab >", value, "ab");
            return (Criteria) this;
        }

        public Criteria andAbGreaterThanOrEqualTo(String value) {
            addCriterion("ab >=", value, "ab");
            return (Criteria) this;
        }

        public Criteria andAbLessThan(String value) {
            addCriterion("ab <", value, "ab");
            return (Criteria) this;
        }

        public Criteria andAbLessThanOrEqualTo(String value) {
            addCriterion("ab <=", value, "ab");
            return (Criteria) this;
        }

        public Criteria andAbLike(String value) {
            addCriterion("ab like", value, "ab");
            return (Criteria) this;
        }

        public Criteria andAbNotLike(String value) {
            addCriterion("ab not like", value, "ab");
            return (Criteria) this;
        }

        public Criteria andAbIn(List<String> values) {
            addCriterion("ab in", values, "ab");
            return (Criteria) this;
        }

        public Criteria andAbNotIn(List<String> values) {
            addCriterion("ab not in", values, "ab");
            return (Criteria) this;
        }

        public Criteria andAbBetween(String value1, String value2) {
            addCriterion("ab between", value1, value2, "ab");
            return (Criteria) this;
        }

        public Criteria andAbNotBetween(String value1, String value2) {
            addCriterion("ab not between", value1, value2, "ab");
            return (Criteria) this;
        }

        public Criteria andAnlageIsNull() {
            addCriterion("anlage is null");
            return (Criteria) this;
        }

        public Criteria andAnlageIsNotNull() {
            addCriterion("anlage is not null");
            return (Criteria) this;
        }

        public Criteria andAnlageEqualTo(String value) {
            addCriterion("anlage =", value, "anlage");
            return (Criteria) this;
        }

        public Criteria andAnlageNotEqualTo(String value) {
            addCriterion("anlage <>", value, "anlage");
            return (Criteria) this;
        }

        public Criteria andAnlageGreaterThan(String value) {
            addCriterion("anlage >", value, "anlage");
            return (Criteria) this;
        }

        public Criteria andAnlageGreaterThanOrEqualTo(String value) {
            addCriterion("anlage >=", value, "anlage");
            return (Criteria) this;
        }

        public Criteria andAnlageLessThan(String value) {
            addCriterion("anlage <", value, "anlage");
            return (Criteria) this;
        }

        public Criteria andAnlageLessThanOrEqualTo(String value) {
            addCriterion("anlage <=", value, "anlage");
            return (Criteria) this;
        }

        public Criteria andAnlageLike(String value) {
            addCriterion("anlage like", value, "anlage");
            return (Criteria) this;
        }

        public Criteria andAnlageNotLike(String value) {
            addCriterion("anlage not like", value, "anlage");
            return (Criteria) this;
        }

        public Criteria andAnlageIn(List<String> values) {
            addCriterion("anlage in", values, "anlage");
            return (Criteria) this;
        }

        public Criteria andAnlageNotIn(List<String> values) {
            addCriterion("anlage not in", values, "anlage");
            return (Criteria) this;
        }

        public Criteria andAnlageBetween(String value1, String value2) {
            addCriterion("anlage between", value1, value2, "anlage");
            return (Criteria) this;
        }

        public Criteria andAnlageNotBetween(String value1, String value2) {
            addCriterion("anlage not between", value1, value2, "anlage");
            return (Criteria) this;
        }

        public Criteria andBauformIsNull() {
            addCriterion("bauform is null");
            return (Criteria) this;
        }

        public Criteria andBauformIsNotNull() {
            addCriterion("bauform is not null");
            return (Criteria) this;
        }

        public Criteria andBauformEqualTo(String value) {
            addCriterion("bauform =", value, "bauform");
            return (Criteria) this;
        }

        public Criteria andBauformNotEqualTo(String value) {
            addCriterion("bauform <>", value, "bauform");
            return (Criteria) this;
        }

        public Criteria andBauformGreaterThan(String value) {
            addCriterion("bauform >", value, "bauform");
            return (Criteria) this;
        }

        public Criteria andBauformGreaterThanOrEqualTo(String value) {
            addCriterion("bauform >=", value, "bauform");
            return (Criteria) this;
        }

        public Criteria andBauformLessThan(String value) {
            addCriterion("bauform <", value, "bauform");
            return (Criteria) this;
        }

        public Criteria andBauformLessThanOrEqualTo(String value) {
            addCriterion("bauform <=", value, "bauform");
            return (Criteria) this;
        }

        public Criteria andBauformLike(String value) {
            addCriterion("bauform like", value, "bauform");
            return (Criteria) this;
        }

        public Criteria andBauformNotLike(String value) {
            addCriterion("bauform not like", value, "bauform");
            return (Criteria) this;
        }

        public Criteria andBauformIn(List<String> values) {
            addCriterion("bauform in", values, "bauform");
            return (Criteria) this;
        }

        public Criteria andBauformNotIn(List<String> values) {
            addCriterion("bauform not in", values, "bauform");
            return (Criteria) this;
        }

        public Criteria andBauformBetween(String value1, String value2) {
            addCriterion("bauform between", value1, value2, "bauform");
            return (Criteria) this;
        }

        public Criteria andBauformNotBetween(String value1, String value2) {
            addCriterion("bauform not between", value1, value2, "bauform");
            return (Criteria) this;
        }

        public Criteria andBauklasIsNull() {
            addCriterion("bauklas is null");
            return (Criteria) this;
        }

        public Criteria andBauklasIsNotNull() {
            addCriterion("bauklas is not null");
            return (Criteria) this;
        }

        public Criteria andBauklasEqualTo(String value) {
            addCriterion("bauklas =", value, "bauklas");
            return (Criteria) this;
        }

        public Criteria andBauklasNotEqualTo(String value) {
            addCriterion("bauklas <>", value, "bauklas");
            return (Criteria) this;
        }

        public Criteria andBauklasGreaterThan(String value) {
            addCriterion("bauklas >", value, "bauklas");
            return (Criteria) this;
        }

        public Criteria andBauklasGreaterThanOrEqualTo(String value) {
            addCriterion("bauklas >=", value, "bauklas");
            return (Criteria) this;
        }

        public Criteria andBauklasLessThan(String value) {
            addCriterion("bauklas <", value, "bauklas");
            return (Criteria) this;
        }

        public Criteria andBauklasLessThanOrEqualTo(String value) {
            addCriterion("bauklas <=", value, "bauklas");
            return (Criteria) this;
        }

        public Criteria andBauklasLike(String value) {
            addCriterion("bauklas like", value, "bauklas");
            return (Criteria) this;
        }

        public Criteria andBauklasNotLike(String value) {
            addCriterion("bauklas not like", value, "bauklas");
            return (Criteria) this;
        }

        public Criteria andBauklasIn(List<String> values) {
            addCriterion("bauklas in", values, "bauklas");
            return (Criteria) this;
        }

        public Criteria andBauklasNotIn(List<String> values) {
            addCriterion("bauklas not in", values, "bauklas");
            return (Criteria) this;
        }

        public Criteria andBauklasBetween(String value1, String value2) {
            addCriterion("bauklas between", value1, value2, "bauklas");
            return (Criteria) this;
        }

        public Criteria andBauklasNotBetween(String value1, String value2) {
            addCriterion("bauklas not between", value1, value2, "bauklas");
            return (Criteria) this;
        }

        public Criteria andBrancheIsNull() {
            addCriterion("branche is null");
            return (Criteria) this;
        }

        public Criteria andBrancheIsNotNull() {
            addCriterion("branche is not null");
            return (Criteria) this;
        }

        public Criteria andBrancheEqualTo(String value) {
            addCriterion("branche =", value, "branche");
            return (Criteria) this;
        }

        public Criteria andBrancheNotEqualTo(String value) {
            addCriterion("branche <>", value, "branche");
            return (Criteria) this;
        }

        public Criteria andBrancheGreaterThan(String value) {
            addCriterion("branche >", value, "branche");
            return (Criteria) this;
        }

        public Criteria andBrancheGreaterThanOrEqualTo(String value) {
            addCriterion("branche >=", value, "branche");
            return (Criteria) this;
        }

        public Criteria andBrancheLessThan(String value) {
            addCriterion("branche <", value, "branche");
            return (Criteria) this;
        }

        public Criteria andBrancheLessThanOrEqualTo(String value) {
            addCriterion("branche <=", value, "branche");
            return (Criteria) this;
        }

        public Criteria andBrancheLike(String value) {
            addCriterion("branche like", value, "branche");
            return (Criteria) this;
        }

        public Criteria andBrancheNotLike(String value) {
            addCriterion("branche not like", value, "branche");
            return (Criteria) this;
        }

        public Criteria andBrancheIn(List<String> values) {
            addCriterion("branche in", values, "branche");
            return (Criteria) this;
        }

        public Criteria andBrancheNotIn(List<String> values) {
            addCriterion("branche not in", values, "branche");
            return (Criteria) this;
        }

        public Criteria andBrancheBetween(String value1, String value2) {
            addCriterion("branche between", value1, value2, "branche");
            return (Criteria) this;
        }

        public Criteria andBrancheNotBetween(String value1, String value2) {
            addCriterion("branche not between", value1, value2, "branche");
            return (Criteria) this;
        }

        public Criteria andDevlocIsNull() {
            addCriterion("devloc is null");
            return (Criteria) this;
        }

        public Criteria andDevlocIsNotNull() {
            addCriterion("devloc is not null");
            return (Criteria) this;
        }

        public Criteria andDevlocEqualTo(String value) {
            addCriterion("devloc =", value, "devloc");
            return (Criteria) this;
        }

        public Criteria andDevlocNotEqualTo(String value) {
            addCriterion("devloc <>", value, "devloc");
            return (Criteria) this;
        }

        public Criteria andDevlocGreaterThan(String value) {
            addCriterion("devloc >", value, "devloc");
            return (Criteria) this;
        }

        public Criteria andDevlocGreaterThanOrEqualTo(String value) {
            addCriterion("devloc >=", value, "devloc");
            return (Criteria) this;
        }

        public Criteria andDevlocLessThan(String value) {
            addCriterion("devloc <", value, "devloc");
            return (Criteria) this;
        }

        public Criteria andDevlocLessThanOrEqualTo(String value) {
            addCriterion("devloc <=", value, "devloc");
            return (Criteria) this;
        }

        public Criteria andDevlocLike(String value) {
            addCriterion("devloc like", value, "devloc");
            return (Criteria) this;
        }

        public Criteria andDevlocNotLike(String value) {
            addCriterion("devloc not like", value, "devloc");
            return (Criteria) this;
        }

        public Criteria andDevlocIn(List<String> values) {
            addCriterion("devloc in", values, "devloc");
            return (Criteria) this;
        }

        public Criteria andDevlocNotIn(List<String> values) {
            addCriterion("devloc not in", values, "devloc");
            return (Criteria) this;
        }

        public Criteria andDevlocBetween(String value1, String value2) {
            addCriterion("devloc between", value1, value2, "devloc");
            return (Criteria) this;
        }

        public Criteria andDevlocNotBetween(String value1, String value2) {
            addCriterion("devloc not between", value1, value2, "devloc");
            return (Criteria) this;
        }

        public Criteria andGwldtIsNull() {
            addCriterion("gwldt is null");
            return (Criteria) this;
        }

        public Criteria andGwldtIsNotNull() {
            addCriterion("gwldt is not null");
            return (Criteria) this;
        }

        public Criteria andGwldtEqualTo(String value) {
            addCriterion("gwldt =", value, "gwldt");
            return (Criteria) this;
        }

        public Criteria andGwldtNotEqualTo(String value) {
            addCriterion("gwldt <>", value, "gwldt");
            return (Criteria) this;
        }

        public Criteria andGwldtGreaterThan(String value) {
            addCriterion("gwldt >", value, "gwldt");
            return (Criteria) this;
        }

        public Criteria andGwldtGreaterThanOrEqualTo(String value) {
            addCriterion("gwldt >=", value, "gwldt");
            return (Criteria) this;
        }

        public Criteria andGwldtLessThan(String value) {
            addCriterion("gwldt <", value, "gwldt");
            return (Criteria) this;
        }

        public Criteria andGwldtLessThanOrEqualTo(String value) {
            addCriterion("gwldt <=", value, "gwldt");
            return (Criteria) this;
        }

        public Criteria andGwldtLike(String value) {
            addCriterion("gwldt like", value, "gwldt");
            return (Criteria) this;
        }

        public Criteria andGwldtNotLike(String value) {
            addCriterion("gwldt not like", value, "gwldt");
            return (Criteria) this;
        }

        public Criteria andGwldtIn(List<String> values) {
            addCriterion("gwldt in", values, "gwldt");
            return (Criteria) this;
        }

        public Criteria andGwldtNotIn(List<String> values) {
            addCriterion("gwldt not in", values, "gwldt");
            return (Criteria) this;
        }

        public Criteria andGwldtBetween(String value1, String value2) {
            addCriterion("gwldt between", value1, value2, "gwldt");
            return (Criteria) this;
        }

        public Criteria andGwldtNotBetween(String value1, String value2) {
            addCriterion("gwldt not between", value1, value2, "gwldt");
            return (Criteria) this;
        }

        public Criteria andGwlenIsNull() {
            addCriterion("gwlen is null");
            return (Criteria) this;
        }

        public Criteria andGwlenIsNotNull() {
            addCriterion("gwlen is not null");
            return (Criteria) this;
        }

        public Criteria andGwlenEqualTo(String value) {
            addCriterion("gwlen =", value, "gwlen");
            return (Criteria) this;
        }

        public Criteria andGwlenNotEqualTo(String value) {
            addCriterion("gwlen <>", value, "gwlen");
            return (Criteria) this;
        }

        public Criteria andGwlenGreaterThan(String value) {
            addCriterion("gwlen >", value, "gwlen");
            return (Criteria) this;
        }

        public Criteria andGwlenGreaterThanOrEqualTo(String value) {
            addCriterion("gwlen >=", value, "gwlen");
            return (Criteria) this;
        }

        public Criteria andGwlenLessThan(String value) {
            addCriterion("gwlen <", value, "gwlen");
            return (Criteria) this;
        }

        public Criteria andGwlenLessThanOrEqualTo(String value) {
            addCriterion("gwlen <=", value, "gwlen");
            return (Criteria) this;
        }

        public Criteria andGwlenLike(String value) {
            addCriterion("gwlen like", value, "gwlen");
            return (Criteria) this;
        }

        public Criteria andGwlenNotLike(String value) {
            addCriterion("gwlen not like", value, "gwlen");
            return (Criteria) this;
        }

        public Criteria andGwlenIn(List<String> values) {
            addCriterion("gwlen in", values, "gwlen");
            return (Criteria) this;
        }

        public Criteria andGwlenNotIn(List<String> values) {
            addCriterion("gwlen not in", values, "gwlen");
            return (Criteria) this;
        }

        public Criteria andGwlenBetween(String value1, String value2) {
            addCriterion("gwlen between", value1, value2, "gwlen");
            return (Criteria) this;
        }

        public Criteria andGwlenNotBetween(String value1, String value2) {
            addCriterion("gwlen not between", value1, value2, "gwlen");
            return (Criteria) this;
        }

        public Criteria andIstypeIsNull() {
            addCriterion("istype is null");
            return (Criteria) this;
        }

        public Criteria andIstypeIsNotNull() {
            addCriterion("istype is not null");
            return (Criteria) this;
        }

        public Criteria andIstypeEqualTo(String value) {
            addCriterion("istype =", value, "istype");
            return (Criteria) this;
        }

        public Criteria andIstypeNotEqualTo(String value) {
            addCriterion("istype <>", value, "istype");
            return (Criteria) this;
        }

        public Criteria andIstypeGreaterThan(String value) {
            addCriterion("istype >", value, "istype");
            return (Criteria) this;
        }

        public Criteria andIstypeGreaterThanOrEqualTo(String value) {
            addCriterion("istype >=", value, "istype");
            return (Criteria) this;
        }

        public Criteria andIstypeLessThan(String value) {
            addCriterion("istype <", value, "istype");
            return (Criteria) this;
        }

        public Criteria andIstypeLessThanOrEqualTo(String value) {
            addCriterion("istype <=", value, "istype");
            return (Criteria) this;
        }

        public Criteria andIstypeLike(String value) {
            addCriterion("istype like", value, "istype");
            return (Criteria) this;
        }

        public Criteria andIstypeNotLike(String value) {
            addCriterion("istype not like", value, "istype");
            return (Criteria) this;
        }

        public Criteria andIstypeIn(List<String> values) {
            addCriterion("istype in", values, "istype");
            return (Criteria) this;
        }

        public Criteria andIstypeNotIn(List<String> values) {
            addCriterion("istype not in", values, "istype");
            return (Criteria) this;
        }

        public Criteria andIstypeBetween(String value1, String value2) {
            addCriterion("istype between", value1, value2, "istype");
            return (Criteria) this;
        }

        public Criteria andIstypeNotBetween(String value1, String value2) {
            addCriterion("istype not between", value1, value2, "istype");
            return (Criteria) this;
        }

        public Criteria andLoctxtIsNull() {
            addCriterion("loctxt is null");
            return (Criteria) this;
        }

        public Criteria andLoctxtIsNotNull() {
            addCriterion("loctxt is not null");
            return (Criteria) this;
        }

        public Criteria andLoctxtEqualTo(String value) {
            addCriterion("loctxt =", value, "loctxt");
            return (Criteria) this;
        }

        public Criteria andLoctxtNotEqualTo(String value) {
            addCriterion("loctxt <>", value, "loctxt");
            return (Criteria) this;
        }

        public Criteria andLoctxtGreaterThan(String value) {
            addCriterion("loctxt >", value, "loctxt");
            return (Criteria) this;
        }

        public Criteria andLoctxtGreaterThanOrEqualTo(String value) {
            addCriterion("loctxt >=", value, "loctxt");
            return (Criteria) this;
        }

        public Criteria andLoctxtLessThan(String value) {
            addCriterion("loctxt <", value, "loctxt");
            return (Criteria) this;
        }

        public Criteria andLoctxtLessThanOrEqualTo(String value) {
            addCriterion("loctxt <=", value, "loctxt");
            return (Criteria) this;
        }

        public Criteria andLoctxtLike(String value) {
            addCriterion("loctxt like", value, "loctxt");
            return (Criteria) this;
        }

        public Criteria andLoctxtNotLike(String value) {
            addCriterion("loctxt not like", value, "loctxt");
            return (Criteria) this;
        }

        public Criteria andLoctxtIn(List<String> values) {
            addCriterion("loctxt in", values, "loctxt");
            return (Criteria) this;
        }

        public Criteria andLoctxtNotIn(List<String> values) {
            addCriterion("loctxt not in", values, "loctxt");
            return (Criteria) this;
        }

        public Criteria andLoctxtBetween(String value1, String value2) {
            addCriterion("loctxt between", value1, value2, "loctxt");
            return (Criteria) this;
        }

        public Criteria andLoctxtNotBetween(String value1, String value2) {
            addCriterion("loctxt not between", value1, value2, "loctxt");
            return (Criteria) this;
        }

        public Criteria andMaktxIsNull() {
            addCriterion("maktx is null");
            return (Criteria) this;
        }

        public Criteria andMaktxIsNotNull() {
            addCriterion("maktx is not null");
            return (Criteria) this;
        }

        public Criteria andMaktxEqualTo(String value) {
            addCriterion("maktx =", value, "maktx");
            return (Criteria) this;
        }

        public Criteria andMaktxNotEqualTo(String value) {
            addCriterion("maktx <>", value, "maktx");
            return (Criteria) this;
        }

        public Criteria andMaktxGreaterThan(String value) {
            addCriterion("maktx >", value, "maktx");
            return (Criteria) this;
        }

        public Criteria andMaktxGreaterThanOrEqualTo(String value) {
            addCriterion("maktx >=", value, "maktx");
            return (Criteria) this;
        }

        public Criteria andMaktxLessThan(String value) {
            addCriterion("maktx <", value, "maktx");
            return (Criteria) this;
        }

        public Criteria andMaktxLessThanOrEqualTo(String value) {
            addCriterion("maktx <=", value, "maktx");
            return (Criteria) this;
        }

        public Criteria andMaktxLike(String value) {
            addCriterion("maktx like", value, "maktx");
            return (Criteria) this;
        }

        public Criteria andMaktxNotLike(String value) {
            addCriterion("maktx not like", value, "maktx");
            return (Criteria) this;
        }

        public Criteria andMaktxIn(List<String> values) {
            addCriterion("maktx in", values, "maktx");
            return (Criteria) this;
        }

        public Criteria andMaktxNotIn(List<String> values) {
            addCriterion("maktx not in", values, "maktx");
            return (Criteria) this;
        }

        public Criteria andMaktxBetween(String value1, String value2) {
            addCriterion("maktx between", value1, value2, "maktx");
            return (Criteria) this;
        }

        public Criteria andMaktxNotBetween(String value1, String value2) {
            addCriterion("maktx not between", value1, value2, "maktx");
            return (Criteria) this;
        }

        public Criteria andMatnrIsNull() {
            addCriterion("matnr is null");
            return (Criteria) this;
        }

        public Criteria andMatnrIsNotNull() {
            addCriterion("matnr is not null");
            return (Criteria) this;
        }

        public Criteria andMatnrEqualTo(String value) {
            addCriterion("matnr =", value, "matnr");
            return (Criteria) this;
        }

        public Criteria andMatnrNotEqualTo(String value) {
            addCriterion("matnr <>", value, "matnr");
            return (Criteria) this;
        }

        public Criteria andMatnrGreaterThan(String value) {
            addCriterion("matnr >", value, "matnr");
            return (Criteria) this;
        }

        public Criteria andMatnrGreaterThanOrEqualTo(String value) {
            addCriterion("matnr >=", value, "matnr");
            return (Criteria) this;
        }

        public Criteria andMatnrLessThan(String value) {
            addCriterion("matnr <", value, "matnr");
            return (Criteria) this;
        }

        public Criteria andMatnrLessThanOrEqualTo(String value) {
            addCriterion("matnr <=", value, "matnr");
            return (Criteria) this;
        }

        public Criteria andMatnrLike(String value) {
            addCriterion("matnr like", value, "matnr");
            return (Criteria) this;
        }

        public Criteria andMatnrNotLike(String value) {
            addCriterion("matnr not like", value, "matnr");
            return (Criteria) this;
        }

        public Criteria andMatnrIn(List<String> values) {
            addCriterion("matnr in", values, "matnr");
            return (Criteria) this;
        }

        public Criteria andMatnrNotIn(List<String> values) {
            addCriterion("matnr not in", values, "matnr");
            return (Criteria) this;
        }

        public Criteria andMatnrBetween(String value1, String value2) {
            addCriterion("matnr between", value1, value2, "matnr");
            return (Criteria) this;
        }

        public Criteria andMatnrNotBetween(String value1, String value2) {
            addCriterion("matnr not between", value1, value2, "matnr");
            return (Criteria) this;
        }

        public Criteria andMetypIsNull() {
            addCriterion("metyp is null");
            return (Criteria) this;
        }

        public Criteria andMetypIsNotNull() {
            addCriterion("metyp is not null");
            return (Criteria) this;
        }

        public Criteria andMetypEqualTo(String value) {
            addCriterion("metyp =", value, "metyp");
            return (Criteria) this;
        }

        public Criteria andMetypNotEqualTo(String value) {
            addCriterion("metyp <>", value, "metyp");
            return (Criteria) this;
        }

        public Criteria andMetypGreaterThan(String value) {
            addCriterion("metyp >", value, "metyp");
            return (Criteria) this;
        }

        public Criteria andMetypGreaterThanOrEqualTo(String value) {
            addCriterion("metyp >=", value, "metyp");
            return (Criteria) this;
        }

        public Criteria andMetypLessThan(String value) {
            addCriterion("metyp <", value, "metyp");
            return (Criteria) this;
        }

        public Criteria andMetypLessThanOrEqualTo(String value) {
            addCriterion("metyp <=", value, "metyp");
            return (Criteria) this;
        }

        public Criteria andMetypLike(String value) {
            addCriterion("metyp like", value, "metyp");
            return (Criteria) this;
        }

        public Criteria andMetypNotLike(String value) {
            addCriterion("metyp not like", value, "metyp");
            return (Criteria) this;
        }

        public Criteria andMetypIn(List<String> values) {
            addCriterion("metyp in", values, "metyp");
            return (Criteria) this;
        }

        public Criteria andMetypNotIn(List<String> values) {
            addCriterion("metyp not in", values, "metyp");
            return (Criteria) this;
        }

        public Criteria andMetypBetween(String value1, String value2) {
            addCriterion("metyp between", value1, value2, "metyp");
            return (Criteria) this;
        }

        public Criteria andMetypNotBetween(String value1, String value2) {
            addCriterion("metyp not between", value1, value2, "metyp");
            return (Criteria) this;
        }

        public Criteria andOpeInsIsNull() {
            addCriterion("ope_ins is null");
            return (Criteria) this;
        }

        public Criteria andOpeInsIsNotNull() {
            addCriterion("ope_ins is not null");
            return (Criteria) this;
        }

        public Criteria andOpeInsEqualTo(String value) {
            addCriterion("ope_ins =", value, "opeIns");
            return (Criteria) this;
        }

        public Criteria andOpeInsNotEqualTo(String value) {
            addCriterion("ope_ins <>", value, "opeIns");
            return (Criteria) this;
        }

        public Criteria andOpeInsGreaterThan(String value) {
            addCriterion("ope_ins >", value, "opeIns");
            return (Criteria) this;
        }

        public Criteria andOpeInsGreaterThanOrEqualTo(String value) {
            addCriterion("ope_ins >=", value, "opeIns");
            return (Criteria) this;
        }

        public Criteria andOpeInsLessThan(String value) {
            addCriterion("ope_ins <", value, "opeIns");
            return (Criteria) this;
        }

        public Criteria andOpeInsLessThanOrEqualTo(String value) {
            addCriterion("ope_ins <=", value, "opeIns");
            return (Criteria) this;
        }

        public Criteria andOpeInsLike(String value) {
            addCriterion("ope_ins like", value, "opeIns");
            return (Criteria) this;
        }

        public Criteria andOpeInsNotLike(String value) {
            addCriterion("ope_ins not like", value, "opeIns");
            return (Criteria) this;
        }

        public Criteria andOpeInsIn(List<String> values) {
            addCriterion("ope_ins in", values, "opeIns");
            return (Criteria) this;
        }

        public Criteria andOpeInsNotIn(List<String> values) {
            addCriterion("ope_ins not in", values, "opeIns");
            return (Criteria) this;
        }

        public Criteria andOpeInsBetween(String value1, String value2) {
            addCriterion("ope_ins between", value1, value2, "opeIns");
            return (Criteria) this;
        }

        public Criteria andOpeInsNotBetween(String value1, String value2) {
            addCriterion("ope_ins not between", value1, value2, "opeIns");
            return (Criteria) this;
        }

        public Criteria andPlanIdIsNull() {
            addCriterion("plan_id is null");
            return (Criteria) this;
        }

        public Criteria andPlanIdIsNotNull() {
            addCriterion("plan_id is not null");
            return (Criteria) this;
        }

        public Criteria andPlanIdEqualTo(Integer value) {
            addCriterion("plan_id =", value, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdNotEqualTo(Integer value) {
            addCriterion("plan_id <>", value, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdGreaterThan(Integer value) {
            addCriterion("plan_id >", value, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("plan_id >=", value, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdLessThan(Integer value) {
            addCriterion("plan_id <", value, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdLessThanOrEqualTo(Integer value) {
            addCriterion("plan_id <=", value, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdIn(List<Integer> values) {
            addCriterion("plan_id in", values, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdNotIn(List<Integer> values) {
            addCriterion("plan_id not in", values, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdBetween(Integer value1, Integer value2) {
            addCriterion("plan_id between", value1, value2, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdNotBetween(Integer value1, Integer value2) {
            addCriterion("plan_id not between", value1, value2, "planId");
            return (Criteria) this;
        }

        public Criteria andPlatxtIsNull() {
            addCriterion("platxt is null");
            return (Criteria) this;
        }

        public Criteria andPlatxtIsNotNull() {
            addCriterion("platxt is not null");
            return (Criteria) this;
        }

        public Criteria andPlatxtEqualTo(String value) {
            addCriterion("platxt =", value, "platxt");
            return (Criteria) this;
        }

        public Criteria andPlatxtNotEqualTo(String value) {
            addCriterion("platxt <>", value, "platxt");
            return (Criteria) this;
        }

        public Criteria andPlatxtGreaterThan(String value) {
            addCriterion("platxt >", value, "platxt");
            return (Criteria) this;
        }

        public Criteria andPlatxtGreaterThanOrEqualTo(String value) {
            addCriterion("platxt >=", value, "platxt");
            return (Criteria) this;
        }

        public Criteria andPlatxtLessThan(String value) {
            addCriterion("platxt <", value, "platxt");
            return (Criteria) this;
        }

        public Criteria andPlatxtLessThanOrEqualTo(String value) {
            addCriterion("platxt <=", value, "platxt");
            return (Criteria) this;
        }

        public Criteria andPlatxtLike(String value) {
            addCriterion("platxt like", value, "platxt");
            return (Criteria) this;
        }

        public Criteria andPlatxtNotLike(String value) {
            addCriterion("platxt not like", value, "platxt");
            return (Criteria) this;
        }

        public Criteria andPlatxtIn(List<String> values) {
            addCriterion("platxt in", values, "platxt");
            return (Criteria) this;
        }

        public Criteria andPlatxtNotIn(List<String> values) {
            addCriterion("platxt not in", values, "platxt");
            return (Criteria) this;
        }

        public Criteria andPlatxtBetween(String value1, String value2) {
            addCriterion("platxt between", value1, value2, "platxt");
            return (Criteria) this;
        }

        public Criteria andPlatxtNotBetween(String value1, String value2) {
            addCriterion("platxt not between", value1, value2, "platxt");
            return (Criteria) this;
        }

        public Criteria andSergeIsNull() {
            addCriterion("serge is null");
            return (Criteria) this;
        }

        public Criteria andSergeIsNotNull() {
            addCriterion("serge is not null");
            return (Criteria) this;
        }

        public Criteria andSergeEqualTo(String value) {
            addCriterion("serge =", value, "serge");
            return (Criteria) this;
        }

        public Criteria andSergeNotEqualTo(String value) {
            addCriterion("serge <>", value, "serge");
            return (Criteria) this;
        }

        public Criteria andSergeGreaterThan(String value) {
            addCriterion("serge >", value, "serge");
            return (Criteria) this;
        }

        public Criteria andSergeGreaterThanOrEqualTo(String value) {
            addCriterion("serge >=", value, "serge");
            return (Criteria) this;
        }

        public Criteria andSergeLessThan(String value) {
            addCriterion("serge <", value, "serge");
            return (Criteria) this;
        }

        public Criteria andSergeLessThanOrEqualTo(String value) {
            addCriterion("serge <=", value, "serge");
            return (Criteria) this;
        }

        public Criteria andSergeLike(String value) {
            addCriterion("serge like", value, "serge");
            return (Criteria) this;
        }

        public Criteria andSergeNotLike(String value) {
            addCriterion("serge not like", value, "serge");
            return (Criteria) this;
        }

        public Criteria andSergeIn(List<String> values) {
            addCriterion("serge in", values, "serge");
            return (Criteria) this;
        }

        public Criteria andSergeNotIn(List<String> values) {
            addCriterion("serge not in", values, "serge");
            return (Criteria) this;
        }

        public Criteria andSergeBetween(String value1, String value2) {
            addCriterion("serge between", value1, value2, "serge");
            return (Criteria) this;
        }

        public Criteria andSergeNotBetween(String value1, String value2) {
            addCriterion("serge not between", value1, value2, "serge");
            return (Criteria) this;
        }

        public Criteria andSernrIsNull() {
            addCriterion("sernr is null");
            return (Criteria) this;
        }

        public Criteria andSernrIsNotNull() {
            addCriterion("sernr is not null");
            return (Criteria) this;
        }

        public Criteria andSernrEqualTo(String value) {
            addCriterion("sernr =", value, "sernr");
            return (Criteria) this;
        }

        public Criteria andSernrNotEqualTo(String value) {
            addCriterion("sernr <>", value, "sernr");
            return (Criteria) this;
        }

        public Criteria andSernrGreaterThan(String value) {
            addCriterion("sernr >", value, "sernr");
            return (Criteria) this;
        }

        public Criteria andSernrGreaterThanOrEqualTo(String value) {
            addCriterion("sernr >=", value, "sernr");
            return (Criteria) this;
        }

        public Criteria andSernrLessThan(String value) {
            addCriterion("sernr <", value, "sernr");
            return (Criteria) this;
        }

        public Criteria andSernrLessThanOrEqualTo(String value) {
            addCriterion("sernr <=", value, "sernr");
            return (Criteria) this;
        }

        public Criteria andSernrLike(String value) {
            addCriterion("sernr like", value, "sernr");
            return (Criteria) this;
        }

        public Criteria andSernrNotLike(String value) {
            addCriterion("sernr not like", value, "sernr");
            return (Criteria) this;
        }

        public Criteria andSernrIn(List<String> values) {
            addCriterion("sernr in", values, "sernr");
            return (Criteria) this;
        }

        public Criteria andSernrNotIn(List<String> values) {
            addCriterion("sernr not in", values, "sernr");
            return (Criteria) this;
        }

        public Criteria andSernrBetween(String value1, String value2) {
            addCriterion("sernr between", value1, value2, "sernr");
            return (Criteria) this;
        }

        public Criteria andSernrNotBetween(String value1, String value2) {
            addCriterion("sernr not between", value1, value2, "sernr");
            return (Criteria) this;
        }

        public Criteria andSrqunrIsNull() {
            addCriterion("srqunr is null");
            return (Criteria) this;
        }

        public Criteria andSrqunrIsNotNull() {
            addCriterion("srqunr is not null");
            return (Criteria) this;
        }

        public Criteria andSrqunrEqualTo(String value) {
            addCriterion("srqunr =", value, "srqunr");
            return (Criteria) this;
        }

        public Criteria andSrqunrNotEqualTo(String value) {
            addCriterion("srqunr <>", value, "srqunr");
            return (Criteria) this;
        }

        public Criteria andSrqunrGreaterThan(String value) {
            addCriterion("srqunr >", value, "srqunr");
            return (Criteria) this;
        }

        public Criteria andSrqunrGreaterThanOrEqualTo(String value) {
            addCriterion("srqunr >=", value, "srqunr");
            return (Criteria) this;
        }

        public Criteria andSrqunrLessThan(String value) {
            addCriterion("srqunr <", value, "srqunr");
            return (Criteria) this;
        }

        public Criteria andSrqunrLessThanOrEqualTo(String value) {
            addCriterion("srqunr <=", value, "srqunr");
            return (Criteria) this;
        }

        public Criteria andSrqunrLike(String value) {
            addCriterion("srqunr like", value, "srqunr");
            return (Criteria) this;
        }

        public Criteria andSrqunrNotLike(String value) {
            addCriterion("srqunr not like", value, "srqunr");
            return (Criteria) this;
        }

        public Criteria andSrqunrIn(List<String> values) {
            addCriterion("srqunr in", values, "srqunr");
            return (Criteria) this;
        }

        public Criteria andSrqunrNotIn(List<String> values) {
            addCriterion("srqunr not in", values, "srqunr");
            return (Criteria) this;
        }

        public Criteria andSrqunrBetween(String value1, String value2) {
            addCriterion("srqunr between", value1, value2, "srqunr");
            return (Criteria) this;
        }

        public Criteria andSrqunrNotBetween(String value1, String value2) {
            addCriterion("srqunr not between", value1, value2, "srqunr");
            return (Criteria) this;
        }

        public Criteria andTextIsNull() {
            addCriterion("text is null");
            return (Criteria) this;
        }

        public Criteria andTextIsNotNull() {
            addCriterion("text is not null");
            return (Criteria) this;
        }

        public Criteria andTextEqualTo(String value) {
            addCriterion("text =", value, "text");
            return (Criteria) this;
        }

        public Criteria andTextNotEqualTo(String value) {
            addCriterion("text <>", value, "text");
            return (Criteria) this;
        }

        public Criteria andTextGreaterThan(String value) {
            addCriterion("text >", value, "text");
            return (Criteria) this;
        }

        public Criteria andTextGreaterThanOrEqualTo(String value) {
            addCriterion("text >=", value, "text");
            return (Criteria) this;
        }

        public Criteria andTextLessThan(String value) {
            addCriterion("text <", value, "text");
            return (Criteria) this;
        }

        public Criteria andTextLessThanOrEqualTo(String value) {
            addCriterion("text <=", value, "text");
            return (Criteria) this;
        }

        public Criteria andTextLike(String value) {
            addCriterion("text like", value, "text");
            return (Criteria) this;
        }

        public Criteria andTextNotLike(String value) {
            addCriterion("text not like", value, "text");
            return (Criteria) this;
        }

        public Criteria andTextIn(List<String> values) {
            addCriterion("text in", values, "text");
            return (Criteria) this;
        }

        public Criteria andTextNotIn(List<String> values) {
            addCriterion("text not in", values, "text");
            return (Criteria) this;
        }

        public Criteria andTextBetween(String value1, String value2) {
            addCriterion("text between", value1, value2, "text");
            return (Criteria) this;
        }

        public Criteria andTextNotBetween(String value1, String value2) {
            addCriterion("text not between", value1, value2, "text");
            return (Criteria) this;
        }

        public Criteria andUploadFlagIsNull() {
            addCriterion("upload_flag is null");
            return (Criteria) this;
        }

        public Criteria andUploadFlagIsNotNull() {
            addCriterion("upload_flag is not null");
            return (Criteria) this;
        }

        public Criteria andUploadFlagEqualTo(String value) {
            addCriterion("upload_flag =", value, "uploadFlag");
            return (Criteria) this;
        }

        public Criteria andUploadFlagNotEqualTo(String value) {
            addCriterion("upload_flag <>", value, "uploadFlag");
            return (Criteria) this;
        }

        public Criteria andUploadFlagGreaterThan(String value) {
            addCriterion("upload_flag >", value, "uploadFlag");
            return (Criteria) this;
        }

        public Criteria andUploadFlagGreaterThanOrEqualTo(String value) {
            addCriterion("upload_flag >=", value, "uploadFlag");
            return (Criteria) this;
        }

        public Criteria andUploadFlagLessThan(String value) {
            addCriterion("upload_flag <", value, "uploadFlag");
            return (Criteria) this;
        }

        public Criteria andUploadFlagLessThanOrEqualTo(String value) {
            addCriterion("upload_flag <=", value, "uploadFlag");
            return (Criteria) this;
        }

        public Criteria andUploadFlagLike(String value) {
            addCriterion("upload_flag like", value, "uploadFlag");
            return (Criteria) this;
        }

        public Criteria andUploadFlagNotLike(String value) {
            addCriterion("upload_flag not like", value, "uploadFlag");
            return (Criteria) this;
        }

        public Criteria andUploadFlagIn(List<String> values) {
            addCriterion("upload_flag in", values, "uploadFlag");
            return (Criteria) this;
        }

        public Criteria andUploadFlagNotIn(List<String> values) {
            addCriterion("upload_flag not in", values, "uploadFlag");
            return (Criteria) this;
        }

        public Criteria andUploadFlagBetween(String value1, String value2) {
            addCriterion("upload_flag between", value1, value2, "uploadFlag");
            return (Criteria) this;
        }

        public Criteria andUploadFlagNotBetween(String value1, String value2) {
            addCriterion("upload_flag not between", value1, value2, "uploadFlag");
            return (Criteria) this;
        }

        public Criteria andVertragIsNull() {
            addCriterion("vertrag is null");
            return (Criteria) this;
        }

        public Criteria andVertragIsNotNull() {
            addCriterion("vertrag is not null");
            return (Criteria) this;
        }

        public Criteria andVertragEqualTo(String value) {
            addCriterion("vertrag =", value, "vertrag");
            return (Criteria) this;
        }

        public Criteria andVertragNotEqualTo(String value) {
            addCriterion("vertrag <>", value, "vertrag");
            return (Criteria) this;
        }

        public Criteria andVertragGreaterThan(String value) {
            addCriterion("vertrag >", value, "vertrag");
            return (Criteria) this;
        }

        public Criteria andVertragGreaterThanOrEqualTo(String value) {
            addCriterion("vertrag >=", value, "vertrag");
            return (Criteria) this;
        }

        public Criteria andVertragLessThan(String value) {
            addCriterion("vertrag <", value, "vertrag");
            return (Criteria) this;
        }

        public Criteria andVertragLessThanOrEqualTo(String value) {
            addCriterion("vertrag <=", value, "vertrag");
            return (Criteria) this;
        }

        public Criteria andVertragLike(String value) {
            addCriterion("vertrag like", value, "vertrag");
            return (Criteria) this;
        }

        public Criteria andVertragNotLike(String value) {
            addCriterion("vertrag not like", value, "vertrag");
            return (Criteria) this;
        }

        public Criteria andVertragIn(List<String> values) {
            addCriterion("vertrag in", values, "vertrag");
            return (Criteria) this;
        }

        public Criteria andVertragNotIn(List<String> values) {
            addCriterion("vertrag not in", values, "vertrag");
            return (Criteria) this;
        }

        public Criteria andVertragBetween(String value1, String value2) {
            addCriterion("vertrag between", value1, value2, "vertrag");
            return (Criteria) this;
        }

        public Criteria andVertragNotBetween(String value1, String value2) {
            addCriterion("vertrag not between", value1, value2, "vertrag");
            return (Criteria) this;
        }

        public Criteria andVreferIsNull() {
            addCriterion("vrefer is null");
            return (Criteria) this;
        }

        public Criteria andVreferIsNotNull() {
            addCriterion("vrefer is not null");
            return (Criteria) this;
        }

        public Criteria andVreferEqualTo(String value) {
            addCriterion("vrefer =", value, "vrefer");
            return (Criteria) this;
        }

        public Criteria andVreferNotEqualTo(String value) {
            addCriterion("vrefer <>", value, "vrefer");
            return (Criteria) this;
        }

        public Criteria andVreferGreaterThan(String value) {
            addCriterion("vrefer >", value, "vrefer");
            return (Criteria) this;
        }

        public Criteria andVreferGreaterThanOrEqualTo(String value) {
            addCriterion("vrefer >=", value, "vrefer");
            return (Criteria) this;
        }

        public Criteria andVreferLessThan(String value) {
            addCriterion("vrefer <", value, "vrefer");
            return (Criteria) this;
        }

        public Criteria andVreferLessThanOrEqualTo(String value) {
            addCriterion("vrefer <=", value, "vrefer");
            return (Criteria) this;
        }

        public Criteria andVreferLike(String value) {
            addCriterion("vrefer like", value, "vrefer");
            return (Criteria) this;
        }

        public Criteria andVreferNotLike(String value) {
            addCriterion("vrefer not like", value, "vrefer");
            return (Criteria) this;
        }

        public Criteria andVreferIn(List<String> values) {
            addCriterion("vrefer in", values, "vrefer");
            return (Criteria) this;
        }

        public Criteria andVreferNotIn(List<String> values) {
            addCriterion("vrefer not in", values, "vrefer");
            return (Criteria) this;
        }

        public Criteria andVreferBetween(String value1, String value2) {
            addCriterion("vrefer between", value1, value2, "vrefer");
            return (Criteria) this;
        }

        public Criteria andVreferNotBetween(String value1, String value2) {
            addCriterion("vrefer not between", value1, value2, "vrefer");
            return (Criteria) this;
        }

        public Criteria andVstelleIsNull() {
            addCriterion("vstelle is null");
            return (Criteria) this;
        }

        public Criteria andVstelleIsNotNull() {
            addCriterion("vstelle is not null");
            return (Criteria) this;
        }

        public Criteria andVstelleEqualTo(String value) {
            addCriterion("vstelle =", value, "vstelle");
            return (Criteria) this;
        }

        public Criteria andVstelleNotEqualTo(String value) {
            addCriterion("vstelle <>", value, "vstelle");
            return (Criteria) this;
        }

        public Criteria andVstelleGreaterThan(String value) {
            addCriterion("vstelle >", value, "vstelle");
            return (Criteria) this;
        }

        public Criteria andVstelleGreaterThanOrEqualTo(String value) {
            addCriterion("vstelle >=", value, "vstelle");
            return (Criteria) this;
        }

        public Criteria andVstelleLessThan(String value) {
            addCriterion("vstelle <", value, "vstelle");
            return (Criteria) this;
        }

        public Criteria andVstelleLessThanOrEqualTo(String value) {
            addCriterion("vstelle <=", value, "vstelle");
            return (Criteria) this;
        }

        public Criteria andVstelleLike(String value) {
            addCriterion("vstelle like", value, "vstelle");
            return (Criteria) this;
        }

        public Criteria andVstelleNotLike(String value) {
            addCriterion("vstelle not like", value, "vstelle");
            return (Criteria) this;
        }

        public Criteria andVstelleIn(List<String> values) {
            addCriterion("vstelle in", values, "vstelle");
            return (Criteria) this;
        }

        public Criteria andVstelleNotIn(List<String> values) {
            addCriterion("vstelle not in", values, "vstelle");
            return (Criteria) this;
        }

        public Criteria andVstelleBetween(String value1, String value2) {
            addCriterion("vstelle between", value1, value2, "vstelle");
            return (Criteria) this;
        }

        public Criteria andVstelleNotBetween(String value1, String value2) {
            addCriterion("vstelle not between", value1, value2, "vstelle");
            return (Criteria) this;
        }

        public Criteria andYcdirIsNull() {
            addCriterion("ycdir is null");
            return (Criteria) this;
        }

        public Criteria andYcdirIsNotNull() {
            addCriterion("ycdir is not null");
            return (Criteria) this;
        }

        public Criteria andYcdirEqualTo(String value) {
            addCriterion("ycdir =", value, "ycdir");
            return (Criteria) this;
        }

        public Criteria andYcdirNotEqualTo(String value) {
            addCriterion("ycdir <>", value, "ycdir");
            return (Criteria) this;
        }

        public Criteria andYcdirGreaterThan(String value) {
            addCriterion("ycdir >", value, "ycdir");
            return (Criteria) this;
        }

        public Criteria andYcdirGreaterThanOrEqualTo(String value) {
            addCriterion("ycdir >=", value, "ycdir");
            return (Criteria) this;
        }

        public Criteria andYcdirLessThan(String value) {
            addCriterion("ycdir <", value, "ycdir");
            return (Criteria) this;
        }

        public Criteria andYcdirLessThanOrEqualTo(String value) {
            addCriterion("ycdir <=", value, "ycdir");
            return (Criteria) this;
        }

        public Criteria andYcdirLike(String value) {
            addCriterion("ycdir like", value, "ycdir");
            return (Criteria) this;
        }

        public Criteria andYcdirNotLike(String value) {
            addCriterion("ycdir not like", value, "ycdir");
            return (Criteria) this;
        }

        public Criteria andYcdirIn(List<String> values) {
            addCriterion("ycdir in", values, "ycdir");
            return (Criteria) this;
        }

        public Criteria andYcdirNotIn(List<String> values) {
            addCriterion("ycdir not in", values, "ycdir");
            return (Criteria) this;
        }

        public Criteria andYcdirBetween(String value1, String value2) {
            addCriterion("ycdir between", value1, value2, "ycdir");
            return (Criteria) this;
        }

        public Criteria andYcdirNotBetween(String value1, String value2) {
            addCriterion("ycdir not between", value1, value2, "ycdir");
            return (Criteria) this;
        }

        public Criteria andYfhkaIsNull() {
            addCriterion("yfhka is null");
            return (Criteria) this;
        }

        public Criteria andYfhkaIsNotNull() {
            addCriterion("yfhka is not null");
            return (Criteria) this;
        }

        public Criteria andYfhkaEqualTo(String value) {
            addCriterion("yfhka =", value, "yfhka");
            return (Criteria) this;
        }

        public Criteria andYfhkaNotEqualTo(String value) {
            addCriterion("yfhka <>", value, "yfhka");
            return (Criteria) this;
        }

        public Criteria andYfhkaGreaterThan(String value) {
            addCriterion("yfhka >", value, "yfhka");
            return (Criteria) this;
        }

        public Criteria andYfhkaGreaterThanOrEqualTo(String value) {
            addCriterion("yfhka >=", value, "yfhka");
            return (Criteria) this;
        }

        public Criteria andYfhkaLessThan(String value) {
            addCriterion("yfhka <", value, "yfhka");
            return (Criteria) this;
        }

        public Criteria andYfhkaLessThanOrEqualTo(String value) {
            addCriterion("yfhka <=", value, "yfhka");
            return (Criteria) this;
        }

        public Criteria andYfhkaLike(String value) {
            addCriterion("yfhka like", value, "yfhka");
            return (Criteria) this;
        }

        public Criteria andYfhkaNotLike(String value) {
            addCriterion("yfhka not like", value, "yfhka");
            return (Criteria) this;
        }

        public Criteria andYfhkaIn(List<String> values) {
            addCriterion("yfhka in", values, "yfhka");
            return (Criteria) this;
        }

        public Criteria andYfhkaNotIn(List<String> values) {
            addCriterion("yfhka not in", values, "yfhka");
            return (Criteria) this;
        }

        public Criteria andYfhkaBetween(String value1, String value2) {
            addCriterion("yfhka between", value1, value2, "yfhka");
            return (Criteria) this;
        }

        public Criteria andYfhkaNotBetween(String value1, String value2) {
            addCriterion("yfhka not between", value1, value2, "yfhka");
            return (Criteria) this;
        }

        public Criteria andYliuf1IsNull() {
            addCriterion("yliuf1 is null");
            return (Criteria) this;
        }

        public Criteria andYliuf1IsNotNull() {
            addCriterion("yliuf1 is not null");
            return (Criteria) this;
        }

        public Criteria andYliuf1EqualTo(String value) {
            addCriterion("yliuf1 =", value, "yliuf1");
            return (Criteria) this;
        }

        public Criteria andYliuf1NotEqualTo(String value) {
            addCriterion("yliuf1 <>", value, "yliuf1");
            return (Criteria) this;
        }

        public Criteria andYliuf1GreaterThan(String value) {
            addCriterion("yliuf1 >", value, "yliuf1");
            return (Criteria) this;
        }

        public Criteria andYliuf1GreaterThanOrEqualTo(String value) {
            addCriterion("yliuf1 >=", value, "yliuf1");
            return (Criteria) this;
        }

        public Criteria andYliuf1LessThan(String value) {
            addCriterion("yliuf1 <", value, "yliuf1");
            return (Criteria) this;
        }

        public Criteria andYliuf1LessThanOrEqualTo(String value) {
            addCriterion("yliuf1 <=", value, "yliuf1");
            return (Criteria) this;
        }

        public Criteria andYliuf1Like(String value) {
            addCriterion("yliuf1 like", value, "yliuf1");
            return (Criteria) this;
        }

        public Criteria andYliuf1NotLike(String value) {
            addCriterion("yliuf1 not like", value, "yliuf1");
            return (Criteria) this;
        }

        public Criteria andYliuf1In(List<String> values) {
            addCriterion("yliuf1 in", values, "yliuf1");
            return (Criteria) this;
        }

        public Criteria andYliuf1NotIn(List<String> values) {
            addCriterion("yliuf1 not in", values, "yliuf1");
            return (Criteria) this;
        }

        public Criteria andYliuf1Between(String value1, String value2) {
            addCriterion("yliuf1 between", value1, value2, "yliuf1");
            return (Criteria) this;
        }

        public Criteria andYliuf1NotBetween(String value1, String value2) {
            addCriterion("yliuf1 not between", value1, value2, "yliuf1");
            return (Criteria) this;
        }

        public Criteria andYplaceIsNull() {
            addCriterion("yplace is null");
            return (Criteria) this;
        }

        public Criteria andYplaceIsNotNull() {
            addCriterion("yplace is not null");
            return (Criteria) this;
        }

        public Criteria andYplaceEqualTo(String value) {
            addCriterion("yplace =", value, "yplace");
            return (Criteria) this;
        }

        public Criteria andYplaceNotEqualTo(String value) {
            addCriterion("yplace <>", value, "yplace");
            return (Criteria) this;
        }

        public Criteria andYplaceGreaterThan(String value) {
            addCriterion("yplace >", value, "yplace");
            return (Criteria) this;
        }

        public Criteria andYplaceGreaterThanOrEqualTo(String value) {
            addCriterion("yplace >=", value, "yplace");
            return (Criteria) this;
        }

        public Criteria andYplaceLessThan(String value) {
            addCriterion("yplace <", value, "yplace");
            return (Criteria) this;
        }

        public Criteria andYplaceLessThanOrEqualTo(String value) {
            addCriterion("yplace <=", value, "yplace");
            return (Criteria) this;
        }

        public Criteria andYplaceLike(String value) {
            addCriterion("yplace like", value, "yplace");
            return (Criteria) this;
        }

        public Criteria andYplaceNotLike(String value) {
            addCriterion("yplace not like", value, "yplace");
            return (Criteria) this;
        }

        public Criteria andYplaceIn(List<String> values) {
            addCriterion("yplace in", values, "yplace");
            return (Criteria) this;
        }

        public Criteria andYplaceNotIn(List<String> values) {
            addCriterion("yplace not in", values, "yplace");
            return (Criteria) this;
        }

        public Criteria andYplaceBetween(String value1, String value2) {
            addCriterion("yplace between", value1, value2, "yplace");
            return (Criteria) this;
        }

        public Criteria andYplaceNotBetween(String value1, String value2) {
            addCriterion("yplace not between", value1, value2, "yplace");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ichinstallinfo
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ichinstallinfo
     *
     * @mbg.generated
     */
    public static class Criterion implements Serializable {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}