package com.ecej.po;

import java.io.Serializable;

/**
 * Created by wyx on 2017-10-09.
 * 
 * @author wyx
 * @title ichprice
 * @date 2017-10-09
 */
public class ICHPrice implements Serializable {
    /**
     * 
     * id 
     * id
     */
    private Integer id;

    /**
     * 
     * ab 
     * ab
     */
    private String ab;

    /**
     * 
     * aenam 
     * aenam
     */
    private String aenam;

    /**
     * 
     * anlage 
     * anlage
     */
    private String anlage;

    /**
     * 
     * bukrs 
     * bukrs
     */
    private String bukrs;

    /**
     * 
     * caculatety 
     * caculatety
     */
    private String caculatety;

    /**
     * 
     * dats 
     * dats
     */
    private String dats;

    /**
     * 
     * higprice 
     * higprice
     */
    private Double higprice;

    /**
     * 
     * iZahl 
     * i_zahl
     */
    private String iZahl;

    /**
     * 
     * iZahl2 
     * i_zahl2
     */
    private Double iZahl2;

    /**
     * 
     * iZahl3 
     * i_zahl3
     */
    private Double iZahl3;

    /**
     * 
     * icZahl 
     * ic_zahl
     */
    private Double icZahl;

    /**
     * 
     * icZahl2 
     * ic_zahl2
     */
    private Double icZahl2;

    /**
     * 
     * icZahl3 
     * ic_zahl3
     */
    private Double icZahl3;

    /**
     * 
     * icmon 
     * icmon
     */
    private Double icmon;

    /**
     * 
     * jtbz 
     * jtbz
     */
    private String jtbz;

    /**
     * 
     * jtlevl 
     * jtlevl
     */
    private String jtlevl;

    /**
     * 
     * laeda 
     * laeda
     */
    private String laeda;

    /**
     * 
     * lowprice 
     * lowprice
     */
    private Double lowprice;

    /**
     * 
     * morprice 
     * morprice
     */
    private Double morprice;

    /**
     * 
     * planId 
     * plan_id
     */
    private Integer planId;

    /**
     * 
     * qsyue 
     * qsyue
     */
    private String qsyue;

    /**
     * 
     * resprice 
     * resprice
     */
    private Double resprice;

    /**
     * 
     * stepMethd 
     * step_methd
     */
    private String stepMethd;

    /**
     * 
     * tariftyp 
     * tariftyp
     */
    private String tariftyp;

    /**
     * 
     * xuhao 
     * xuhao
     */
    private String xuhao;

    /**
     * 
     * zzyue 
     * zzyue
     */
    private String zzyue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ichprice
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichprice.id
     *
     * @return the value of ichprice.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichprice.id
     *
     * @param id the value for ichprice.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichprice.ab
     *
     * @return the value of ichprice.ab
     *
     * @mbg.generated
     */
    public String getAb() {
        return ab;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichprice.ab
     *
     * @param ab the value for ichprice.ab
     *
     * @mbg.generated
     */
    public void setAb(String ab) {
        this.ab = ab == null ? null : ab.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichprice.aenam
     *
     * @return the value of ichprice.aenam
     *
     * @mbg.generated
     */
    public String getAenam() {
        return aenam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichprice.aenam
     *
     * @param aenam the value for ichprice.aenam
     *
     * @mbg.generated
     */
    public void setAenam(String aenam) {
        this.aenam = aenam == null ? null : aenam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichprice.anlage
     *
     * @return the value of ichprice.anlage
     *
     * @mbg.generated
     */
    public String getAnlage() {
        return anlage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichprice.anlage
     *
     * @param anlage the value for ichprice.anlage
     *
     * @mbg.generated
     */
    public void setAnlage(String anlage) {
        this.anlage = anlage == null ? null : anlage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichprice.bukrs
     *
     * @return the value of ichprice.bukrs
     *
     * @mbg.generated
     */
    public String getBukrs() {
        return bukrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichprice.bukrs
     *
     * @param bukrs the value for ichprice.bukrs
     *
     * @mbg.generated
     */
    public void setBukrs(String bukrs) {
        this.bukrs = bukrs == null ? null : bukrs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichprice.caculatety
     *
     * @return the value of ichprice.caculatety
     *
     * @mbg.generated
     */
    public String getCaculatety() {
        return caculatety;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichprice.caculatety
     *
     * @param caculatety the value for ichprice.caculatety
     *
     * @mbg.generated
     */
    public void setCaculatety(String caculatety) {
        this.caculatety = caculatety == null ? null : caculatety.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichprice.dats
     *
     * @return the value of ichprice.dats
     *
     * @mbg.generated
     */
    public String getDats() {
        return dats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichprice.dats
     *
     * @param dats the value for ichprice.dats
     *
     * @mbg.generated
     */
    public void setDats(String dats) {
        this.dats = dats == null ? null : dats.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichprice.higprice
     *
     * @return the value of ichprice.higprice
     *
     * @mbg.generated
     */
    public Double getHigprice() {
        return higprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichprice.higprice
     *
     * @param higprice the value for ichprice.higprice
     *
     * @mbg.generated
     */
    public void setHigprice(Double higprice) {
        this.higprice = higprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichprice.i_zahl
     *
     * @return the value of ichprice.i_zahl
     *
     * @mbg.generated
     */
    public String getiZahl() {
        return iZahl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichprice.i_zahl
     *
     * @param iZahl the value for ichprice.i_zahl
     *
     * @mbg.generated
     */
    public void setiZahl(String iZahl) {
        this.iZahl = iZahl == null ? null : iZahl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichprice.i_zahl2
     *
     * @return the value of ichprice.i_zahl2
     *
     * @mbg.generated
     */
    public Double getiZahl2() {
        return iZahl2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichprice.i_zahl2
     *
     * @param iZahl2 the value for ichprice.i_zahl2
     *
     * @mbg.generated
     */
    public void setiZahl2(Double iZahl2) {
        this.iZahl2 = iZahl2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichprice.i_zahl3
     *
     * @return the value of ichprice.i_zahl3
     *
     * @mbg.generated
     */
    public Double getiZahl3() {
        return iZahl3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichprice.i_zahl3
     *
     * @param iZahl3 the value for ichprice.i_zahl3
     *
     * @mbg.generated
     */
    public void setiZahl3(Double iZahl3) {
        this.iZahl3 = iZahl3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichprice.ic_zahl
     *
     * @return the value of ichprice.ic_zahl
     *
     * @mbg.generated
     */
    public Double getIcZahl() {
        return icZahl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichprice.ic_zahl
     *
     * @param icZahl the value for ichprice.ic_zahl
     *
     * @mbg.generated
     */
    public void setIcZahl(Double icZahl) {
        this.icZahl = icZahl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichprice.ic_zahl2
     *
     * @return the value of ichprice.ic_zahl2
     *
     * @mbg.generated
     */
    public Double getIcZahl2() {
        return icZahl2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichprice.ic_zahl2
     *
     * @param icZahl2 the value for ichprice.ic_zahl2
     *
     * @mbg.generated
     */
    public void setIcZahl2(Double icZahl2) {
        this.icZahl2 = icZahl2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichprice.ic_zahl3
     *
     * @return the value of ichprice.ic_zahl3
     *
     * @mbg.generated
     */
    public Double getIcZahl3() {
        return icZahl3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichprice.ic_zahl3
     *
     * @param icZahl3 the value for ichprice.ic_zahl3
     *
     * @mbg.generated
     */
    public void setIcZahl3(Double icZahl3) {
        this.icZahl3 = icZahl3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichprice.icmon
     *
     * @return the value of ichprice.icmon
     *
     * @mbg.generated
     */
    public Double getIcmon() {
        return icmon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichprice.icmon
     *
     * @param icmon the value for ichprice.icmon
     *
     * @mbg.generated
     */
    public void setIcmon(Double icmon) {
        this.icmon = icmon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichprice.jtbz
     *
     * @return the value of ichprice.jtbz
     *
     * @mbg.generated
     */
    public String getJtbz() {
        return jtbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichprice.jtbz
     *
     * @param jtbz the value for ichprice.jtbz
     *
     * @mbg.generated
     */
    public void setJtbz(String jtbz) {
        this.jtbz = jtbz == null ? null : jtbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichprice.jtlevl
     *
     * @return the value of ichprice.jtlevl
     *
     * @mbg.generated
     */
    public String getJtlevl() {
        return jtlevl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichprice.jtlevl
     *
     * @param jtlevl the value for ichprice.jtlevl
     *
     * @mbg.generated
     */
    public void setJtlevl(String jtlevl) {
        this.jtlevl = jtlevl == null ? null : jtlevl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichprice.laeda
     *
     * @return the value of ichprice.laeda
     *
     * @mbg.generated
     */
    public String getLaeda() {
        return laeda;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichprice.laeda
     *
     * @param laeda the value for ichprice.laeda
     *
     * @mbg.generated
     */
    public void setLaeda(String laeda) {
        this.laeda = laeda == null ? null : laeda.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichprice.lowprice
     *
     * @return the value of ichprice.lowprice
     *
     * @mbg.generated
     */
    public Double getLowprice() {
        return lowprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichprice.lowprice
     *
     * @param lowprice the value for ichprice.lowprice
     *
     * @mbg.generated
     */
    public void setLowprice(Double lowprice) {
        this.lowprice = lowprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichprice.morprice
     *
     * @return the value of ichprice.morprice
     *
     * @mbg.generated
     */
    public Double getMorprice() {
        return morprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichprice.morprice
     *
     * @param morprice the value for ichprice.morprice
     *
     * @mbg.generated
     */
    public void setMorprice(Double morprice) {
        this.morprice = morprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichprice.plan_id
     *
     * @return the value of ichprice.plan_id
     *
     * @mbg.generated
     */
    public Integer getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichprice.plan_id
     *
     * @param planId the value for ichprice.plan_id
     *
     * @mbg.generated
     */
    public void setPlanId(Integer planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichprice.qsyue
     *
     * @return the value of ichprice.qsyue
     *
     * @mbg.generated
     */
    public String getQsyue() {
        return qsyue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichprice.qsyue
     *
     * @param qsyue the value for ichprice.qsyue
     *
     * @mbg.generated
     */
    public void setQsyue(String qsyue) {
        this.qsyue = qsyue == null ? null : qsyue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichprice.resprice
     *
     * @return the value of ichprice.resprice
     *
     * @mbg.generated
     */
    public Double getResprice() {
        return resprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichprice.resprice
     *
     * @param resprice the value for ichprice.resprice
     *
     * @mbg.generated
     */
    public void setResprice(Double resprice) {
        this.resprice = resprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichprice.step_methd
     *
     * @return the value of ichprice.step_methd
     *
     * @mbg.generated
     */
    public String getStepMethd() {
        return stepMethd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichprice.step_methd
     *
     * @param stepMethd the value for ichprice.step_methd
     *
     * @mbg.generated
     */
    public void setStepMethd(String stepMethd) {
        this.stepMethd = stepMethd == null ? null : stepMethd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichprice.tariftyp
     *
     * @return the value of ichprice.tariftyp
     *
     * @mbg.generated
     */
    public String getTariftyp() {
        return tariftyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichprice.tariftyp
     *
     * @param tariftyp the value for ichprice.tariftyp
     *
     * @mbg.generated
     */
    public void setTariftyp(String tariftyp) {
        this.tariftyp = tariftyp == null ? null : tariftyp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichprice.xuhao
     *
     * @return the value of ichprice.xuhao
     *
     * @mbg.generated
     */
    public String getXuhao() {
        return xuhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichprice.xuhao
     *
     * @param xuhao the value for ichprice.xuhao
     *
     * @mbg.generated
     */
    public void setXuhao(String xuhao) {
        this.xuhao = xuhao == null ? null : xuhao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichprice.zzyue
     *
     * @return the value of ichprice.zzyue
     *
     * @mbg.generated
     */
    public String getZzyue() {
        return zzyue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichprice.zzyue
     *
     * @param zzyue the value for ichprice.zzyue
     *
     * @mbg.generated
     */
    public void setZzyue(String zzyue) {
        this.zzyue = zzyue == null ? null : zzyue.trim();
    }
}