package com.ecej.po;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class ICHPriceExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ichprice
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ichprice
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ichprice
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ichprice
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichprice
     *
     * @mbg.generated
     */
    public ICHPriceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichprice
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichprice
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichprice
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichprice
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichprice
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichprice
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichprice
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichprice
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichprice
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ichprice
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ichprice
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria implements Serializable {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAbIsNull() {
            addCriterion("ab is null");
            return (Criteria) this;
        }

        public Criteria andAbIsNotNull() {
            addCriterion("ab is not null");
            return (Criteria) this;
        }

        public Criteria andAbEqualTo(String value) {
            addCriterion("ab =", value, "ab");
            return (Criteria) this;
        }

        public Criteria andAbNotEqualTo(String value) {
            addCriterion("ab <>", value, "ab");
            return (Criteria) this;
        }

        public Criteria andAbGreaterThan(String value) {
            addCriterion("ab >", value, "ab");
            return (Criteria) this;
        }

        public Criteria andAbGreaterThanOrEqualTo(String value) {
            addCriterion("ab >=", value, "ab");
            return (Criteria) this;
        }

        public Criteria andAbLessThan(String value) {
            addCriterion("ab <", value, "ab");
            return (Criteria) this;
        }

        public Criteria andAbLessThanOrEqualTo(String value) {
            addCriterion("ab <=", value, "ab");
            return (Criteria) this;
        }

        public Criteria andAbLike(String value) {
            addCriterion("ab like", value, "ab");
            return (Criteria) this;
        }

        public Criteria andAbNotLike(String value) {
            addCriterion("ab not like", value, "ab");
            return (Criteria) this;
        }

        public Criteria andAbIn(List<String> values) {
            addCriterion("ab in", values, "ab");
            return (Criteria) this;
        }

        public Criteria andAbNotIn(List<String> values) {
            addCriterion("ab not in", values, "ab");
            return (Criteria) this;
        }

        public Criteria andAbBetween(String value1, String value2) {
            addCriterion("ab between", value1, value2, "ab");
            return (Criteria) this;
        }

        public Criteria andAbNotBetween(String value1, String value2) {
            addCriterion("ab not between", value1, value2, "ab");
            return (Criteria) this;
        }

        public Criteria andAenamIsNull() {
            addCriterion("aenam is null");
            return (Criteria) this;
        }

        public Criteria andAenamIsNotNull() {
            addCriterion("aenam is not null");
            return (Criteria) this;
        }

        public Criteria andAenamEqualTo(String value) {
            addCriterion("aenam =", value, "aenam");
            return (Criteria) this;
        }

        public Criteria andAenamNotEqualTo(String value) {
            addCriterion("aenam <>", value, "aenam");
            return (Criteria) this;
        }

        public Criteria andAenamGreaterThan(String value) {
            addCriterion("aenam >", value, "aenam");
            return (Criteria) this;
        }

        public Criteria andAenamGreaterThanOrEqualTo(String value) {
            addCriterion("aenam >=", value, "aenam");
            return (Criteria) this;
        }

        public Criteria andAenamLessThan(String value) {
            addCriterion("aenam <", value, "aenam");
            return (Criteria) this;
        }

        public Criteria andAenamLessThanOrEqualTo(String value) {
            addCriterion("aenam <=", value, "aenam");
            return (Criteria) this;
        }

        public Criteria andAenamLike(String value) {
            addCriterion("aenam like", value, "aenam");
            return (Criteria) this;
        }

        public Criteria andAenamNotLike(String value) {
            addCriterion("aenam not like", value, "aenam");
            return (Criteria) this;
        }

        public Criteria andAenamIn(List<String> values) {
            addCriterion("aenam in", values, "aenam");
            return (Criteria) this;
        }

        public Criteria andAenamNotIn(List<String> values) {
            addCriterion("aenam not in", values, "aenam");
            return (Criteria) this;
        }

        public Criteria andAenamBetween(String value1, String value2) {
            addCriterion("aenam between", value1, value2, "aenam");
            return (Criteria) this;
        }

        public Criteria andAenamNotBetween(String value1, String value2) {
            addCriterion("aenam not between", value1, value2, "aenam");
            return (Criteria) this;
        }

        public Criteria andAnlageIsNull() {
            addCriterion("anlage is null");
            return (Criteria) this;
        }

        public Criteria andAnlageIsNotNull() {
            addCriterion("anlage is not null");
            return (Criteria) this;
        }

        public Criteria andAnlageEqualTo(String value) {
            addCriterion("anlage =", value, "anlage");
            return (Criteria) this;
        }

        public Criteria andAnlageNotEqualTo(String value) {
            addCriterion("anlage <>", value, "anlage");
            return (Criteria) this;
        }

        public Criteria andAnlageGreaterThan(String value) {
            addCriterion("anlage >", value, "anlage");
            return (Criteria) this;
        }

        public Criteria andAnlageGreaterThanOrEqualTo(String value) {
            addCriterion("anlage >=", value, "anlage");
            return (Criteria) this;
        }

        public Criteria andAnlageLessThan(String value) {
            addCriterion("anlage <", value, "anlage");
            return (Criteria) this;
        }

        public Criteria andAnlageLessThanOrEqualTo(String value) {
            addCriterion("anlage <=", value, "anlage");
            return (Criteria) this;
        }

        public Criteria andAnlageLike(String value) {
            addCriterion("anlage like", value, "anlage");
            return (Criteria) this;
        }

        public Criteria andAnlageNotLike(String value) {
            addCriterion("anlage not like", value, "anlage");
            return (Criteria) this;
        }

        public Criteria andAnlageIn(List<String> values) {
            addCriterion("anlage in", values, "anlage");
            return (Criteria) this;
        }

        public Criteria andAnlageNotIn(List<String> values) {
            addCriterion("anlage not in", values, "anlage");
            return (Criteria) this;
        }

        public Criteria andAnlageBetween(String value1, String value2) {
            addCriterion("anlage between", value1, value2, "anlage");
            return (Criteria) this;
        }

        public Criteria andAnlageNotBetween(String value1, String value2) {
            addCriterion("anlage not between", value1, value2, "anlage");
            return (Criteria) this;
        }

        public Criteria andBukrsIsNull() {
            addCriterion("bukrs is null");
            return (Criteria) this;
        }

        public Criteria andBukrsIsNotNull() {
            addCriterion("bukrs is not null");
            return (Criteria) this;
        }

        public Criteria andBukrsEqualTo(String value) {
            addCriterion("bukrs =", value, "bukrs");
            return (Criteria) this;
        }

        public Criteria andBukrsNotEqualTo(String value) {
            addCriterion("bukrs <>", value, "bukrs");
            return (Criteria) this;
        }

        public Criteria andBukrsGreaterThan(String value) {
            addCriterion("bukrs >", value, "bukrs");
            return (Criteria) this;
        }

        public Criteria andBukrsGreaterThanOrEqualTo(String value) {
            addCriterion("bukrs >=", value, "bukrs");
            return (Criteria) this;
        }

        public Criteria andBukrsLessThan(String value) {
            addCriterion("bukrs <", value, "bukrs");
            return (Criteria) this;
        }

        public Criteria andBukrsLessThanOrEqualTo(String value) {
            addCriterion("bukrs <=", value, "bukrs");
            return (Criteria) this;
        }

        public Criteria andBukrsLike(String value) {
            addCriterion("bukrs like", value, "bukrs");
            return (Criteria) this;
        }

        public Criteria andBukrsNotLike(String value) {
            addCriterion("bukrs not like", value, "bukrs");
            return (Criteria) this;
        }

        public Criteria andBukrsIn(List<String> values) {
            addCriterion("bukrs in", values, "bukrs");
            return (Criteria) this;
        }

        public Criteria andBukrsNotIn(List<String> values) {
            addCriterion("bukrs not in", values, "bukrs");
            return (Criteria) this;
        }

        public Criteria andBukrsBetween(String value1, String value2) {
            addCriterion("bukrs between", value1, value2, "bukrs");
            return (Criteria) this;
        }

        public Criteria andBukrsNotBetween(String value1, String value2) {
            addCriterion("bukrs not between", value1, value2, "bukrs");
            return (Criteria) this;
        }

        public Criteria andCaculatetyIsNull() {
            addCriterion("caculatety is null");
            return (Criteria) this;
        }

        public Criteria andCaculatetyIsNotNull() {
            addCriterion("caculatety is not null");
            return (Criteria) this;
        }

        public Criteria andCaculatetyEqualTo(String value) {
            addCriterion("caculatety =", value, "caculatety");
            return (Criteria) this;
        }

        public Criteria andCaculatetyNotEqualTo(String value) {
            addCriterion("caculatety <>", value, "caculatety");
            return (Criteria) this;
        }

        public Criteria andCaculatetyGreaterThan(String value) {
            addCriterion("caculatety >", value, "caculatety");
            return (Criteria) this;
        }

        public Criteria andCaculatetyGreaterThanOrEqualTo(String value) {
            addCriterion("caculatety >=", value, "caculatety");
            return (Criteria) this;
        }

        public Criteria andCaculatetyLessThan(String value) {
            addCriterion("caculatety <", value, "caculatety");
            return (Criteria) this;
        }

        public Criteria andCaculatetyLessThanOrEqualTo(String value) {
            addCriterion("caculatety <=", value, "caculatety");
            return (Criteria) this;
        }

        public Criteria andCaculatetyLike(String value) {
            addCriterion("caculatety like", value, "caculatety");
            return (Criteria) this;
        }

        public Criteria andCaculatetyNotLike(String value) {
            addCriterion("caculatety not like", value, "caculatety");
            return (Criteria) this;
        }

        public Criteria andCaculatetyIn(List<String> values) {
            addCriterion("caculatety in", values, "caculatety");
            return (Criteria) this;
        }

        public Criteria andCaculatetyNotIn(List<String> values) {
            addCriterion("caculatety not in", values, "caculatety");
            return (Criteria) this;
        }

        public Criteria andCaculatetyBetween(String value1, String value2) {
            addCriterion("caculatety between", value1, value2, "caculatety");
            return (Criteria) this;
        }

        public Criteria andCaculatetyNotBetween(String value1, String value2) {
            addCriterion("caculatety not between", value1, value2, "caculatety");
            return (Criteria) this;
        }

        public Criteria andDatsIsNull() {
            addCriterion("dats is null");
            return (Criteria) this;
        }

        public Criteria andDatsIsNotNull() {
            addCriterion("dats is not null");
            return (Criteria) this;
        }

        public Criteria andDatsEqualTo(String value) {
            addCriterion("dats =", value, "dats");
            return (Criteria) this;
        }

        public Criteria andDatsNotEqualTo(String value) {
            addCriterion("dats <>", value, "dats");
            return (Criteria) this;
        }

        public Criteria andDatsGreaterThan(String value) {
            addCriterion("dats >", value, "dats");
            return (Criteria) this;
        }

        public Criteria andDatsGreaterThanOrEqualTo(String value) {
            addCriterion("dats >=", value, "dats");
            return (Criteria) this;
        }

        public Criteria andDatsLessThan(String value) {
            addCriterion("dats <", value, "dats");
            return (Criteria) this;
        }

        public Criteria andDatsLessThanOrEqualTo(String value) {
            addCriterion("dats <=", value, "dats");
            return (Criteria) this;
        }

        public Criteria andDatsLike(String value) {
            addCriterion("dats like", value, "dats");
            return (Criteria) this;
        }

        public Criteria andDatsNotLike(String value) {
            addCriterion("dats not like", value, "dats");
            return (Criteria) this;
        }

        public Criteria andDatsIn(List<String> values) {
            addCriterion("dats in", values, "dats");
            return (Criteria) this;
        }

        public Criteria andDatsNotIn(List<String> values) {
            addCriterion("dats not in", values, "dats");
            return (Criteria) this;
        }

        public Criteria andDatsBetween(String value1, String value2) {
            addCriterion("dats between", value1, value2, "dats");
            return (Criteria) this;
        }

        public Criteria andDatsNotBetween(String value1, String value2) {
            addCriterion("dats not between", value1, value2, "dats");
            return (Criteria) this;
        }

        public Criteria andHigpriceIsNull() {
            addCriterion("higprice is null");
            return (Criteria) this;
        }

        public Criteria andHigpriceIsNotNull() {
            addCriterion("higprice is not null");
            return (Criteria) this;
        }

        public Criteria andHigpriceEqualTo(Double value) {
            addCriterion("higprice =", value, "higprice");
            return (Criteria) this;
        }

        public Criteria andHigpriceNotEqualTo(Double value) {
            addCriterion("higprice <>", value, "higprice");
            return (Criteria) this;
        }

        public Criteria andHigpriceGreaterThan(Double value) {
            addCriterion("higprice >", value, "higprice");
            return (Criteria) this;
        }

        public Criteria andHigpriceGreaterThanOrEqualTo(Double value) {
            addCriterion("higprice >=", value, "higprice");
            return (Criteria) this;
        }

        public Criteria andHigpriceLessThan(Double value) {
            addCriterion("higprice <", value, "higprice");
            return (Criteria) this;
        }

        public Criteria andHigpriceLessThanOrEqualTo(Double value) {
            addCriterion("higprice <=", value, "higprice");
            return (Criteria) this;
        }

        public Criteria andHigpriceIn(List<Double> values) {
            addCriterion("higprice in", values, "higprice");
            return (Criteria) this;
        }

        public Criteria andHigpriceNotIn(List<Double> values) {
            addCriterion("higprice not in", values, "higprice");
            return (Criteria) this;
        }

        public Criteria andHigpriceBetween(Double value1, Double value2) {
            addCriterion("higprice between", value1, value2, "higprice");
            return (Criteria) this;
        }

        public Criteria andHigpriceNotBetween(Double value1, Double value2) {
            addCriterion("higprice not between", value1, value2, "higprice");
            return (Criteria) this;
        }

        public Criteria andIZahlIsNull() {
            addCriterion("i_zahl is null");
            return (Criteria) this;
        }

        public Criteria andIZahlIsNotNull() {
            addCriterion("i_zahl is not null");
            return (Criteria) this;
        }

        public Criteria andIZahlEqualTo(String value) {
            addCriterion("i_zahl =", value, "iZahl");
            return (Criteria) this;
        }

        public Criteria andIZahlNotEqualTo(String value) {
            addCriterion("i_zahl <>", value, "iZahl");
            return (Criteria) this;
        }

        public Criteria andIZahlGreaterThan(String value) {
            addCriterion("i_zahl >", value, "iZahl");
            return (Criteria) this;
        }

        public Criteria andIZahlGreaterThanOrEqualTo(String value) {
            addCriterion("i_zahl >=", value, "iZahl");
            return (Criteria) this;
        }

        public Criteria andIZahlLessThan(String value) {
            addCriterion("i_zahl <", value, "iZahl");
            return (Criteria) this;
        }

        public Criteria andIZahlLessThanOrEqualTo(String value) {
            addCriterion("i_zahl <=", value, "iZahl");
            return (Criteria) this;
        }

        public Criteria andIZahlLike(String value) {
            addCriterion("i_zahl like", value, "iZahl");
            return (Criteria) this;
        }

        public Criteria andIZahlNotLike(String value) {
            addCriterion("i_zahl not like", value, "iZahl");
            return (Criteria) this;
        }

        public Criteria andIZahlIn(List<String> values) {
            addCriterion("i_zahl in", values, "iZahl");
            return (Criteria) this;
        }

        public Criteria andIZahlNotIn(List<String> values) {
            addCriterion("i_zahl not in", values, "iZahl");
            return (Criteria) this;
        }

        public Criteria andIZahlBetween(String value1, String value2) {
            addCriterion("i_zahl between", value1, value2, "iZahl");
            return (Criteria) this;
        }

        public Criteria andIZahlNotBetween(String value1, String value2) {
            addCriterion("i_zahl not between", value1, value2, "iZahl");
            return (Criteria) this;
        }

        public Criteria andIZahl2IsNull() {
            addCriterion("i_zahl2 is null");
            return (Criteria) this;
        }

        public Criteria andIZahl2IsNotNull() {
            addCriterion("i_zahl2 is not null");
            return (Criteria) this;
        }

        public Criteria andIZahl2EqualTo(Double value) {
            addCriterion("i_zahl2 =", value, "iZahl2");
            return (Criteria) this;
        }

        public Criteria andIZahl2NotEqualTo(Double value) {
            addCriterion("i_zahl2 <>", value, "iZahl2");
            return (Criteria) this;
        }

        public Criteria andIZahl2GreaterThan(Double value) {
            addCriterion("i_zahl2 >", value, "iZahl2");
            return (Criteria) this;
        }

        public Criteria andIZahl2GreaterThanOrEqualTo(Double value) {
            addCriterion("i_zahl2 >=", value, "iZahl2");
            return (Criteria) this;
        }

        public Criteria andIZahl2LessThan(Double value) {
            addCriterion("i_zahl2 <", value, "iZahl2");
            return (Criteria) this;
        }

        public Criteria andIZahl2LessThanOrEqualTo(Double value) {
            addCriterion("i_zahl2 <=", value, "iZahl2");
            return (Criteria) this;
        }

        public Criteria andIZahl2In(List<Double> values) {
            addCriterion("i_zahl2 in", values, "iZahl2");
            return (Criteria) this;
        }

        public Criteria andIZahl2NotIn(List<Double> values) {
            addCriterion("i_zahl2 not in", values, "iZahl2");
            return (Criteria) this;
        }

        public Criteria andIZahl2Between(Double value1, Double value2) {
            addCriterion("i_zahl2 between", value1, value2, "iZahl2");
            return (Criteria) this;
        }

        public Criteria andIZahl2NotBetween(Double value1, Double value2) {
            addCriterion("i_zahl2 not between", value1, value2, "iZahl2");
            return (Criteria) this;
        }

        public Criteria andIZahl3IsNull() {
            addCriterion("i_zahl3 is null");
            return (Criteria) this;
        }

        public Criteria andIZahl3IsNotNull() {
            addCriterion("i_zahl3 is not null");
            return (Criteria) this;
        }

        public Criteria andIZahl3EqualTo(Double value) {
            addCriterion("i_zahl3 =", value, "iZahl3");
            return (Criteria) this;
        }

        public Criteria andIZahl3NotEqualTo(Double value) {
            addCriterion("i_zahl3 <>", value, "iZahl3");
            return (Criteria) this;
        }

        public Criteria andIZahl3GreaterThan(Double value) {
            addCriterion("i_zahl3 >", value, "iZahl3");
            return (Criteria) this;
        }

        public Criteria andIZahl3GreaterThanOrEqualTo(Double value) {
            addCriterion("i_zahl3 >=", value, "iZahl3");
            return (Criteria) this;
        }

        public Criteria andIZahl3LessThan(Double value) {
            addCriterion("i_zahl3 <", value, "iZahl3");
            return (Criteria) this;
        }

        public Criteria andIZahl3LessThanOrEqualTo(Double value) {
            addCriterion("i_zahl3 <=", value, "iZahl3");
            return (Criteria) this;
        }

        public Criteria andIZahl3In(List<Double> values) {
            addCriterion("i_zahl3 in", values, "iZahl3");
            return (Criteria) this;
        }

        public Criteria andIZahl3NotIn(List<Double> values) {
            addCriterion("i_zahl3 not in", values, "iZahl3");
            return (Criteria) this;
        }

        public Criteria andIZahl3Between(Double value1, Double value2) {
            addCriterion("i_zahl3 between", value1, value2, "iZahl3");
            return (Criteria) this;
        }

        public Criteria andIZahl3NotBetween(Double value1, Double value2) {
            addCriterion("i_zahl3 not between", value1, value2, "iZahl3");
            return (Criteria) this;
        }

        public Criteria andIcZahlIsNull() {
            addCriterion("ic_zahl is null");
            return (Criteria) this;
        }

        public Criteria andIcZahlIsNotNull() {
            addCriterion("ic_zahl is not null");
            return (Criteria) this;
        }

        public Criteria andIcZahlEqualTo(Double value) {
            addCriterion("ic_zahl =", value, "icZahl");
            return (Criteria) this;
        }

        public Criteria andIcZahlNotEqualTo(Double value) {
            addCriterion("ic_zahl <>", value, "icZahl");
            return (Criteria) this;
        }

        public Criteria andIcZahlGreaterThan(Double value) {
            addCriterion("ic_zahl >", value, "icZahl");
            return (Criteria) this;
        }

        public Criteria andIcZahlGreaterThanOrEqualTo(Double value) {
            addCriterion("ic_zahl >=", value, "icZahl");
            return (Criteria) this;
        }

        public Criteria andIcZahlLessThan(Double value) {
            addCriterion("ic_zahl <", value, "icZahl");
            return (Criteria) this;
        }

        public Criteria andIcZahlLessThanOrEqualTo(Double value) {
            addCriterion("ic_zahl <=", value, "icZahl");
            return (Criteria) this;
        }

        public Criteria andIcZahlIn(List<Double> values) {
            addCriterion("ic_zahl in", values, "icZahl");
            return (Criteria) this;
        }

        public Criteria andIcZahlNotIn(List<Double> values) {
            addCriterion("ic_zahl not in", values, "icZahl");
            return (Criteria) this;
        }

        public Criteria andIcZahlBetween(Double value1, Double value2) {
            addCriterion("ic_zahl between", value1, value2, "icZahl");
            return (Criteria) this;
        }

        public Criteria andIcZahlNotBetween(Double value1, Double value2) {
            addCriterion("ic_zahl not between", value1, value2, "icZahl");
            return (Criteria) this;
        }

        public Criteria andIcZahl2IsNull() {
            addCriterion("ic_zahl2 is null");
            return (Criteria) this;
        }

        public Criteria andIcZahl2IsNotNull() {
            addCriterion("ic_zahl2 is not null");
            return (Criteria) this;
        }

        public Criteria andIcZahl2EqualTo(Double value) {
            addCriterion("ic_zahl2 =", value, "icZahl2");
            return (Criteria) this;
        }

        public Criteria andIcZahl2NotEqualTo(Double value) {
            addCriterion("ic_zahl2 <>", value, "icZahl2");
            return (Criteria) this;
        }

        public Criteria andIcZahl2GreaterThan(Double value) {
            addCriterion("ic_zahl2 >", value, "icZahl2");
            return (Criteria) this;
        }

        public Criteria andIcZahl2GreaterThanOrEqualTo(Double value) {
            addCriterion("ic_zahl2 >=", value, "icZahl2");
            return (Criteria) this;
        }

        public Criteria andIcZahl2LessThan(Double value) {
            addCriterion("ic_zahl2 <", value, "icZahl2");
            return (Criteria) this;
        }

        public Criteria andIcZahl2LessThanOrEqualTo(Double value) {
            addCriterion("ic_zahl2 <=", value, "icZahl2");
            return (Criteria) this;
        }

        public Criteria andIcZahl2In(List<Double> values) {
            addCriterion("ic_zahl2 in", values, "icZahl2");
            return (Criteria) this;
        }

        public Criteria andIcZahl2NotIn(List<Double> values) {
            addCriterion("ic_zahl2 not in", values, "icZahl2");
            return (Criteria) this;
        }

        public Criteria andIcZahl2Between(Double value1, Double value2) {
            addCriterion("ic_zahl2 between", value1, value2, "icZahl2");
            return (Criteria) this;
        }

        public Criteria andIcZahl2NotBetween(Double value1, Double value2) {
            addCriterion("ic_zahl2 not between", value1, value2, "icZahl2");
            return (Criteria) this;
        }

        public Criteria andIcZahl3IsNull() {
            addCriterion("ic_zahl3 is null");
            return (Criteria) this;
        }

        public Criteria andIcZahl3IsNotNull() {
            addCriterion("ic_zahl3 is not null");
            return (Criteria) this;
        }

        public Criteria andIcZahl3EqualTo(Double value) {
            addCriterion("ic_zahl3 =", value, "icZahl3");
            return (Criteria) this;
        }

        public Criteria andIcZahl3NotEqualTo(Double value) {
            addCriterion("ic_zahl3 <>", value, "icZahl3");
            return (Criteria) this;
        }

        public Criteria andIcZahl3GreaterThan(Double value) {
            addCriterion("ic_zahl3 >", value, "icZahl3");
            return (Criteria) this;
        }

        public Criteria andIcZahl3GreaterThanOrEqualTo(Double value) {
            addCriterion("ic_zahl3 >=", value, "icZahl3");
            return (Criteria) this;
        }

        public Criteria andIcZahl3LessThan(Double value) {
            addCriterion("ic_zahl3 <", value, "icZahl3");
            return (Criteria) this;
        }

        public Criteria andIcZahl3LessThanOrEqualTo(Double value) {
            addCriterion("ic_zahl3 <=", value, "icZahl3");
            return (Criteria) this;
        }

        public Criteria andIcZahl3In(List<Double> values) {
            addCriterion("ic_zahl3 in", values, "icZahl3");
            return (Criteria) this;
        }

        public Criteria andIcZahl3NotIn(List<Double> values) {
            addCriterion("ic_zahl3 not in", values, "icZahl3");
            return (Criteria) this;
        }

        public Criteria andIcZahl3Between(Double value1, Double value2) {
            addCriterion("ic_zahl3 between", value1, value2, "icZahl3");
            return (Criteria) this;
        }

        public Criteria andIcZahl3NotBetween(Double value1, Double value2) {
            addCriterion("ic_zahl3 not between", value1, value2, "icZahl3");
            return (Criteria) this;
        }

        public Criteria andIcmonIsNull() {
            addCriterion("icmon is null");
            return (Criteria) this;
        }

        public Criteria andIcmonIsNotNull() {
            addCriterion("icmon is not null");
            return (Criteria) this;
        }

        public Criteria andIcmonEqualTo(Double value) {
            addCriterion("icmon =", value, "icmon");
            return (Criteria) this;
        }

        public Criteria andIcmonNotEqualTo(Double value) {
            addCriterion("icmon <>", value, "icmon");
            return (Criteria) this;
        }

        public Criteria andIcmonGreaterThan(Double value) {
            addCriterion("icmon >", value, "icmon");
            return (Criteria) this;
        }

        public Criteria andIcmonGreaterThanOrEqualTo(Double value) {
            addCriterion("icmon >=", value, "icmon");
            return (Criteria) this;
        }

        public Criteria andIcmonLessThan(Double value) {
            addCriterion("icmon <", value, "icmon");
            return (Criteria) this;
        }

        public Criteria andIcmonLessThanOrEqualTo(Double value) {
            addCriterion("icmon <=", value, "icmon");
            return (Criteria) this;
        }

        public Criteria andIcmonIn(List<Double> values) {
            addCriterion("icmon in", values, "icmon");
            return (Criteria) this;
        }

        public Criteria andIcmonNotIn(List<Double> values) {
            addCriterion("icmon not in", values, "icmon");
            return (Criteria) this;
        }

        public Criteria andIcmonBetween(Double value1, Double value2) {
            addCriterion("icmon between", value1, value2, "icmon");
            return (Criteria) this;
        }

        public Criteria andIcmonNotBetween(Double value1, Double value2) {
            addCriterion("icmon not between", value1, value2, "icmon");
            return (Criteria) this;
        }

        public Criteria andJtbzIsNull() {
            addCriterion("jtbz is null");
            return (Criteria) this;
        }

        public Criteria andJtbzIsNotNull() {
            addCriterion("jtbz is not null");
            return (Criteria) this;
        }

        public Criteria andJtbzEqualTo(String value) {
            addCriterion("jtbz =", value, "jtbz");
            return (Criteria) this;
        }

        public Criteria andJtbzNotEqualTo(String value) {
            addCriterion("jtbz <>", value, "jtbz");
            return (Criteria) this;
        }

        public Criteria andJtbzGreaterThan(String value) {
            addCriterion("jtbz >", value, "jtbz");
            return (Criteria) this;
        }

        public Criteria andJtbzGreaterThanOrEqualTo(String value) {
            addCriterion("jtbz >=", value, "jtbz");
            return (Criteria) this;
        }

        public Criteria andJtbzLessThan(String value) {
            addCriterion("jtbz <", value, "jtbz");
            return (Criteria) this;
        }

        public Criteria andJtbzLessThanOrEqualTo(String value) {
            addCriterion("jtbz <=", value, "jtbz");
            return (Criteria) this;
        }

        public Criteria andJtbzLike(String value) {
            addCriterion("jtbz like", value, "jtbz");
            return (Criteria) this;
        }

        public Criteria andJtbzNotLike(String value) {
            addCriterion("jtbz not like", value, "jtbz");
            return (Criteria) this;
        }

        public Criteria andJtbzIn(List<String> values) {
            addCriterion("jtbz in", values, "jtbz");
            return (Criteria) this;
        }

        public Criteria andJtbzNotIn(List<String> values) {
            addCriterion("jtbz not in", values, "jtbz");
            return (Criteria) this;
        }

        public Criteria andJtbzBetween(String value1, String value2) {
            addCriterion("jtbz between", value1, value2, "jtbz");
            return (Criteria) this;
        }

        public Criteria andJtbzNotBetween(String value1, String value2) {
            addCriterion("jtbz not between", value1, value2, "jtbz");
            return (Criteria) this;
        }

        public Criteria andJtlevlIsNull() {
            addCriterion("jtlevl is null");
            return (Criteria) this;
        }

        public Criteria andJtlevlIsNotNull() {
            addCriterion("jtlevl is not null");
            return (Criteria) this;
        }

        public Criteria andJtlevlEqualTo(String value) {
            addCriterion("jtlevl =", value, "jtlevl");
            return (Criteria) this;
        }

        public Criteria andJtlevlNotEqualTo(String value) {
            addCriterion("jtlevl <>", value, "jtlevl");
            return (Criteria) this;
        }

        public Criteria andJtlevlGreaterThan(String value) {
            addCriterion("jtlevl >", value, "jtlevl");
            return (Criteria) this;
        }

        public Criteria andJtlevlGreaterThanOrEqualTo(String value) {
            addCriterion("jtlevl >=", value, "jtlevl");
            return (Criteria) this;
        }

        public Criteria andJtlevlLessThan(String value) {
            addCriterion("jtlevl <", value, "jtlevl");
            return (Criteria) this;
        }

        public Criteria andJtlevlLessThanOrEqualTo(String value) {
            addCriterion("jtlevl <=", value, "jtlevl");
            return (Criteria) this;
        }

        public Criteria andJtlevlLike(String value) {
            addCriterion("jtlevl like", value, "jtlevl");
            return (Criteria) this;
        }

        public Criteria andJtlevlNotLike(String value) {
            addCriterion("jtlevl not like", value, "jtlevl");
            return (Criteria) this;
        }

        public Criteria andJtlevlIn(List<String> values) {
            addCriterion("jtlevl in", values, "jtlevl");
            return (Criteria) this;
        }

        public Criteria andJtlevlNotIn(List<String> values) {
            addCriterion("jtlevl not in", values, "jtlevl");
            return (Criteria) this;
        }

        public Criteria andJtlevlBetween(String value1, String value2) {
            addCriterion("jtlevl between", value1, value2, "jtlevl");
            return (Criteria) this;
        }

        public Criteria andJtlevlNotBetween(String value1, String value2) {
            addCriterion("jtlevl not between", value1, value2, "jtlevl");
            return (Criteria) this;
        }

        public Criteria andLaedaIsNull() {
            addCriterion("laeda is null");
            return (Criteria) this;
        }

        public Criteria andLaedaIsNotNull() {
            addCriterion("laeda is not null");
            return (Criteria) this;
        }

        public Criteria andLaedaEqualTo(String value) {
            addCriterion("laeda =", value, "laeda");
            return (Criteria) this;
        }

        public Criteria andLaedaNotEqualTo(String value) {
            addCriterion("laeda <>", value, "laeda");
            return (Criteria) this;
        }

        public Criteria andLaedaGreaterThan(String value) {
            addCriterion("laeda >", value, "laeda");
            return (Criteria) this;
        }

        public Criteria andLaedaGreaterThanOrEqualTo(String value) {
            addCriterion("laeda >=", value, "laeda");
            return (Criteria) this;
        }

        public Criteria andLaedaLessThan(String value) {
            addCriterion("laeda <", value, "laeda");
            return (Criteria) this;
        }

        public Criteria andLaedaLessThanOrEqualTo(String value) {
            addCriterion("laeda <=", value, "laeda");
            return (Criteria) this;
        }

        public Criteria andLaedaLike(String value) {
            addCriterion("laeda like", value, "laeda");
            return (Criteria) this;
        }

        public Criteria andLaedaNotLike(String value) {
            addCriterion("laeda not like", value, "laeda");
            return (Criteria) this;
        }

        public Criteria andLaedaIn(List<String> values) {
            addCriterion("laeda in", values, "laeda");
            return (Criteria) this;
        }

        public Criteria andLaedaNotIn(List<String> values) {
            addCriterion("laeda not in", values, "laeda");
            return (Criteria) this;
        }

        public Criteria andLaedaBetween(String value1, String value2) {
            addCriterion("laeda between", value1, value2, "laeda");
            return (Criteria) this;
        }

        public Criteria andLaedaNotBetween(String value1, String value2) {
            addCriterion("laeda not between", value1, value2, "laeda");
            return (Criteria) this;
        }

        public Criteria andLowpriceIsNull() {
            addCriterion("lowprice is null");
            return (Criteria) this;
        }

        public Criteria andLowpriceIsNotNull() {
            addCriterion("lowprice is not null");
            return (Criteria) this;
        }

        public Criteria andLowpriceEqualTo(Double value) {
            addCriterion("lowprice =", value, "lowprice");
            return (Criteria) this;
        }

        public Criteria andLowpriceNotEqualTo(Double value) {
            addCriterion("lowprice <>", value, "lowprice");
            return (Criteria) this;
        }

        public Criteria andLowpriceGreaterThan(Double value) {
            addCriterion("lowprice >", value, "lowprice");
            return (Criteria) this;
        }

        public Criteria andLowpriceGreaterThanOrEqualTo(Double value) {
            addCriterion("lowprice >=", value, "lowprice");
            return (Criteria) this;
        }

        public Criteria andLowpriceLessThan(Double value) {
            addCriterion("lowprice <", value, "lowprice");
            return (Criteria) this;
        }

        public Criteria andLowpriceLessThanOrEqualTo(Double value) {
            addCriterion("lowprice <=", value, "lowprice");
            return (Criteria) this;
        }

        public Criteria andLowpriceIn(List<Double> values) {
            addCriterion("lowprice in", values, "lowprice");
            return (Criteria) this;
        }

        public Criteria andLowpriceNotIn(List<Double> values) {
            addCriterion("lowprice not in", values, "lowprice");
            return (Criteria) this;
        }

        public Criteria andLowpriceBetween(Double value1, Double value2) {
            addCriterion("lowprice between", value1, value2, "lowprice");
            return (Criteria) this;
        }

        public Criteria andLowpriceNotBetween(Double value1, Double value2) {
            addCriterion("lowprice not between", value1, value2, "lowprice");
            return (Criteria) this;
        }

        public Criteria andMorpriceIsNull() {
            addCriterion("morprice is null");
            return (Criteria) this;
        }

        public Criteria andMorpriceIsNotNull() {
            addCriterion("morprice is not null");
            return (Criteria) this;
        }

        public Criteria andMorpriceEqualTo(Double value) {
            addCriterion("morprice =", value, "morprice");
            return (Criteria) this;
        }

        public Criteria andMorpriceNotEqualTo(Double value) {
            addCriterion("morprice <>", value, "morprice");
            return (Criteria) this;
        }

        public Criteria andMorpriceGreaterThan(Double value) {
            addCriterion("morprice >", value, "morprice");
            return (Criteria) this;
        }

        public Criteria andMorpriceGreaterThanOrEqualTo(Double value) {
            addCriterion("morprice >=", value, "morprice");
            return (Criteria) this;
        }

        public Criteria andMorpriceLessThan(Double value) {
            addCriterion("morprice <", value, "morprice");
            return (Criteria) this;
        }

        public Criteria andMorpriceLessThanOrEqualTo(Double value) {
            addCriterion("morprice <=", value, "morprice");
            return (Criteria) this;
        }

        public Criteria andMorpriceIn(List<Double> values) {
            addCriterion("morprice in", values, "morprice");
            return (Criteria) this;
        }

        public Criteria andMorpriceNotIn(List<Double> values) {
            addCriterion("morprice not in", values, "morprice");
            return (Criteria) this;
        }

        public Criteria andMorpriceBetween(Double value1, Double value2) {
            addCriterion("morprice between", value1, value2, "morprice");
            return (Criteria) this;
        }

        public Criteria andMorpriceNotBetween(Double value1, Double value2) {
            addCriterion("morprice not between", value1, value2, "morprice");
            return (Criteria) this;
        }

        public Criteria andPlanIdIsNull() {
            addCriterion("plan_id is null");
            return (Criteria) this;
        }

        public Criteria andPlanIdIsNotNull() {
            addCriterion("plan_id is not null");
            return (Criteria) this;
        }

        public Criteria andPlanIdEqualTo(Integer value) {
            addCriterion("plan_id =", value, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdNotEqualTo(Integer value) {
            addCriterion("plan_id <>", value, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdGreaterThan(Integer value) {
            addCriterion("plan_id >", value, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("plan_id >=", value, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdLessThan(Integer value) {
            addCriterion("plan_id <", value, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdLessThanOrEqualTo(Integer value) {
            addCriterion("plan_id <=", value, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdIn(List<Integer> values) {
            addCriterion("plan_id in", values, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdNotIn(List<Integer> values) {
            addCriterion("plan_id not in", values, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdBetween(Integer value1, Integer value2) {
            addCriterion("plan_id between", value1, value2, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdNotBetween(Integer value1, Integer value2) {
            addCriterion("plan_id not between", value1, value2, "planId");
            return (Criteria) this;
        }

        public Criteria andQsyueIsNull() {
            addCriterion("qsyue is null");
            return (Criteria) this;
        }

        public Criteria andQsyueIsNotNull() {
            addCriterion("qsyue is not null");
            return (Criteria) this;
        }

        public Criteria andQsyueEqualTo(String value) {
            addCriterion("qsyue =", value, "qsyue");
            return (Criteria) this;
        }

        public Criteria andQsyueNotEqualTo(String value) {
            addCriterion("qsyue <>", value, "qsyue");
            return (Criteria) this;
        }

        public Criteria andQsyueGreaterThan(String value) {
            addCriterion("qsyue >", value, "qsyue");
            return (Criteria) this;
        }

        public Criteria andQsyueGreaterThanOrEqualTo(String value) {
            addCriterion("qsyue >=", value, "qsyue");
            return (Criteria) this;
        }

        public Criteria andQsyueLessThan(String value) {
            addCriterion("qsyue <", value, "qsyue");
            return (Criteria) this;
        }

        public Criteria andQsyueLessThanOrEqualTo(String value) {
            addCriterion("qsyue <=", value, "qsyue");
            return (Criteria) this;
        }

        public Criteria andQsyueLike(String value) {
            addCriterion("qsyue like", value, "qsyue");
            return (Criteria) this;
        }

        public Criteria andQsyueNotLike(String value) {
            addCriterion("qsyue not like", value, "qsyue");
            return (Criteria) this;
        }

        public Criteria andQsyueIn(List<String> values) {
            addCriterion("qsyue in", values, "qsyue");
            return (Criteria) this;
        }

        public Criteria andQsyueNotIn(List<String> values) {
            addCriterion("qsyue not in", values, "qsyue");
            return (Criteria) this;
        }

        public Criteria andQsyueBetween(String value1, String value2) {
            addCriterion("qsyue between", value1, value2, "qsyue");
            return (Criteria) this;
        }

        public Criteria andQsyueNotBetween(String value1, String value2) {
            addCriterion("qsyue not between", value1, value2, "qsyue");
            return (Criteria) this;
        }

        public Criteria andRespriceIsNull() {
            addCriterion("resprice is null");
            return (Criteria) this;
        }

        public Criteria andRespriceIsNotNull() {
            addCriterion("resprice is not null");
            return (Criteria) this;
        }

        public Criteria andRespriceEqualTo(Double value) {
            addCriterion("resprice =", value, "resprice");
            return (Criteria) this;
        }

        public Criteria andRespriceNotEqualTo(Double value) {
            addCriterion("resprice <>", value, "resprice");
            return (Criteria) this;
        }

        public Criteria andRespriceGreaterThan(Double value) {
            addCriterion("resprice >", value, "resprice");
            return (Criteria) this;
        }

        public Criteria andRespriceGreaterThanOrEqualTo(Double value) {
            addCriterion("resprice >=", value, "resprice");
            return (Criteria) this;
        }

        public Criteria andRespriceLessThan(Double value) {
            addCriterion("resprice <", value, "resprice");
            return (Criteria) this;
        }

        public Criteria andRespriceLessThanOrEqualTo(Double value) {
            addCriterion("resprice <=", value, "resprice");
            return (Criteria) this;
        }

        public Criteria andRespriceIn(List<Double> values) {
            addCriterion("resprice in", values, "resprice");
            return (Criteria) this;
        }

        public Criteria andRespriceNotIn(List<Double> values) {
            addCriterion("resprice not in", values, "resprice");
            return (Criteria) this;
        }

        public Criteria andRespriceBetween(Double value1, Double value2) {
            addCriterion("resprice between", value1, value2, "resprice");
            return (Criteria) this;
        }

        public Criteria andRespriceNotBetween(Double value1, Double value2) {
            addCriterion("resprice not between", value1, value2, "resprice");
            return (Criteria) this;
        }

        public Criteria andStepMethdIsNull() {
            addCriterion("step_methd is null");
            return (Criteria) this;
        }

        public Criteria andStepMethdIsNotNull() {
            addCriterion("step_methd is not null");
            return (Criteria) this;
        }

        public Criteria andStepMethdEqualTo(String value) {
            addCriterion("step_methd =", value, "stepMethd");
            return (Criteria) this;
        }

        public Criteria andStepMethdNotEqualTo(String value) {
            addCriterion("step_methd <>", value, "stepMethd");
            return (Criteria) this;
        }

        public Criteria andStepMethdGreaterThan(String value) {
            addCriterion("step_methd >", value, "stepMethd");
            return (Criteria) this;
        }

        public Criteria andStepMethdGreaterThanOrEqualTo(String value) {
            addCriterion("step_methd >=", value, "stepMethd");
            return (Criteria) this;
        }

        public Criteria andStepMethdLessThan(String value) {
            addCriterion("step_methd <", value, "stepMethd");
            return (Criteria) this;
        }

        public Criteria andStepMethdLessThanOrEqualTo(String value) {
            addCriterion("step_methd <=", value, "stepMethd");
            return (Criteria) this;
        }

        public Criteria andStepMethdLike(String value) {
            addCriterion("step_methd like", value, "stepMethd");
            return (Criteria) this;
        }

        public Criteria andStepMethdNotLike(String value) {
            addCriterion("step_methd not like", value, "stepMethd");
            return (Criteria) this;
        }

        public Criteria andStepMethdIn(List<String> values) {
            addCriterion("step_methd in", values, "stepMethd");
            return (Criteria) this;
        }

        public Criteria andStepMethdNotIn(List<String> values) {
            addCriterion("step_methd not in", values, "stepMethd");
            return (Criteria) this;
        }

        public Criteria andStepMethdBetween(String value1, String value2) {
            addCriterion("step_methd between", value1, value2, "stepMethd");
            return (Criteria) this;
        }

        public Criteria andStepMethdNotBetween(String value1, String value2) {
            addCriterion("step_methd not between", value1, value2, "stepMethd");
            return (Criteria) this;
        }

        public Criteria andTariftypIsNull() {
            addCriterion("tariftyp is null");
            return (Criteria) this;
        }

        public Criteria andTariftypIsNotNull() {
            addCriterion("tariftyp is not null");
            return (Criteria) this;
        }

        public Criteria andTariftypEqualTo(String value) {
            addCriterion("tariftyp =", value, "tariftyp");
            return (Criteria) this;
        }

        public Criteria andTariftypNotEqualTo(String value) {
            addCriterion("tariftyp <>", value, "tariftyp");
            return (Criteria) this;
        }

        public Criteria andTariftypGreaterThan(String value) {
            addCriterion("tariftyp >", value, "tariftyp");
            return (Criteria) this;
        }

        public Criteria andTariftypGreaterThanOrEqualTo(String value) {
            addCriterion("tariftyp >=", value, "tariftyp");
            return (Criteria) this;
        }

        public Criteria andTariftypLessThan(String value) {
            addCriterion("tariftyp <", value, "tariftyp");
            return (Criteria) this;
        }

        public Criteria andTariftypLessThanOrEqualTo(String value) {
            addCriterion("tariftyp <=", value, "tariftyp");
            return (Criteria) this;
        }

        public Criteria andTariftypLike(String value) {
            addCriterion("tariftyp like", value, "tariftyp");
            return (Criteria) this;
        }

        public Criteria andTariftypNotLike(String value) {
            addCriterion("tariftyp not like", value, "tariftyp");
            return (Criteria) this;
        }

        public Criteria andTariftypIn(List<String> values) {
            addCriterion("tariftyp in", values, "tariftyp");
            return (Criteria) this;
        }

        public Criteria andTariftypNotIn(List<String> values) {
            addCriterion("tariftyp not in", values, "tariftyp");
            return (Criteria) this;
        }

        public Criteria andTariftypBetween(String value1, String value2) {
            addCriterion("tariftyp between", value1, value2, "tariftyp");
            return (Criteria) this;
        }

        public Criteria andTariftypNotBetween(String value1, String value2) {
            addCriterion("tariftyp not between", value1, value2, "tariftyp");
            return (Criteria) this;
        }

        public Criteria andXuhaoIsNull() {
            addCriterion("xuhao is null");
            return (Criteria) this;
        }

        public Criteria andXuhaoIsNotNull() {
            addCriterion("xuhao is not null");
            return (Criteria) this;
        }

        public Criteria andXuhaoEqualTo(String value) {
            addCriterion("xuhao =", value, "xuhao");
            return (Criteria) this;
        }

        public Criteria andXuhaoNotEqualTo(String value) {
            addCriterion("xuhao <>", value, "xuhao");
            return (Criteria) this;
        }

        public Criteria andXuhaoGreaterThan(String value) {
            addCriterion("xuhao >", value, "xuhao");
            return (Criteria) this;
        }

        public Criteria andXuhaoGreaterThanOrEqualTo(String value) {
            addCriterion("xuhao >=", value, "xuhao");
            return (Criteria) this;
        }

        public Criteria andXuhaoLessThan(String value) {
            addCriterion("xuhao <", value, "xuhao");
            return (Criteria) this;
        }

        public Criteria andXuhaoLessThanOrEqualTo(String value) {
            addCriterion("xuhao <=", value, "xuhao");
            return (Criteria) this;
        }

        public Criteria andXuhaoLike(String value) {
            addCriterion("xuhao like", value, "xuhao");
            return (Criteria) this;
        }

        public Criteria andXuhaoNotLike(String value) {
            addCriterion("xuhao not like", value, "xuhao");
            return (Criteria) this;
        }

        public Criteria andXuhaoIn(List<String> values) {
            addCriterion("xuhao in", values, "xuhao");
            return (Criteria) this;
        }

        public Criteria andXuhaoNotIn(List<String> values) {
            addCriterion("xuhao not in", values, "xuhao");
            return (Criteria) this;
        }

        public Criteria andXuhaoBetween(String value1, String value2) {
            addCriterion("xuhao between", value1, value2, "xuhao");
            return (Criteria) this;
        }

        public Criteria andXuhaoNotBetween(String value1, String value2) {
            addCriterion("xuhao not between", value1, value2, "xuhao");
            return (Criteria) this;
        }

        public Criteria andZzyueIsNull() {
            addCriterion("zzyue is null");
            return (Criteria) this;
        }

        public Criteria andZzyueIsNotNull() {
            addCriterion("zzyue is not null");
            return (Criteria) this;
        }

        public Criteria andZzyueEqualTo(String value) {
            addCriterion("zzyue =", value, "zzyue");
            return (Criteria) this;
        }

        public Criteria andZzyueNotEqualTo(String value) {
            addCriterion("zzyue <>", value, "zzyue");
            return (Criteria) this;
        }

        public Criteria andZzyueGreaterThan(String value) {
            addCriterion("zzyue >", value, "zzyue");
            return (Criteria) this;
        }

        public Criteria andZzyueGreaterThanOrEqualTo(String value) {
            addCriterion("zzyue >=", value, "zzyue");
            return (Criteria) this;
        }

        public Criteria andZzyueLessThan(String value) {
            addCriterion("zzyue <", value, "zzyue");
            return (Criteria) this;
        }

        public Criteria andZzyueLessThanOrEqualTo(String value) {
            addCriterion("zzyue <=", value, "zzyue");
            return (Criteria) this;
        }

        public Criteria andZzyueLike(String value) {
            addCriterion("zzyue like", value, "zzyue");
            return (Criteria) this;
        }

        public Criteria andZzyueNotLike(String value) {
            addCriterion("zzyue not like", value, "zzyue");
            return (Criteria) this;
        }

        public Criteria andZzyueIn(List<String> values) {
            addCriterion("zzyue in", values, "zzyue");
            return (Criteria) this;
        }

        public Criteria andZzyueNotIn(List<String> values) {
            addCriterion("zzyue not in", values, "zzyue");
            return (Criteria) this;
        }

        public Criteria andZzyueBetween(String value1, String value2) {
            addCriterion("zzyue between", value1, value2, "zzyue");
            return (Criteria) this;
        }

        public Criteria andZzyueNotBetween(String value1, String value2) {
            addCriterion("zzyue not between", value1, value2, "zzyue");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ichprice
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ichprice
     *
     * @mbg.generated
     */
    public static class Criterion implements Serializable {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}