package com.ecej.po;

import java.io.Serializable;

/**
 * Created by wyx on 2017-10-09.
 * 
 * @author wyx
 * @title ichreadingplan
 * @date 2017-10-09
 */
public class ICHReadingPlan implements Serializable {
    /**
     * 
     * id 
     * id
     */
    private Integer id;

    /**
     * 
     * ableser 
     * ableser
     */
    private String ableser;

    /**
     * 
     * ablesgr 
     * ablesgr
     */
    private String ablesgr;

    /**
     * 
     * ablesgre 
     * ablesgre
     */
    private String ablesgre;

    /**
     * 
     * adatsoll 
     * adatsoll
     */
    private String adatsoll;

    /**
     * 
     * adattats 
     * adattats
     */
    private String adattats;

    /**
     * 
     * adcbtms 
     * adcbtms
     */
    private String adcbtms;

    /**
     * 
     * anlage 
     * anlage
     */
    private String anlage;

    /**
     * 
     * begru 
     * begru
     */
    private String begru;

    /**
     * 
     * bkdzljll 
     * bkdzljll
     */
    private Double bkdzljll;

    /**
     * 
     * bkssll 
     * bkssll
     */
    private Double bkssll;

    /**
     * 
     * bkzlljll 
     * bkzlljll
     */
    private Double bkzlljll;

    /**
     * 
     * bukrs 
     * bukrs
     */
    private String bukrs;

    /**
     * 
     * cbpl 
     * cbpl
     */
    private String cbpl;

    /**
     * 
     * cbplt 
     * cbplt
     */
    private String cbplt;

    /**
     * 
     * dataflg 
     * dataflg
     */
    private String dataflg;

    /**
     * 
     * expired 
     * expired
     */
    private String expired;

    /**
     * 
     * gkssll 
     * gkssll
     */
    private Double gkssll;

    /**
     * 
     * icdigit 
     * icdigit
     */
    private Double icdigit;

    /**
     * 
     * lbkdzljll 
     * lbkdzljll
     */
    private Double lbkdzljll;

    /**
     * 
     * meins 
     * meins
     */
    private Double meins;

    /**
     * 
     * nZwstndab 
     * n_zwstndab
     */
    private Double nZwstndab;

    /**
     * 
     * note 
     * note
     */
    private String note;

    /**
     * 
     * opeMr 
     * ope_mr
     */
    private String opeMr;

    /**
     * 
     * opnum 
     * opnum
     */
    private String opnum;

    /**
     * 
     * pernr 
     * pernr
     */
    private String pernr;

    /**
     * 
     * pressure 
     * pressure
     */
    private Double pressure;

    /**
     * 
     * readingtime 
     * readingtime
     */
    private String readingtime;

    /**
     * 
     * returntime 
     * returntime
     */
    private String returntime;

    /**
     * 
     * scjhrq 
     * scjhrq
     */
    private String scjhrq;

    /**
     * 
     * scjhtm 
     * scjhtm
     */
    private String scjhtm;

    /**
     * 
     * tempearture 
     * tempearture
     */
    private Double tempearture;

    /**
     * 
     * termschl 
     * termschl
     */
    private String termschl;

    /**
     * 
     * uploadFlag 
     * upload_flag
     */
    private String uploadFlag;

    /**
     * 
     * vZwstndab 
     * v_zwstndab
     */
    private Double vZwstndab;

    /**
     * 
     * zwnummer 
     * zwnummer
     */
    private String zwnummer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ichreadingplan
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichreadingplan.id
     *
     * @return the value of ichreadingplan.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichreadingplan.id
     *
     * @param id the value for ichreadingplan.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichreadingplan.ableser
     *
     * @return the value of ichreadingplan.ableser
     *
     * @mbg.generated
     */
    public String getAbleser() {
        return ableser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichreadingplan.ableser
     *
     * @param ableser the value for ichreadingplan.ableser
     *
     * @mbg.generated
     */
    public void setAbleser(String ableser) {
        this.ableser = ableser == null ? null : ableser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichreadingplan.ablesgr
     *
     * @return the value of ichreadingplan.ablesgr
     *
     * @mbg.generated
     */
    public String getAblesgr() {
        return ablesgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichreadingplan.ablesgr
     *
     * @param ablesgr the value for ichreadingplan.ablesgr
     *
     * @mbg.generated
     */
    public void setAblesgr(String ablesgr) {
        this.ablesgr = ablesgr == null ? null : ablesgr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichreadingplan.ablesgre
     *
     * @return the value of ichreadingplan.ablesgre
     *
     * @mbg.generated
     */
    public String getAblesgre() {
        return ablesgre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichreadingplan.ablesgre
     *
     * @param ablesgre the value for ichreadingplan.ablesgre
     *
     * @mbg.generated
     */
    public void setAblesgre(String ablesgre) {
        this.ablesgre = ablesgre == null ? null : ablesgre.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichreadingplan.adatsoll
     *
     * @return the value of ichreadingplan.adatsoll
     *
     * @mbg.generated
     */
    public String getAdatsoll() {
        return adatsoll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichreadingplan.adatsoll
     *
     * @param adatsoll the value for ichreadingplan.adatsoll
     *
     * @mbg.generated
     */
    public void setAdatsoll(String adatsoll) {
        this.adatsoll = adatsoll == null ? null : adatsoll.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichreadingplan.adattats
     *
     * @return the value of ichreadingplan.adattats
     *
     * @mbg.generated
     */
    public String getAdattats() {
        return adattats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichreadingplan.adattats
     *
     * @param adattats the value for ichreadingplan.adattats
     *
     * @mbg.generated
     */
    public void setAdattats(String adattats) {
        this.adattats = adattats == null ? null : adattats.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichreadingplan.adcbtms
     *
     * @return the value of ichreadingplan.adcbtms
     *
     * @mbg.generated
     */
    public String getAdcbtms() {
        return adcbtms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichreadingplan.adcbtms
     *
     * @param adcbtms the value for ichreadingplan.adcbtms
     *
     * @mbg.generated
     */
    public void setAdcbtms(String adcbtms) {
        this.adcbtms = adcbtms == null ? null : adcbtms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichreadingplan.anlage
     *
     * @return the value of ichreadingplan.anlage
     *
     * @mbg.generated
     */
    public String getAnlage() {
        return anlage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichreadingplan.anlage
     *
     * @param anlage the value for ichreadingplan.anlage
     *
     * @mbg.generated
     */
    public void setAnlage(String anlage) {
        this.anlage = anlage == null ? null : anlage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichreadingplan.begru
     *
     * @return the value of ichreadingplan.begru
     *
     * @mbg.generated
     */
    public String getBegru() {
        return begru;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichreadingplan.begru
     *
     * @param begru the value for ichreadingplan.begru
     *
     * @mbg.generated
     */
    public void setBegru(String begru) {
        this.begru = begru == null ? null : begru.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichreadingplan.bkdzljll
     *
     * @return the value of ichreadingplan.bkdzljll
     *
     * @mbg.generated
     */
    public Double getBkdzljll() {
        return bkdzljll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichreadingplan.bkdzljll
     *
     * @param bkdzljll the value for ichreadingplan.bkdzljll
     *
     * @mbg.generated
     */
    public void setBkdzljll(Double bkdzljll) {
        this.bkdzljll = bkdzljll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichreadingplan.bkssll
     *
     * @return the value of ichreadingplan.bkssll
     *
     * @mbg.generated
     */
    public Double getBkssll() {
        return bkssll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichreadingplan.bkssll
     *
     * @param bkssll the value for ichreadingplan.bkssll
     *
     * @mbg.generated
     */
    public void setBkssll(Double bkssll) {
        this.bkssll = bkssll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichreadingplan.bkzlljll
     *
     * @return the value of ichreadingplan.bkzlljll
     *
     * @mbg.generated
     */
    public Double getBkzlljll() {
        return bkzlljll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichreadingplan.bkzlljll
     *
     * @param bkzlljll the value for ichreadingplan.bkzlljll
     *
     * @mbg.generated
     */
    public void setBkzlljll(Double bkzlljll) {
        this.bkzlljll = bkzlljll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichreadingplan.bukrs
     *
     * @return the value of ichreadingplan.bukrs
     *
     * @mbg.generated
     */
    public String getBukrs() {
        return bukrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichreadingplan.bukrs
     *
     * @param bukrs the value for ichreadingplan.bukrs
     *
     * @mbg.generated
     */
    public void setBukrs(String bukrs) {
        this.bukrs = bukrs == null ? null : bukrs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichreadingplan.cbpl
     *
     * @return the value of ichreadingplan.cbpl
     *
     * @mbg.generated
     */
    public String getCbpl() {
        return cbpl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichreadingplan.cbpl
     *
     * @param cbpl the value for ichreadingplan.cbpl
     *
     * @mbg.generated
     */
    public void setCbpl(String cbpl) {
        this.cbpl = cbpl == null ? null : cbpl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichreadingplan.cbplt
     *
     * @return the value of ichreadingplan.cbplt
     *
     * @mbg.generated
     */
    public String getCbplt() {
        return cbplt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichreadingplan.cbplt
     *
     * @param cbplt the value for ichreadingplan.cbplt
     *
     * @mbg.generated
     */
    public void setCbplt(String cbplt) {
        this.cbplt = cbplt == null ? null : cbplt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichreadingplan.dataflg
     *
     * @return the value of ichreadingplan.dataflg
     *
     * @mbg.generated
     */
    public String getDataflg() {
        return dataflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichreadingplan.dataflg
     *
     * @param dataflg the value for ichreadingplan.dataflg
     *
     * @mbg.generated
     */
    public void setDataflg(String dataflg) {
        this.dataflg = dataflg == null ? null : dataflg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichreadingplan.expired
     *
     * @return the value of ichreadingplan.expired
     *
     * @mbg.generated
     */
    public String getExpired() {
        return expired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichreadingplan.expired
     *
     * @param expired the value for ichreadingplan.expired
     *
     * @mbg.generated
     */
    public void setExpired(String expired) {
        this.expired = expired == null ? null : expired.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichreadingplan.gkssll
     *
     * @return the value of ichreadingplan.gkssll
     *
     * @mbg.generated
     */
    public Double getGkssll() {
        return gkssll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichreadingplan.gkssll
     *
     * @param gkssll the value for ichreadingplan.gkssll
     *
     * @mbg.generated
     */
    public void setGkssll(Double gkssll) {
        this.gkssll = gkssll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichreadingplan.icdigit
     *
     * @return the value of ichreadingplan.icdigit
     *
     * @mbg.generated
     */
    public Double getIcdigit() {
        return icdigit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichreadingplan.icdigit
     *
     * @param icdigit the value for ichreadingplan.icdigit
     *
     * @mbg.generated
     */
    public void setIcdigit(Double icdigit) {
        this.icdigit = icdigit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichreadingplan.lbkdzljll
     *
     * @return the value of ichreadingplan.lbkdzljll
     *
     * @mbg.generated
     */
    public Double getLbkdzljll() {
        return lbkdzljll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichreadingplan.lbkdzljll
     *
     * @param lbkdzljll the value for ichreadingplan.lbkdzljll
     *
     * @mbg.generated
     */
    public void setLbkdzljll(Double lbkdzljll) {
        this.lbkdzljll = lbkdzljll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichreadingplan.meins
     *
     * @return the value of ichreadingplan.meins
     *
     * @mbg.generated
     */
    public Double getMeins() {
        return meins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichreadingplan.meins
     *
     * @param meins the value for ichreadingplan.meins
     *
     * @mbg.generated
     */
    public void setMeins(Double meins) {
        this.meins = meins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichreadingplan.n_zwstndab
     *
     * @return the value of ichreadingplan.n_zwstndab
     *
     * @mbg.generated
     */
    public Double getnZwstndab() {
        return nZwstndab;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichreadingplan.n_zwstndab
     *
     * @param nZwstndab the value for ichreadingplan.n_zwstndab
     *
     * @mbg.generated
     */
    public void setnZwstndab(Double nZwstndab) {
        this.nZwstndab = nZwstndab;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichreadingplan.note
     *
     * @return the value of ichreadingplan.note
     *
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichreadingplan.note
     *
     * @param note the value for ichreadingplan.note
     *
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichreadingplan.ope_mr
     *
     * @return the value of ichreadingplan.ope_mr
     *
     * @mbg.generated
     */
    public String getOpeMr() {
        return opeMr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichreadingplan.ope_mr
     *
     * @param opeMr the value for ichreadingplan.ope_mr
     *
     * @mbg.generated
     */
    public void setOpeMr(String opeMr) {
        this.opeMr = opeMr == null ? null : opeMr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichreadingplan.opnum
     *
     * @return the value of ichreadingplan.opnum
     *
     * @mbg.generated
     */
    public String getOpnum() {
        return opnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichreadingplan.opnum
     *
     * @param opnum the value for ichreadingplan.opnum
     *
     * @mbg.generated
     */
    public void setOpnum(String opnum) {
        this.opnum = opnum == null ? null : opnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichreadingplan.pernr
     *
     * @return the value of ichreadingplan.pernr
     *
     * @mbg.generated
     */
    public String getPernr() {
        return pernr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichreadingplan.pernr
     *
     * @param pernr the value for ichreadingplan.pernr
     *
     * @mbg.generated
     */
    public void setPernr(String pernr) {
        this.pernr = pernr == null ? null : pernr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichreadingplan.pressure
     *
     * @return the value of ichreadingplan.pressure
     *
     * @mbg.generated
     */
    public Double getPressure() {
        return pressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichreadingplan.pressure
     *
     * @param pressure the value for ichreadingplan.pressure
     *
     * @mbg.generated
     */
    public void setPressure(Double pressure) {
        this.pressure = pressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichreadingplan.readingtime
     *
     * @return the value of ichreadingplan.readingtime
     *
     * @mbg.generated
     */
    public String getReadingtime() {
        return readingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichreadingplan.readingtime
     *
     * @param readingtime the value for ichreadingplan.readingtime
     *
     * @mbg.generated
     */
    public void setReadingtime(String readingtime) {
        this.readingtime = readingtime == null ? null : readingtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichreadingplan.returntime
     *
     * @return the value of ichreadingplan.returntime
     *
     * @mbg.generated
     */
    public String getReturntime() {
        return returntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichreadingplan.returntime
     *
     * @param returntime the value for ichreadingplan.returntime
     *
     * @mbg.generated
     */
    public void setReturntime(String returntime) {
        this.returntime = returntime == null ? null : returntime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichreadingplan.scjhrq
     *
     * @return the value of ichreadingplan.scjhrq
     *
     * @mbg.generated
     */
    public String getScjhrq() {
        return scjhrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichreadingplan.scjhrq
     *
     * @param scjhrq the value for ichreadingplan.scjhrq
     *
     * @mbg.generated
     */
    public void setScjhrq(String scjhrq) {
        this.scjhrq = scjhrq == null ? null : scjhrq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichreadingplan.scjhtm
     *
     * @return the value of ichreadingplan.scjhtm
     *
     * @mbg.generated
     */
    public String getScjhtm() {
        return scjhtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichreadingplan.scjhtm
     *
     * @param scjhtm the value for ichreadingplan.scjhtm
     *
     * @mbg.generated
     */
    public void setScjhtm(String scjhtm) {
        this.scjhtm = scjhtm == null ? null : scjhtm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichreadingplan.tempearture
     *
     * @return the value of ichreadingplan.tempearture
     *
     * @mbg.generated
     */
    public Double getTempearture() {
        return tempearture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichreadingplan.tempearture
     *
     * @param tempearture the value for ichreadingplan.tempearture
     *
     * @mbg.generated
     */
    public void setTempearture(Double tempearture) {
        this.tempearture = tempearture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichreadingplan.termschl
     *
     * @return the value of ichreadingplan.termschl
     *
     * @mbg.generated
     */
    public String getTermschl() {
        return termschl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichreadingplan.termschl
     *
     * @param termschl the value for ichreadingplan.termschl
     *
     * @mbg.generated
     */
    public void setTermschl(String termschl) {
        this.termschl = termschl == null ? null : termschl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichreadingplan.upload_flag
     *
     * @return the value of ichreadingplan.upload_flag
     *
     * @mbg.generated
     */
    public String getUploadFlag() {
        return uploadFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichreadingplan.upload_flag
     *
     * @param uploadFlag the value for ichreadingplan.upload_flag
     *
     * @mbg.generated
     */
    public void setUploadFlag(String uploadFlag) {
        this.uploadFlag = uploadFlag == null ? null : uploadFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichreadingplan.v_zwstndab
     *
     * @return the value of ichreadingplan.v_zwstndab
     *
     * @mbg.generated
     */
    public Double getvZwstndab() {
        return vZwstndab;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichreadingplan.v_zwstndab
     *
     * @param vZwstndab the value for ichreadingplan.v_zwstndab
     *
     * @mbg.generated
     */
    public void setvZwstndab(Double vZwstndab) {
        this.vZwstndab = vZwstndab;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ichreadingplan.zwnummer
     *
     * @return the value of ichreadingplan.zwnummer
     *
     * @mbg.generated
     */
    public String getZwnummer() {
        return zwnummer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ichreadingplan.zwnummer
     *
     * @param zwnummer the value for ichreadingplan.zwnummer
     *
     * @mbg.generated
     */
    public void setZwnummer(String zwnummer) {
        this.zwnummer = zwnummer == null ? null : zwnummer.trim();
    }
}