package com.ecej.po;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MessageInfoExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table messageinfo
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table messageinfo
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table messageinfo
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table messageinfo
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messageinfo
     *
     * @mbg.generated
     */
    public MessageInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messageinfo
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messageinfo
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messageinfo
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messageinfo
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messageinfo
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messageinfo
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messageinfo
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messageinfo
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messageinfo
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messageinfo
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table messageinfo
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria implements Serializable {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMsgcodeIsNull() {
            addCriterion("msgCode is null");
            return (Criteria) this;
        }

        public Criteria andMsgcodeIsNotNull() {
            addCriterion("msgCode is not null");
            return (Criteria) this;
        }

        public Criteria andMsgcodeEqualTo(Integer value) {
            addCriterion("msgCode =", value, "msgcode");
            return (Criteria) this;
        }

        public Criteria andMsgcodeNotEqualTo(Integer value) {
            addCriterion("msgCode <>", value, "msgcode");
            return (Criteria) this;
        }

        public Criteria andMsgcodeGreaterThan(Integer value) {
            addCriterion("msgCode >", value, "msgcode");
            return (Criteria) this;
        }

        public Criteria andMsgcodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("msgCode >=", value, "msgcode");
            return (Criteria) this;
        }

        public Criteria andMsgcodeLessThan(Integer value) {
            addCriterion("msgCode <", value, "msgcode");
            return (Criteria) this;
        }

        public Criteria andMsgcodeLessThanOrEqualTo(Integer value) {
            addCriterion("msgCode <=", value, "msgcode");
            return (Criteria) this;
        }

        public Criteria andMsgcodeIn(List<Integer> values) {
            addCriterion("msgCode in", values, "msgcode");
            return (Criteria) this;
        }

        public Criteria andMsgcodeNotIn(List<Integer> values) {
            addCriterion("msgCode not in", values, "msgcode");
            return (Criteria) this;
        }

        public Criteria andMsgcodeBetween(Integer value1, Integer value2) {
            addCriterion("msgCode between", value1, value2, "msgcode");
            return (Criteria) this;
        }

        public Criteria andMsgcodeNotBetween(Integer value1, Integer value2) {
            addCriterion("msgCode not between", value1, value2, "msgcode");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createtime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createtime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createtime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createtime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createtime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createtime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createtime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createtime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createtime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createtime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createtime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andHasreadIsNull() {
            addCriterion("hasRead is null");
            return (Criteria) this;
        }

        public Criteria andHasreadIsNotNull() {
            addCriterion("hasRead is not null");
            return (Criteria) this;
        }

        public Criteria andHasreadEqualTo(Integer value) {
            addCriterion("hasRead =", value, "hasread");
            return (Criteria) this;
        }

        public Criteria andHasreadNotEqualTo(Integer value) {
            addCriterion("hasRead <>", value, "hasread");
            return (Criteria) this;
        }

        public Criteria andHasreadGreaterThan(Integer value) {
            addCriterion("hasRead >", value, "hasread");
            return (Criteria) this;
        }

        public Criteria andHasreadGreaterThanOrEqualTo(Integer value) {
            addCriterion("hasRead >=", value, "hasread");
            return (Criteria) this;
        }

        public Criteria andHasreadLessThan(Integer value) {
            addCriterion("hasRead <", value, "hasread");
            return (Criteria) this;
        }

        public Criteria andHasreadLessThanOrEqualTo(Integer value) {
            addCriterion("hasRead <=", value, "hasread");
            return (Criteria) this;
        }

        public Criteria andHasreadIn(List<Integer> values) {
            addCriterion("hasRead in", values, "hasread");
            return (Criteria) this;
        }

        public Criteria andHasreadNotIn(List<Integer> values) {
            addCriterion("hasRead not in", values, "hasread");
            return (Criteria) this;
        }

        public Criteria andHasreadBetween(Integer value1, Integer value2) {
            addCriterion("hasRead between", value1, value2, "hasread");
            return (Criteria) this;
        }

        public Criteria andHasreadNotBetween(Integer value1, Integer value2) {
            addCriterion("hasRead not between", value1, value2, "hasread");
            return (Criteria) this;
        }

        public Criteria andMsgcontentIsNull() {
            addCriterion("msgContent is null");
            return (Criteria) this;
        }

        public Criteria andMsgcontentIsNotNull() {
            addCriterion("msgContent is not null");
            return (Criteria) this;
        }

        public Criteria andMsgcontentEqualTo(String value) {
            addCriterion("msgContent =", value, "msgcontent");
            return (Criteria) this;
        }

        public Criteria andMsgcontentNotEqualTo(String value) {
            addCriterion("msgContent <>", value, "msgcontent");
            return (Criteria) this;
        }

        public Criteria andMsgcontentGreaterThan(String value) {
            addCriterion("msgContent >", value, "msgcontent");
            return (Criteria) this;
        }

        public Criteria andMsgcontentGreaterThanOrEqualTo(String value) {
            addCriterion("msgContent >=", value, "msgcontent");
            return (Criteria) this;
        }

        public Criteria andMsgcontentLessThan(String value) {
            addCriterion("msgContent <", value, "msgcontent");
            return (Criteria) this;
        }

        public Criteria andMsgcontentLessThanOrEqualTo(String value) {
            addCriterion("msgContent <=", value, "msgcontent");
            return (Criteria) this;
        }

        public Criteria andMsgcontentLike(String value) {
            addCriterion("msgContent like", value, "msgcontent");
            return (Criteria) this;
        }

        public Criteria andMsgcontentNotLike(String value) {
            addCriterion("msgContent not like", value, "msgcontent");
            return (Criteria) this;
        }

        public Criteria andMsgcontentIn(List<String> values) {
            addCriterion("msgContent in", values, "msgcontent");
            return (Criteria) this;
        }

        public Criteria andMsgcontentNotIn(List<String> values) {
            addCriterion("msgContent not in", values, "msgcontent");
            return (Criteria) this;
        }

        public Criteria andMsgcontentBetween(String value1, String value2) {
            addCriterion("msgContent between", value1, value2, "msgcontent");
            return (Criteria) this;
        }

        public Criteria andMsgcontentNotBetween(String value1, String value2) {
            addCriterion("msgContent not between", value1, value2, "msgcontent");
            return (Criteria) this;
        }

        public Criteria andMsgreceiverIsNull() {
            addCriterion("msgReceiver is null");
            return (Criteria) this;
        }

        public Criteria andMsgreceiverIsNotNull() {
            addCriterion("msgReceiver is not null");
            return (Criteria) this;
        }

        public Criteria andMsgreceiverEqualTo(String value) {
            addCriterion("msgReceiver =", value, "msgreceiver");
            return (Criteria) this;
        }

        public Criteria andMsgreceiverNotEqualTo(String value) {
            addCriterion("msgReceiver <>", value, "msgreceiver");
            return (Criteria) this;
        }

        public Criteria andMsgreceiverGreaterThan(String value) {
            addCriterion("msgReceiver >", value, "msgreceiver");
            return (Criteria) this;
        }

        public Criteria andMsgreceiverGreaterThanOrEqualTo(String value) {
            addCriterion("msgReceiver >=", value, "msgreceiver");
            return (Criteria) this;
        }

        public Criteria andMsgreceiverLessThan(String value) {
            addCriterion("msgReceiver <", value, "msgreceiver");
            return (Criteria) this;
        }

        public Criteria andMsgreceiverLessThanOrEqualTo(String value) {
            addCriterion("msgReceiver <=", value, "msgreceiver");
            return (Criteria) this;
        }

        public Criteria andMsgreceiverLike(String value) {
            addCriterion("msgReceiver like", value, "msgreceiver");
            return (Criteria) this;
        }

        public Criteria andMsgreceiverNotLike(String value) {
            addCriterion("msgReceiver not like", value, "msgreceiver");
            return (Criteria) this;
        }

        public Criteria andMsgreceiverIn(List<String> values) {
            addCriterion("msgReceiver in", values, "msgreceiver");
            return (Criteria) this;
        }

        public Criteria andMsgreceiverNotIn(List<String> values) {
            addCriterion("msgReceiver not in", values, "msgreceiver");
            return (Criteria) this;
        }

        public Criteria andMsgreceiverBetween(String value1, String value2) {
            addCriterion("msgReceiver between", value1, value2, "msgreceiver");
            return (Criteria) this;
        }

        public Criteria andMsgreceiverNotBetween(String value1, String value2) {
            addCriterion("msgReceiver not between", value1, value2, "msgreceiver");
            return (Criteria) this;
        }

        public Criteria andMsgtypeIsNull() {
            addCriterion("msgType is null");
            return (Criteria) this;
        }

        public Criteria andMsgtypeIsNotNull() {
            addCriterion("msgType is not null");
            return (Criteria) this;
        }

        public Criteria andMsgtypeEqualTo(String value) {
            addCriterion("msgType =", value, "msgtype");
            return (Criteria) this;
        }

        public Criteria andMsgtypeNotEqualTo(String value) {
            addCriterion("msgType <>", value, "msgtype");
            return (Criteria) this;
        }

        public Criteria andMsgtypeGreaterThan(String value) {
            addCriterion("msgType >", value, "msgtype");
            return (Criteria) this;
        }

        public Criteria andMsgtypeGreaterThanOrEqualTo(String value) {
            addCriterion("msgType >=", value, "msgtype");
            return (Criteria) this;
        }

        public Criteria andMsgtypeLessThan(String value) {
            addCriterion("msgType <", value, "msgtype");
            return (Criteria) this;
        }

        public Criteria andMsgtypeLessThanOrEqualTo(String value) {
            addCriterion("msgType <=", value, "msgtype");
            return (Criteria) this;
        }

        public Criteria andMsgtypeLike(String value) {
            addCriterion("msgType like", value, "msgtype");
            return (Criteria) this;
        }

        public Criteria andMsgtypeNotLike(String value) {
            addCriterion("msgType not like", value, "msgtype");
            return (Criteria) this;
        }

        public Criteria andMsgtypeIn(List<String> values) {
            addCriterion("msgType in", values, "msgtype");
            return (Criteria) this;
        }

        public Criteria andMsgtypeNotIn(List<String> values) {
            addCriterion("msgType not in", values, "msgtype");
            return (Criteria) this;
        }

        public Criteria andMsgtypeBetween(String value1, String value2) {
            addCriterion("msgType between", value1, value2, "msgtype");
            return (Criteria) this;
        }

        public Criteria andMsgtypeNotBetween(String value1, String value2) {
            addCriterion("msgType not between", value1, value2, "msgtype");
            return (Criteria) this;
        }

        public Criteria andMsgtypedescIsNull() {
            addCriterion("msgTypeDesc is null");
            return (Criteria) this;
        }

        public Criteria andMsgtypedescIsNotNull() {
            addCriterion("msgTypeDesc is not null");
            return (Criteria) this;
        }

        public Criteria andMsgtypedescEqualTo(String value) {
            addCriterion("msgTypeDesc =", value, "msgtypedesc");
            return (Criteria) this;
        }

        public Criteria andMsgtypedescNotEqualTo(String value) {
            addCriterion("msgTypeDesc <>", value, "msgtypedesc");
            return (Criteria) this;
        }

        public Criteria andMsgtypedescGreaterThan(String value) {
            addCriterion("msgTypeDesc >", value, "msgtypedesc");
            return (Criteria) this;
        }

        public Criteria andMsgtypedescGreaterThanOrEqualTo(String value) {
            addCriterion("msgTypeDesc >=", value, "msgtypedesc");
            return (Criteria) this;
        }

        public Criteria andMsgtypedescLessThan(String value) {
            addCriterion("msgTypeDesc <", value, "msgtypedesc");
            return (Criteria) this;
        }

        public Criteria andMsgtypedescLessThanOrEqualTo(String value) {
            addCriterion("msgTypeDesc <=", value, "msgtypedesc");
            return (Criteria) this;
        }

        public Criteria andMsgtypedescLike(String value) {
            addCriterion("msgTypeDesc like", value, "msgtypedesc");
            return (Criteria) this;
        }

        public Criteria andMsgtypedescNotLike(String value) {
            addCriterion("msgTypeDesc not like", value, "msgtypedesc");
            return (Criteria) this;
        }

        public Criteria andMsgtypedescIn(List<String> values) {
            addCriterion("msgTypeDesc in", values, "msgtypedesc");
            return (Criteria) this;
        }

        public Criteria andMsgtypedescNotIn(List<String> values) {
            addCriterion("msgTypeDesc not in", values, "msgtypedesc");
            return (Criteria) this;
        }

        public Criteria andMsgtypedescBetween(String value1, String value2) {
            addCriterion("msgTypeDesc between", value1, value2, "msgtypedesc");
            return (Criteria) this;
        }

        public Criteria andMsgtypedescNotBetween(String value1, String value2) {
            addCriterion("msgTypeDesc not between", value1, value2, "msgtypedesc");
            return (Criteria) this;
        }

        public Criteria andTasktypeIsNull() {
            addCriterion("taskType is null");
            return (Criteria) this;
        }

        public Criteria andTasktypeIsNotNull() {
            addCriterion("taskType is not null");
            return (Criteria) this;
        }

        public Criteria andTasktypeEqualTo(String value) {
            addCriterion("taskType =", value, "tasktype");
            return (Criteria) this;
        }

        public Criteria andTasktypeNotEqualTo(String value) {
            addCriterion("taskType <>", value, "tasktype");
            return (Criteria) this;
        }

        public Criteria andTasktypeGreaterThan(String value) {
            addCriterion("taskType >", value, "tasktype");
            return (Criteria) this;
        }

        public Criteria andTasktypeGreaterThanOrEqualTo(String value) {
            addCriterion("taskType >=", value, "tasktype");
            return (Criteria) this;
        }

        public Criteria andTasktypeLessThan(String value) {
            addCriterion("taskType <", value, "tasktype");
            return (Criteria) this;
        }

        public Criteria andTasktypeLessThanOrEqualTo(String value) {
            addCriterion("taskType <=", value, "tasktype");
            return (Criteria) this;
        }

        public Criteria andTasktypeLike(String value) {
            addCriterion("taskType like", value, "tasktype");
            return (Criteria) this;
        }

        public Criteria andTasktypeNotLike(String value) {
            addCriterion("taskType not like", value, "tasktype");
            return (Criteria) this;
        }

        public Criteria andTasktypeIn(List<String> values) {
            addCriterion("taskType in", values, "tasktype");
            return (Criteria) this;
        }

        public Criteria andTasktypeNotIn(List<String> values) {
            addCriterion("taskType not in", values, "tasktype");
            return (Criteria) this;
        }

        public Criteria andTasktypeBetween(String value1, String value2) {
            addCriterion("taskType between", value1, value2, "tasktype");
            return (Criteria) this;
        }

        public Criteria andTasktypeNotBetween(String value1, String value2) {
            addCriterion("taskType not between", value1, value2, "tasktype");
            return (Criteria) this;
        }

        public Criteria andUpdatetableIsNull() {
            addCriterion("updateTable is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetableIsNotNull() {
            addCriterion("updateTable is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetableEqualTo(String value) {
            addCriterion("updateTable =", value, "updatetable");
            return (Criteria) this;
        }

        public Criteria andUpdatetableNotEqualTo(String value) {
            addCriterion("updateTable <>", value, "updatetable");
            return (Criteria) this;
        }

        public Criteria andUpdatetableGreaterThan(String value) {
            addCriterion("updateTable >", value, "updatetable");
            return (Criteria) this;
        }

        public Criteria andUpdatetableGreaterThanOrEqualTo(String value) {
            addCriterion("updateTable >=", value, "updatetable");
            return (Criteria) this;
        }

        public Criteria andUpdatetableLessThan(String value) {
            addCriterion("updateTable <", value, "updatetable");
            return (Criteria) this;
        }

        public Criteria andUpdatetableLessThanOrEqualTo(String value) {
            addCriterion("updateTable <=", value, "updatetable");
            return (Criteria) this;
        }

        public Criteria andUpdatetableLike(String value) {
            addCriterion("updateTable like", value, "updatetable");
            return (Criteria) this;
        }

        public Criteria andUpdatetableNotLike(String value) {
            addCriterion("updateTable not like", value, "updatetable");
            return (Criteria) this;
        }

        public Criteria andUpdatetableIn(List<String> values) {
            addCriterion("updateTable in", values, "updatetable");
            return (Criteria) this;
        }

        public Criteria andUpdatetableNotIn(List<String> values) {
            addCriterion("updateTable not in", values, "updatetable");
            return (Criteria) this;
        }

        public Criteria andUpdatetableBetween(String value1, String value2) {
            addCriterion("updateTable between", value1, value2, "updatetable");
            return (Criteria) this;
        }

        public Criteria andUpdatetableNotBetween(String value1, String value2) {
            addCriterion("updateTable not between", value1, value2, "updatetable");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updatetime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updatetime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("updatetime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("updatetime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("updatetime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updatetime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("updatetime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("updatetime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("updatetime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("updatetime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("updatetime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("updatetime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table messageinfo
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table messageinfo
     *
     * @mbg.generated
     */
    public static class Criterion implements Serializable {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}